### ISSUE TITLE
Add table aws_docdb_cluster

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-aws#1006]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.
[AWS Ref](https://docs.aws.amazon.com/documentdb/latest/developerguide/mongo-apis.html)
[Terraform Ref](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdb_cluster)
[GO SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/docdb/)

**Comment by cbruno10** [comment]
Re-opening as the PR has been re-opened as well, please see https://github.com/turbot/steampipe-plugin-aws/pull/1019#issuecomment-1233119507 for more info.
