### ISSUE TITLE
Add table aws_docdb_cluster_instance

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-aws#1007]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

[AWS Ref](https://docs.aws.amazon.com/documentdb/latest/developerguide/backup_restore-share_cluster_snapshots.html)
[Terraform Ref](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdb_cluster)
[GO SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/docdb/)

**Comment by rajlearner17** [comment]
Not required

**Comment by rajlearner17** [comment]
As discussed, in the current state, `aws_rds_db_instance` returns the result for DocDB instance. However, a separate API is available, which can be leveraged to have a separate table like `aws_docdb_cluster`.

**Comment by misraved** [comment]
https://github.com/turbot/steampipe-mod-aws-compliance/issues/547
