### ISSUE TITLE
Add support for cost usage filtering / grouping by Tag

### ISSUE THREAD

**Issue by johnsmyth** [turbot/steampipe-plugin-aws#1058]
**Is your feature request related to a problem? Please describe.**
The `aws_cost_usage` table only allows you to specify dimensions for finding aws costs.   A user should be able to use tags and/or cost categories instead / as well.

**Describe the solution you'd like**
The API allows you to specify 3 types of filters - dimension, tag, and cost category.  The table is written to specify only dimensions, not tags or cost categories.  The table implementation pre-dates optional key columns for list quals - we should revisit the design of this table and add optional list quals, or add a new table with tag and cost category filtering capabilities.

**Additional context**
Steampipe slack thread:  https://steampipe.slack.com/archives/C01UECB59A7/p1654111791546649

**Comment by ParthaI** [comment]
@johnsmyth @cbruno10, I have tested the API with tag support, and the response is inconsistent. Also in CLI, the behavior is the same as AWS GO SDK API.

Observations: 
1. If I am passing the correct tag key and correct tag value, I am getting the result. (expected)
2. If I am passing the incorrect tag key and incorrect tag value, I am getting the result. (Not expected)
3. If any of the tag key/tag values is incorrect I am also getting the result. (Not expected)

I have raised an AWS support request (Case ID: 10185237031) and also raised an issue in [AWS GO SDK](https://github.com/aws/aws-sdk-go/issues/4429).
