### ISSUE TITLE
Add table aws_amplify_app

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-aws#1073]
**References**
API actions:
- https://docs.aws.amazon.com/amplify/latest/APIReference/API_GetApp.html
- https://docs.aws.amazon.com/amplify/latest/APIReference/API_ListApps.html

Terraform resource - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/amplify_app

**Comment by omerosaienni** [comment]
Useful notes:

__AWS Amplify endpoints and quotas__
https://docs.aws.amazon.com/general/latest/gr/amplify.html
