### ISSUE TITLE
Add column vpcs in table aws_route53_zone

### ISSUE THREAD

**Issue by take-five** [turbot/steampipe-plugin-aws#1081]
It is possible to retrieve VPCs associated with a hosted zone using [GetHostedZone](https://docs.aws.amazon.com/sdk-for-go/api/service/route53/#Route53.GetHostedZone) functions, which returns [GetHostedZoneOutput](https://docs.aws.amazon.com/sdk-for-go/api/service/route53/#GetHostedZoneOutput) structure, which contains information about associated VPCs.

It would be nice if we had this information in table `aws_route53_zone`, this way it would be possible to reliably join alias records from private zones with actual AWS resources in the same VPC.

**Comment by rajlearner17** [comment]
@take-five Thanks for using Steampipe!! 👍 

Good details to understand your requirement. Would it be possible to know how steampipe is helping you? What exactly is your use case to use Steampipe?

**Comment by take-five** [comment]
Yeah. I'd like to use Steampipe to find DNS records in private hosted zones that point at "dead" EC2-instances. Of course, I could have done it manually, but we have many hosted zones and I thought that Steampipe would be a good fit for this use case.

Basically, I'd like to be able to run a query like this (simplified, column names might be wrong):
```sql
SELECT r.*
FROM aws_route53_hosted_zone z
INNER JOIN aws_route53_record r ON z.id = r.hosted_zone_id
LEFT JOIN aws_ec2_instance i ON z.vpc_id = i.vpc_id AND r.value = i.private_ip_address
WHERE z.is_private
AND r.type = 'A'
AND r.value LIKE '10.%'
AND NOT EXISTS (
  SELECT 1 FROM aws_ec2_instance i WHERE i.vpc_id = z.vpc_id AND i.private_ip_address = r.value
)
```

**Comment by rajlearner17** [comment]
@take-five 

We have added the required column in this [PR](https://github.com/turbot/steampipe-plugin-aws/pull/1085)

If you want to give it a try before release and let us know if it solves your requirement

`Check out this branch & run make`

1. git clone https://github.com/turbot/steampipe-plugin-aws.git
2. cd steampipe-plugin-aws
3. git checkout `issue-1081`
4. make
(Note in case you have already this checked out aws-plugin repo, prefer to checkout `main` > `git pull` > Then `git checkout issue-1081 `branch)

**Comment by take-five** [comment]
@rajlearner17 Wow, thanks for quick reaction!

I tested it locally and got some obscure error.
Here's my query:
```sql
select *
from aws_prod.aws_route53_record r
  join aws_prod.aws_route53_zone z on r.zone_id = z.id
  join jsonb_array_elements_text(r.records) record on true
  join jsonb_array_elements(z.vpcs) zv on true
  left join aws_prod.aws_ec2_instance i on i.vpc_id = zv ->> 'VPCId' and private_ip_address = record::inet
where z.private_zone and r.type = 'A'
  and record like '10.0.%'
  and i.instance_id is null;
```

I get this error
```
Error: unexpected EOF
```

I think the join on "private_ip_address = record::inet" is the cause here, but I'm not sure

**Comment by cbruno10** [comment]
@take-five I believe that bug is related to an ongoing issue, https://github.com/turbot/steampipe-postgres-fdw/issues/192, affecting joins with functions like `jsonb_array_elements`.

Is the new column working well for you otherwise?
