### ISSUE TITLE
AWS S3 bucket size

### ISSUE THREAD

**Issue by moisei** [turbot/steampipe-plugin-aws#1086]
S3 storage is a common source of expenses, and in order to control the cost would be useful to query the size of the S3 bucket and the count of the objects. Also, as the price of S3 storage depends on objects' `StorageClass`, grouping by the `StorageClass` would provide even better observation.

**Comment by rajlearner17** [comment]
@moisei Appreciate using Steampipe!!

Just for reference, [ the discussion thread from the slack community channel](https://steampipe.slack.com/archives/C01UECB59A7/p1655337120909809)

**Comment by cbruno10** [comment]
@moisei One potential way we could get this information is by creating tables to get the [daily storage metrics for buckets](https://docs.aws.amazon.com/AmazonS3/latest/userguide/metrics-dimensions.html#s3-cloudwatch-metrics), which includes the metrics `BucketSizeBytes` and `NumberOfObjects`. Would these metrics give you the type of data you're looking for?

We'd need to update how our CloudWatch metric tables can set dimensions (currently they can only pass in one dimension key/value pair, but all of the S3 bucket daily ones need to pass in 2, `BucketName`, and `StorageType`), and also need to determine how we can get each resource's identifier, e.g., bucket name, from the list of dimensions.

**Comment by moisei** [comment]
@cbruno10  up to me, it would be perfectly fine as I am not looking for real-time data.

**Comment by moisei** [comment]
maybe it is also possible to add AWS Glacier data to this table, as it is another potential source of the expenses
