### ISSUE TITLE
AWS IAM queries fail when using aws-vault credentials with access key pairs

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-aws#1127]
Original issue was submitted in https://github.com/turbot/steampipe/issues/242#issuecomment-1171567086 by [@jweyrich](https://github.com/jweyrich).

> When I run a query on IAM on account `prod` using aws-vault, example:
> 
> ```
> aws-vault exec prod -- steampipe query "select name from aws_iam_user;"
> ```
> 
> It fails with:
> 
> > Warning: executeQueries: query 1 of 1 failed: ERROR: rpc error: code = Unknown desc = InvalidClientTokenId: The security token included in the request is invalid
> > status code: 403, request id:  (SQLSTATE HV000)
> 
> Querying other services (non-IAM) on the same account/profile seem to work fine. Example:
> 
> ```
> aws-vault exec prod -- steampipe query "select name from aws_s3_bucket;"
> ```
> 
> The s3 list works flawlessly.
> 
> Additionally, the profile `prod` is configured using an access key + secret key from an user with `AdministratorAccess` policy. And I have another AWS account configured on profile `homolog` which is accessed thru `AssumeRole` from the `prod` account/profile. The same IAM query works fine for `homolog`.
> 
> Here's my env environment:
> 
> > macOS 10.15.7
> > aws-vault v6.6.0
> > steampipe version 0.15.0
> > plugins:
> > | hub.steampipe.io/plugins/turbot/aws@latest       | 0.66.0  | aws         |
> 
> Not sure what it is.

**Comment by jweyrich** [comment]
> I wonder if it's due to the limitation of using certain IAM and STS actions when using temporary credentials, as noted here [Temporary credentials limitations with STS, IAM](https://github.com/99designs/aws-vault/blob/master/USAGE.md#temporary-credentials-limitations-with-sts-iam)

Thanks for bringing these limitations to my attention. I've never read about them.

> A recommendation from https://github.com/99designs/aws-vault/issues/702 is to use the --no-session option, or to setup MFA on the user.

Indeed. It worked when I ran with `--no-session`. I'll try to dig into that when I find some spare time.
Thank you for all the information! That was super fast. You rock!🥇

**Comment by cbruno10** [comment]
@jweyrich No problem, glad that worked! FYI I've added some more information around STS + IAM limitations with temp creds in aws-vault in https://github.com/turbot/steampipe-plugin-aws/commit/4df337447ed60862428a4fd6c4100d36821c3792, which we'll release in an upcoming version so that content will appear on https://hub.steampipe.io/plugins/turbot/aws#aws-vault-credentials.
