### ISSUE TITLE
Tables querying CloudWatch Logs should include timestamp ranges in examples

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe-plugin-aws#1132]
Tables that query CloudWatch Logs can be slow to return when there is a large history of log entries. Our examples look tempting, but can be a slow / poor experience as a result. (This is mostly because CW Logs just takes a long time to query a large number of streams.)

We should update the examples to include a time range by default, e.g. `and timestamp > now() - interval '1 hour'` or similar to create a better starting point for users.

Tables:
* aws_cloudtrail_trail_event
* aws_cloudwatch_log_event
* aws_vpc_flow_log_event

**Comment by omerosaienni** [comment]
- [ ] aws_cloudwatch_log_event
- [ ] aws_cloudtrail_trail_event
- [ } aws_vpc_flow_log_event
