### ISSUE TITLE
Getting `MissingRegion: could not find region configuration` error in table aws_servicequotas_service_quota

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-aws#1138]
**Describe the bug**
Getting below error while querying table `aws_servicequotas_service_quota`(other tables are working fine)
> select * from aws_servicequotas_service_quota
Error: MissingRegion: could not find region configuration (SQLSTATE HV000)

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by bigdatasourav** [comment]
As discussed with @khushboo9024, the issue was with her config file setup `~/.aws/config`. It is working fine now.
