### ISSUE TITLE
Add table aws_redshiftserverless_namespace

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-aws#1162]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.
AWS GO SDK v1 - https://docs.aws.amazon.com/sdk-for-go/api/service/redshiftserverless/
AWS GO SDK v2 - https://github.com/aws/aws-sdk-go-v2/releases

**Comment by bigdatasourav** [comment]
https://github.com/turbot/steampipe-plugin-aws/pull/1305
