### ISSUE TITLE
Rename column name heath_check_targets

### ISSUE THREAD

**Issue by tinder-jonathanwalker** [turbot/steampipe-plugin-aws#1178]
**Describe the bug**
Column `heath_check_targets` appears to be misspelled on the table `aws_ec2_classic_load_balancer`.

https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_ec2_classic_load_balancer.go#L152-L157
https://github.com/turbot/steampipe-plugin-aws/blob/main/docs/tables/aws_ec2_classic_load_balancer.md?plain=1#L66

**Comment by cbruno10** [comment]
D'oh, completely missed the missing letter. We'll add in the missing letter, thanks!
