### ISSUE TITLE
Add table aws_globalaccelerator_accelerator

### ISSUE THREAD

**Issue by tinder-jonathanwalker** [turbot/steampipe-plugin-aws#1181]
Add the table for AWS Global Accelerators.

**References**
https://docs.aws.amazon.com/global-accelerator/latest/api/API_ListAccelerators.html
https://docs.aws.amazon.com/sdk-for-go/api/service/globalaccelerator/#GlobalAccelerator.ListCustomRoutingAccelerators

**Comment by cbruno10** [comment]
Hey @tinder-jonathanwalker , there's currently a PR open to add this table (along with some others), https://github.com/turbot/steampipe-plugin-aws/pull/1091. The PR author was away on vacation a bit and has some additional changes to make to get the PR ready, but I believe it should be ready soon.

**Comment by cbruno10** [comment]
Removing stale label as https://github.com/turbot/steampipe-plugin-aws/pull/1091 is under review/almost ready to be merged in.
