### ISSUE TITLE
AccessDeniedException breaks if an S3 resource policy denies read access

### ISSUE THREAD

**Issue by Chan9390** [turbot/steampipe-plugin-aws#1192]
**Describe the bug**
We have 100s of bucket in which few buckets are very critical and have a resource policy to restrict access to every IAM user/role except few. In such an environment, trying to run `select * from aws_s3_bucket` gives an error `Error: AccessDenied: Access Denied status code: 403, request id: XXXXXXX, host id: XXXXXXXXXX` along with unreliable results. 

The results include buckets until it reaches 403 error. The number of results might not be constant.

**Steampipe version (`steampipe -v`)**
`steampipe version 0.15.4`

**Plugin version (`steampipe plugin list`)**

```
+--------------------------------------------------+---------+-------------+
| Name                                             | Version | Connections |
+--------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/aws@latest       | 0.71.0  | aws         |
| hub.steampipe.io/plugins/turbot/steampipe@latest | 0.5.0   | steampipe   |
+--------------------------------------------------+---------+-------------+
```

**To reproduce**
Create an S3 bucket in AWS account containing few S3 buckets. For this new bucket, set the resource policy like the following:

*NOTE:* Please update the account ID, rolename and the bucket name before adding this resource policy.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::111111111111:role/ROLENAME"
            },
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::MyExampleBucket"
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::111111111111:role/ROLENAME"
            },
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::MyExampleBucket/*"
        },
        {
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::MyExampleBucket",
                "arn:aws:s3:::MyExampleBucket/*"
            ],
            "Condition": {
                "StringNotLike": {
                    "aws:userId": [
                        "AROAEXAMPLEID:*",
                        "111111111111"
                    ]
                }
            }
        }
    ]
}
```

Setup IAM credentials having ReadOnly access across the account, open steampipe query and then execute `select * from aws_s3_bucket`. Or you don't want to use `*` then execute `select tags from aws_s3_bucket`.

**Expected behavior**
Allow fetching all buckets for which the IAM user has access. Maybe having a user variable in the plugin to ignore access denied errors and fetch all the accessible resource also helps.

**Comment by misraved** [comment]
@Chan9390 Sorry to hear that you are running into issues with the AWS S3 bucket table.

We do have a provision to ignore the access denied errors. Please take a look at the configuration section - https://hub.steampipe.io/plugins/turbot/aws#configuration

If you use the `ignore_error_codes` config argument, you can ignore all the access denied errors.

You can uncomment the `ignore_error_codes` config argument in your `aws.spc` file to be able to use this feature.

Hopefully, this solves your issue. Please let us know in case you have more questions about this.

**Comment by Chan9390** [comment]
Thank you @misraved, this solved my issue. 💯
