### ISSUE TITLE
Add table aws_ecr_image

### ISSUE THREAD

**Issue by darrenlewis1985** [turbot/steampipe-plugin-aws#1196]
When using the the `aws_ecr_repository` table the `image_details` field/array seems to be truncated to only return 100 images even if there are more than 100 images in the ECR repository in AWS. I have some repositories with around 2000 images in. The AWS CLI `describe-images` call supports the `--no-paginate` and `--max-items` parameters so I think it should be possible to return all of the images https://docs.aws.amazon.com/cli/latest/reference/ecr/describe-images.html#describe-images.

This was raised on [Slack](https://steampipe.slack.com/archives/C02NMCM2QKE/p1659372324046439) and was asked to raise an issue here asking for a new table `we should probably break it out as a new table aws_ecr_image since we try to avoid pagination for sub-API calls in a single column`.

The example SQL I'm trying to run is to count the number of images in each repository in ECR.
```
select
    repository_name,
    jsonb_array_length(image_details) as image_count
from
    aws_ecr_repository
```

**Comment by ParthaI** [comment]
Hey @darrenlewis1985, we have provided a fix for now in this [PR](https://github.com/turbot/steampipe-plugin-aws/pull/1198). Could you please try it out and let us know your feedback?

```
1. git clone https://github.com/turbot/steampipe-plugin-aws.git
2. cd steampipe-plugin-aws
3. git checkout issue-1196
4. make
5. Run your query
(Note in case you have already this checked out aws-plugin repo, prefer to checkout main > git pull > git checkout issue-1196 branch)
```

We will check for the new table implementation in our v2 migration phase.

**Comment by e-gineer** [comment]
@ParthaI this fix adds pagination to the column rather than a new table - which sense inconsistent with our other tables and like it could make those queries very expensive.

Any reason why we are taking that approach in this case? Would a breaking change be better here?

**Comment by ParthaI** [comment]
Hi @e-gineer,

We understand what you are asking for, we arrived to implement this fix in the table itself at this stage without initiating a breaking change. We have a similar situation in some existing tables e.g.
https://github.com/turbot/steampipe-plugin-aws/blob/eaa5aefd367c91d9dd4f735d014e1dd582446b95/aws/table_aws_accessanalyzer_analyzer.go#L205

The similar situation for a few tables with tags column.

Should we then proceed to have a breaking change for this ECR table?

**Comment by e-gineer** [comment]
Thanks @ParthaI 

I believe that we should have a rule of "no pagination within column data". Basically, if the data for a column is potentially so big / expensive to retrieve that it needs pagination, then we should make it a table instead.

While we want to minimize breaking changes, we are still in v0.x and I'd personally argue any pagination inside columns was a bug in the first place.

IMO we should:
* Add the new table
* Keep the column as 1 page only (existing behavior)
* Mark the column as deprecated, with a reference to the new table
* Update examples for the existing table and the new table to show how to use them together
* Update any existing mods that use the table as appropriate
* Finally, after say 3 months, remove the deprecated column
