### ISSUE TITLE
inconsistent results in `aws_securityhub_finding` using `compliance_status` qual

### ISSUE THREAD

**Issue by tinder-tder** [turbot/steampipe-plugin-aws#1201]
**Describe the bug**
When querying the aws_securityhub_finding table, if we query using `compliance_status = 'FAILED'` we are getting different results than if we do `compliance_status like 'FAILED'`.  Mainly we get 0 results if we do an `= 'FAILED'` or `in ('FAILED')`
but using `like` works

**Steampipe version (`steampipe -v`)**
v0.15.1

**Plugin version (`steampipe plugin list`)**
 v0.71.0

**To reproduce**
```
Welcome to Steampipe v0.15.1
For more information, type .help
> select count(*) from aws_securityhub_finding where product_name = 'Config' and compliance_status = 'FAILED'
+-------+
| count |
+-------+
| 0     |
+-------+
> select count(*) from aws_securityhub_finding where product_name = 'Config' and compliance_status like 'FAILED'
+-------+
| count |
+-------+
| 86    |
+-------+
> select count(*) from aws_securityhub_finding where product_name = 'Config' and compliance_status in ('FAILED')
+-------+
| count |
+-------+
| 0     |
+-------+
> 
```

**Expected behavior**
all 3 queries should be returning the same results

**Comment by misraved** [comment]
Thanks @tinder-tder for creating this issue with so much information 👍 .

Extremely sorry for the delayed response. I was able to replicate this issue in my local and I suspect it could be an issue with the steampipe-plugin-sdk.

I will continue to test this out to zero in on the root cause of this issue (just want to be sure that the underlying API is not behaving in a funky manner). 

I will add the details in this thread shortly 👍 .

**Comment by tinder-tder** [comment]
@misraved is this still being worked on?

**Comment by misraved** [comment]
Sorry for the delayed response @tinder-tder. I haven't had a chance to take another deep dive into it. I will be investigating this issue tomorrow and rest assured, the fix will be out shortly.

Thank you for your patience 👍.

**Comment by tinder-tder** [comment]
@misraved I just tested with the latest 0.87.0 aws plugin and it looks like its resolved (just getting api limited now).  I will close this.  Thanks for the followup!
