### ISSUE TITLE
Add table aws_ses_domain_identity or aws_ses_identity

### ISSUE THREAD

**Issue by janritter** [turbot/steampipe-plugin-aws#1203]
Currently the Steampipe AWS plugin has the table `aws_ses_email_identity`, to also query SES domain identities I would like to add a new table.
I'm still not sure which option would be the best, so I'm interested in your feedback.

## Ideas

These two tables would be an idea:

1. aws_ses_domain_identity

Similar to the existing `aws_ses_email_identity` table a new table would be added which filters for `Domain` instead of `EmailAddress`

2. aws_ses_identity

Instead of having two separate tables with pre applied filters, a general SES identity table is added without the `IdentityType` filter, filtering can then be done via SQL in SteamPipe

## References

- API reference: https://docs.aws.amazon.com/ses/latest/APIReference/API_ListIdentities.html
- aws_ses_email_identity table with pre applied filter: https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_ses_email_identity.go#L90

**Comment by cbruno10** [comment]
Hi @janritter , thanks for opening the issue and including some proposals!

I'd be in favor of adding the `aws_ses_domain_identity` type for a few reasons:
- If we went with a combined `aws_ses_identity` table, then most likely the identity type would need to be passed in as a required key column, so the table knows which type to retrieve. We do use required key columns in some tables, but try to avoid them to simplify queries.
- We already have the `aws_ses_email_identity` table as you pointed out, so adding the `aws_ses_identity` table would create overlap between the two.
- Terraform has these as 2 separate resource types, [aws_ses_domain_identity](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_domain_identity) and [aws_ses_email_identity](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_email_identity). When designing tables, a place we usually start is with What Would Terraform Do?, and in this case, they had 2 separate tables (which we agreed with when had created the original `aws_ses_email_identity` table).

Hope that's helpful, but if you have any other questions, please let us know!
