### ISSUE TITLE
Add streams detail to table aws_dynamodb_table

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-aws#1205]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

GO SDK - https://docs.aws.amazon.com/sdk-for-go/api/service/dynamodb/#DynamoDB.ListExports 

![image](https://user-images.githubusercontent.com/26873346/184345325-333ca805-ee70-4eb4-b2d7-a223d5484459.png)

**Comment by ParthaI** [comment]
@rajlearner17, we need to add a separate table for `aws_dynamodb_table_export` because it has a separate list call and get call for it. We should not make nested API call within a hydrate call. So we decided to add a new table for it.
