### ISSUE TITLE
verification_token for aws_ses_email_identity is always null

### ISSUE THREAD

**Issue by janritter** [turbot/steampipe-plugin-aws#1207]
**Is your feature request related to a problem? Please describe.**

While working on #1203 I saw that aws_ses_email_identity contains a `verification_token` column which has `The verification token for a domain identity` as the description.
According to the AWS SDK docs the token is only set for domain identities, so it will always be null for email identities: https://github.com/aws/aws-sdk-go/blob/main/service/ses/api.go#L10817

**Describe the solution you'd like**

The description should be adapted, to add a hint that this is always null for email validations.

The best option would be to remove this columns since it's always null, but this would be a breaking change.

**Comment by cbruno10** [comment]
@janritter Nice catch, agree that this column should probably not be present in the `aws_ses_email_identity` table if it will always be `null` as per AWS. We'll most likely look to deprecate this column and then eventually remove it from the table in a future version.
