### ISSUE TITLE
List call for table aws_ecs_service returns error InvalidParameterException 

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-aws#1247]
**Describe the bug**
```
>  select * from silverwater_sso.aws_ecs_service
Error: InvalidParameterException: Long arn format must be used for tagging operations (SQLSTATE HV000)
```

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by khushboo9024** [comment]
Issue resolved.

**Comment by cbruno10** [comment]
@khushboo9024 Can you please add details on what the resolution was? Thanks!
