### ISSUE TITLE
Queries failures due to unsupported region `me-central-1`

### ISSUE THREAD

**Issue by itsofirblink** [turbot/steampipe-plugin-aws#1272]
**Describe the bug**
Queries fail if I have regions = ["*"] in my aws.spc since AWS now supports me-central-1, but the plugin does not.

**Steampipe version (`steampipe -v`)**
v0.15.4

**Plugin version (`steampipe plugin list`)**
v0.74.2

**To reproduce**
Run some kind of query to `select * from aws_ec2_instance` and have `*` as regions in `aws.spc`

**Expected behavior**
Instead of checking for invalid regions with hard coded list, check vs the `AvailableRegions` that returned from the api call, (maybe only if `*` provided)

**Comment by misraved** [comment]
Welcome to Steampipe @itsofirblink 👍  and thanks for reporting the bug.

We already have an open issue to add the support for `me-central-1` region - https://github.com/turbot/steampipe-plugin-aws/issues/1266

In fact, the fix is also ready - https://github.com/turbot/steampipe-plugin-aws/pull/1267 and we will be releasing a new version of the AWS plugin shortly.

**Comment by itsofirblink** [comment]
@misraved Thanks for the update :) Waiting for the merge 👍

**Comment by itsofirblink** [comment]
@misraved Hey! I see that the `Publish and Deploy` step of the release fails :( 
Here: https://github.com/turbot/steampipe-plugin-aws/runs/8091472583
Do you know when it will be released?

**Comment by cbruno10** [comment]
Hey @itsofirblink , we're re-running the release workflow now. It should be released in 10-15 minutes, will post back here once it's available.

**Comment by cbruno10** [comment]
@itsofirblink AWS plugin v0.75.0 is now released, which fixes the issue you originally mentioned. Please give the new version a try, but if you're still seeing errors feel free to re-open this issue, thanks!

**Comment by misraved** [comment]
@itsofirblink AWS plugin v0.75.0 is now available 👍 .

**Comment by itsofirblink** [comment]
@misraved @cbruno10 Thanks for the release! i have seen the code as-well, it looks like a good fix for future compatibilities with AWS!

I'm not sure but i think i feel some slowness in queries (overhead of 3~4 seconds) now, i'm not sure if its related to this release or to AWS, or maybe because we have more regions now to query against and it might take more time.

I think a nice optimization in the plugin will be to get the `region` out from the select query `select * from aws_ec2_instance where region='...'` 
If we will be able to fetch the `region` out it will speed up the query by a lot of time, and it will return only needed data, which means it will optimize memory load as-well 👍 

what do you think?

**Comment by cbruno10** [comment]
Hey @itsofirblink , in the plugin today, if you run a query like `select * from aws_ec2_instance where region = 'us-east-1';`, and your aws.spc contains `regions = ['*']`, the AWS plugin will only connect to and list instances from the `us-east-1` region.

Is this what you're referring to, or are you asking for a different improvement?

Also, are you seeing slowness with any particular queries? Or when you have certain configurations in your `aws.spc` config file?
