### ISSUE TITLE
Add table aws_msk_cluster

### ISSUE THREAD

**Issue by mikekantzer-drizly** [turbot/steampipe-plugin-aws#1278]
**References**
AWS's Managed Streaming for Apache Kafka
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

https://docs.aws.amazon.com/msk/latest/developerguide/getting-started.html
Terraform block: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster
https://docs.aws.amazon.com/sdk-for-go/api/service/kafka/

**Comment by cbruno10** [comment]
Hey @mikekantzer-drizly , thanks for raising this request!

The API docs look fairly straight forward and the table shouldn't be too difficult to test for that given resource type. If anyone is interested in trying to add these table, we always appreciate any PRs and are willing to help along the way!

**Comment by cbruno10** [comment]
Hey @mikekantzer-drizly , we currently have a PR open to add this table, https://github.com/turbot/steampipe-plugin-aws/pull/1291, and are in the process of reviewing it. It should be reviewed + merged before the end of this week.

**Comment by cbruno10** [comment]
@mikekantzer-drizly These tables are now available in v0.78.0 of the plugin, if you run into any issues, please let us know!
