### ISSUE TITLE
Support for Dynamic Aggregators

### ISSUE THREAD

**Issue by somoore** [turbot/steampipe-plugin-aws#1329]
Request:
- Plugin support for a dynamic aggregator file which lives in '~/.steampipe/config/aggregator.template' (or something similar)
- Allow the Steampipe User to (optionally) source their aggregators from a central file, instead of baked-into aws.spc.

For example in '~/.steampipe/config/aws.spc'
```
connection "template" {
 source = "../../aggregator.template"
 type = " aggregator_template "
 plugin = " aws "
} 
```
Reasoning:
- This would allow for the ability to generate aggregators via script in a dynamic method, as well as allow the Steampipe User to list/track all of their aggregators from one central file.

**Comment by johnsmyth** [comment]
@somoore  I think adding support for some sort of "dynamic aggregator' would need to be done at the steampipe or cli level, so it would operate across any plugins.  In your thinking, what would such a template look like?  What 'values' would be available to the template, and where would they come from?   Or is the `source` not a template file,  but rather an executable/script that returns the formatted values to stdout?
