### ISSUE TITLE
Add table aws_iam_service_specific_credential

### ISSUE THREAD

**Issue by alberto-colombo** [turbot/steampipe-plugin-aws#1340]
**References**
https://docs.aws.amazon.com/IAM/latest/APIReference/API_ListServiceSpecificCredentials.html

**Use Case**
as of now is not possible to list if IAM users have "HTTPS Git credentials for AWS CodeCommit" enabled
Should work similar to aws_iam_access_key

**Comment by misraved** [comment]
Thanks @alberto-colombo for raising the request 👍 .

If anyone would like to attempt to develop this table, the API mentioned by @alberto-colombo is an excellent place to start.

Please let us know in case there are questions 👍 .
