### ISSUE TITLE
aws_route53_record record incomplete in aws plugin v0.79.0

### ISSUE THREAD

**Issue by maxx225566** [turbot/steampipe-plugin-aws#1355]
**Describe the bug**
When I upgrade aws plugin to 0.79.0 the record becomes 100

**Steampipe version (`steampipe -v`)**
Example: v0.16.4

**Plugin version (`steampipe plugin list`)**
Example: v0.79.0

**To reproduce**
 different plugin versions on the same AWS connection

      ## aws plugin v0.78.0
      select count(name) from aws0780.aws_route53_record where zone_id = 'Z0939XXXXXXXXXXXXXXXXXX'
      => count = 26456 (correct)
      
      ## aws plugin v0.79.0
      select count(name) from aws0790.aws_route53_record where zone_id = 'Z0939XXXXXXXXXXXXXXXXXX'
      => count = 100 (Incorrect)

**Expected behavior**
Obviously not all records can be displayed in aws plugin v0.79.0 version

**Additional context**

**Comment by misraved** [comment]
@maxx225566 thanks for catching the bug.

We will look to get the fix out shortly.
