### ISSUE TITLE
EBS volume attachments for unattached volume is not null

### ISSUE THREAD

**Issue by eyalliss** [turbot/steampipe-plugin-aws#1366]
**Describe the bug**
I'm querying for unattached EBS volumes daily.
select volume_id, size, attachments from aws_all.aws_ebs_volume as v where state = 'available' and attachments is null

I've copied it from the examples in the [steampipe.io](http://steampipe.io/) site.
It used to work until last update
Now attachments is no longer null it is empty array instead, so I modified the script to be:
select volume_id, size, attachments from aws_all.aws_ebs_volume as v where state = 'available' and attachments = '[]'
The example still on site https://hub.steampipe.io/mods/turbot/aws_thrifty/queries/unattached_ebs_volumes

**Steampipe version (`steampipe -v`)**
steampipe version 0.16.4

**Plugin version (`steampipe plugin list`)**
+--------------------------------------------------+---------+----------------------------+
| Name                                             | Version | Connections                |
+--------------------------------------------------+---------+----------------------------+
| hub.steampipe.io/plugins/turbot/aws@latest       | 0.80.0  | aws_dev,aws_sanity,aws_all |
| hub.steampipe.io/plugins/turbot/steampipe@latest | 0.6.0   | steampipe                  |
+--------------------------------------------------+---------+----------------------------+

**To reproduce**
select volume_id, size, attachments from aws_all.aws_ebs_volume as v where state = 'available' and attachments is null

**Expected behavior**
It should list the unattached volumes and instead I'm getting an empty result

**Additional context**

**Comment by misraved** [comment]
Hello @eyalliss, while digging into this bug, we figured out that the SDK(AWS Go SDK V2) changed the API response from `null` to `[]` in the event of EBS volumes not having any attachments, hence the `attachments` column changed the response from `null` to `[]`.

It might become cumbersome to change the code each time an API response changes, keeping that in mind we decided to update all the instances of `aws_ebs_volume` queries where the `attachments` column is being queried.

Updates made across different mods:
https://github.com/turbot/steampipe-mod-aws-insights/pull/206
https://github.com/turbot/steampipe-mod-aws-thrifty/pull/102

Update made to the `aws_ebs_volume` table doc:
https://github.com/turbot/steampipe-plugin-aws/pull/1368

Once again, thank you for catching the bug, which had slipped from our radar 👍 .
