### ISSUE TITLE
Add table aws_ssm_inventory_entry

### ISSUE THREAD

**Issue by nhalstead** [turbot/steampipe-plugin-aws#1370]
**References**

[AWS ListInventoryEntries](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_ListInventoryEntries.html#API_ListInventoryEntries_Examples)

Related Go Library Method: [`func (*SSM) ListInventoryEntries`](https://docs.aws.amazon.com/sdk-for-go/api/service/ssm/#SSM.ListInventoryEntries)

To fetch data from this API both `InstanceId` and `TypeName` are needed.

Note: The table [`aws_ssm_inventory`](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetInventory.html) exists but is not the same as `...inventory_entries`

**Comment by nhalstead** [comment]
_bump_

**Comment by rajlearner17** [comment]
@ParthaI, We can check if this can be a new table or extended in `aws_ssm_inventory` as a new column.
