### ISSUE TITLE
Error when querying aws_dynamodb_table

### ISSUE THREAD

**Issue by janritter** [turbot/steampipe-plugin-aws#1380]
**Describe the bug**
Error `Error: failed to populate column 'billing_mode': rpc error: code = Internal desc = transform getTableBillingMode failed with panic interface conversion: interface {} is types.BillingMode, not *string (SQLSTATE HV000)` when executing `SELECT * FROM aws_dynamodb_table`

**Steampipe version (`steampipe -v`)**
0.16.4

**Plugin version (`steampipe plugin list`)**
0.81.0

**To reproduce**
Execute the following query:
```sql
SELECT * FROM aws_dynamodb_table;
```

**Expected behavior**
Return all DynamoDB tables with their attributes

**Comment by janritter** [comment]
This bug was introduced with 0.81.0, 0.80.0 is working

**Comment by rajlearner17** [comment]
@janritter Thanks for using Steampipe, and I appreciate raising this bug.

We acknowledge that we started looking into this and will provide an update soon.
