### ISSUE TITLE
aws_route53_record results incomplete aws@0.81.1

### ISSUE THREAD

**Issue by tinder-tder** [turbot/steampipe-plugin-aws#1385]
**Describe the bug**
Results from queries to aws_route53_record table still are incomplete when comparing to results from previous versions <= aws@0.78.0 and spot checking against the aws console/cli

**Steampipe version (`steampipe -v`)**
 v0.17.0

**Plugin version (`steampipe plugin list`)**
 v0.81.1

**To reproduce**
```
> select
      count(name)
      
    from
      prod.aws_route53_record as aws_cloudhubr
    where
      aws_cloudhubr.zone_id = 'ZZZ'
+-------+
| count |
+-------+
| 224   |
+-------+
> select
      count(name)
      
    from
      prod_old.aws_route53_record as aws_cloudhubr
    where
      aws_cloudhubr.zone_id = 'ZZZ'
+-------+
| count |
+-------+
| 225   |
+-------+
> .connections
+---------------------+---------------------------------------------------+
| connection          | plugin                                            |
+---------------------+---------------------------------------------------+
| prod                | hub.steampipe.io/plugins/turbot/aws@latest        |
| prod_old            | hub.steampipe.io/plugins/turbot/aws@0.78.0        |
+---------------------+---------------------------------------------------+
```

the zone id is public and the missing record is of CNAME type (if its relevant).
AWS console and cli show 225 records in the zone id

**Expected behavior**
results should be teh same as previous working versions

**Additional context**
https://github.com/turbot/steampipe-plugin-aws/issues/1374
https://github.com/turbot/steampipe-plugin-aws/pull/1375/files

**Comment by cbruno10** [comment]
Hey @tinder-tder , sorry you're still experiencing issues, looks like our switch to AWS SDK v2 was a bit messy.

I had a few questions that I think may help us debug more:
- If you run the query multiple times with caching disabled, is there 1 consistent record that doesn't get returned?
- For the record that's missing in the example, do you know where that is alphabetically in relation to the other records, e.g., the first record in the zone, the last record, somewhere in between?
- Are there multiple types/entries, e.g., CNAME, NS, A, for that record types?
- If you try with other zones, are you seeing only 1 record missing, or does it vary between zones? And similar to the questions above, are the missing zones consistently toward the beginning, middle, or end of the records alphabetically (or are there no patterns)?

Thanks!

**Comment by tinder-tder** [comment]
>     * If you run the query multiple times with caching disabled, is there 1 consistent record that doesn't get returned?
Yes, with or without caching the same record for that zone is missing
> 
>     * For the record that's missing in the example, do you know where that is alphabetically in relation to the other records, e.g., the first record in the zone, the last record, somewhere in between?
> 
in between, first record lexographically starts with '_', last starts with 'z'. the missing record starts with 's' and there are other records with 's' that are being returned
```
> select
      name
      
    from
      prod.aws_route53_record as aws_cloudhubr
    where
      aws_cloudhubr.zone_id = 'ZZZ' and name like 'sYYYY.%'
+------+
| name |
+------+
+------+
> select
      name
      
    from
      prod_old.aws_route53_record as aws_cloudhubr
    where
      aws_cloudhubr.zone_id = 'ZZZZ' and name like 'sYYYY.%'
+-----------------------+
| name                  |
+-----------------------+
| sYYYY.XXX. |
+-----------------------+
```
>     * Are there multiple types/entries, e.g., CNAME, NS, A, for that record types?
No only a single CNAME for that record name

> 
>     * If you try with other zones, are you seeing only 1 record missing, or does it vary between zones? And similar to the questions above, are the missing zones consistently toward the beginning, middle, or end of the records alphabetically (or are there no patterns)?

All other zones in the same account seem to be matching up (doing the diff only show the one record in that one zone).
```
> select
      * into r53_old from
( select *
    from
      prod_old.aws_route53_record as aws_prodr
    where
      aws_prodr.zone_id in (select id from prod_old.aws_route53_zone) ) as everything
> select
      * into r53_new from
( select *
    from
      prod.aws_route53_record as aws_prodr
    where
      aws_prodr.zone_id in (select id from prod.aws_route53_zone) ) as everything
> select count(*) from public.r53_old
+-------+
| count |
+-------+
| 2990  |
+-------+
> select count(*) from public.r53_new
+-------+
| count |
+-------+
| 2989  |
+-------+
> select count(distinct(zone_id)) from public.r53_new
+-------+
| count |
+-------+
| 76    |
+-------+
> select count(distinct(zone_id)) from public.r53_old
+-------+
| count |
+-------+
| 76    |
+-------+
> select name from public.r53_new where name not in (select name from public.r53_old)
+------+
| name |
+------+
+------+
> select name from public.r53_old where name not in (select name from public.r53_new)
+-----------------------+
| name                  |
+-----------------------+
| sYYYY.XXX. |
+-----------------------+
> 
```

The thing that may be uniq for that zone is that it has the most records for a public zone.  we have a private zone with over 550 records that is coming back clean.

**Comment by tinder-tder** [comment]
@cbruno10 : i jsut tested some queries i should of done before.
Doing an exact name match using `=` or `in` works but if you do a like it doesnt find the record on the newer plugin.
 
```
> select name from prod.aws_route53_record where name like '%sXXXXX%' and zone_id = 'AAAAAAAAA';
+---------------------------------------------------------+
| name                                                    |
+---------------------------------------------------------+
| _ZZZZZZZZZ.sXXXXX.YYYYY. |
+---------------------------------------------------------+
> select name from prod.aws_route53_record where name ='sXXXXX.YYYYY.' and zone_id = 'AAAAAAAAA';
+-----------------------+
| name                  |
+-----------------------+
| sXXXXX.YYYYY. |
+-----------------------+
> select name from prod.aws_route53_record where name in ('sXXXXX.YYYYY.') and zone_id = 'AAAAAAAAA';
+-----------------------+
| name                  |
+-----------------------+
| sXXXXX.YYYYY. |
+-----------------------+
> select name from prod.aws_route53_record where name like 'sXXXXX.%' and zone_id = 'AAAAAAAAA';
+------+
| name |
+------+
+------+
>
```

With 0.78.0 version it works with like and finds the correct records.
```
> select name from prod_old.aws_route53_record where name like '%sXXXXX%' and zone_id = 'AAAAAAAAA';
+---------------------------------------------------------+
| name                                                    |
+---------------------------------------------------------+
| sXXXXX.YYYYY..                                   |
| _ZZZZZZZZZ.sXXXXX.YYYYY. |
+---------------------------------------------------------+
>
```

**Comment by cbruno10** [comment]
Thanks for the additional information @tinder-tder , I'm still puzzled why only 1 record from 1 zone isn't being returned, as paging generally seems to be working for you, except for this 1 specific record.

The `like` query results you mentioned makes sense, since using `like` means we don't pass the quals to the API input parameters, so we try to get all records from the specified zone (which is still missing that 1 record).

I haven't been able to reproduce in any of my public hosted zones with CNAME records unfortunately, even when I locally compile the plugin with a page size of 1 to guarantee that I'm iterating through pages.

If you're able to locally compile the plugin, one suggestion I have is to make use of `plugin.Logger(ctx).Warn(...)` logging statements, which would create messages in log files like `~/.steampipe/logs/plugin-2022-11-28.log`.

So for instance, before this line https://github.com/turbot/steampipe-plugin-aws/blob/7368e02eeb58fe9b520a76d2575bcb9876ac23e3/aws/table_aws_route53_record.go#L197, you could try inserting:
```
plugin.Logger(ctx).Warn("aws_route53_record.listRoute53Records", "record", record)
```

Which would then allow you to see if the record is being streamed, but maybe not being returned in the final results for some reason. You could also output values of `op.IsTruncated`, `op.NextRecordName`, `op.NextRecordType`, `op.NextRecordIdentifier` each loop as well and follow the paging code to see if the next markers are being handled correctly.

**Comment by tinder-tder** [comment]
Well this is weird, nothing has changed but the record shows up properly on all the versions it did not show up for before.  i will close this.
