### ISSUE TITLE
Add new column to get details for connected compute resources (rds_instance & cluster)

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-aws#1400]
**Is your feature request related to a problem? Please describe.**

[AWS RDS New feature > Amazon RDS now supports setting up connectivity between your RDS database and EC2 compute instance in 1-click](https://aws.amazon.com/about-aws/whats-new/2022/08/amazon-rds-setting-up-connectivity-rds-database-ec2-compute-instance-1-click/)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/26873346/202640177-f7109057-daec-4307-ad13-3a7183553511.png)

**Comment by ParthaI** [comment]
Any API/CLI commands For RDS service do not return any info about `connected compute resources` in the cluster. We have created a feature request for it in the [AWS Go SDK V2](https://github.com/aws/aws-sdk-go-v2/issues/1929) repo for tracking purposes.
