### ISSUE TITLE
When selecting the aws_ec2_instance table, if the user_data column is not entered, only the ap-northeast-1 region data is loaded.

### ISSUE THREAD

**Issue by FRABUCHI** [turbot/steampipe-plugin-aws#1402]
**Describe the bug**
When selecting the aws_ec2_instance table, if the user_data column is not specified, only the data of ap-northeast-1 is loaded.

**Steampipe version (`steampipe -v`)**
 v0.15.4

**To reproduce**
`
-- when user_data column is specified, show multiple region
SELECT region , ... ,user_data FROM aws_ec2_instance

-- when user_data column is not specified, show only ap-northeast-1
SELECT region , ... , instance_id FROM aws_ec2_instance
`

**Expected behavior**
I want to import data for all regions even if the user_data column is not included.

**Comment by misraved** [comment]
Hello @FRABUCHI, thanks for using Steampipe. I hope your issue got resolved 👍 . I am closing this issue, for now, please let us know if you run into issues 👍.
