### ISSUE TITLE
aws_s3_access_point only returns resources from us-east-1 and ignores other regions

### ISSUE THREAD

**Issue by ParthaI** [turbot/steampipe-plugin-aws#1406]
**Describe the bug**
We can create the s3 access point with different types of **network origins** 1. `Virtual private cloud (VPC)` 2.` Internet`

The table `aws_s3_access_point` only returns the access points that are network origins `Virtual private cloud (VPC)`. I the not returning the access points that are network origins `Internet`.

**Steampipe version (`steampipe -v`)**
Example: v0.17.2

**Plugin version (`steampipe plugin list`)**
Example: V0.70.0

**To reproduce**
Create two AWS S3 access points with **network origins** 1. `Virtual private cloud (VPC)` 2.` Internet` and run the query `select *  from aws_s3_access_point` 

**Expected behavior**
`select * from aws_s3_access_point` should return all the available s3 access points in an account

**Additional context**

**Comment by ParthaI** [comment]
We can create the s3 access point with different types of **network origins** 1. `Virtual private cloud (VPC)` 2.` Internet`

While making the **[NewListAccessPointsPaginator](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3control@v1.21.9#NewListAccessPointsPaginator)** API call it returns the access points which are the only `Virtual private cloud (VPC)` type network origin, it doesn't list out the access points which are the only `Internet` type network origin. Also, I looked into the input [parameter](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3control@v1.21.9#ListAccessPointsInput), which doesn't accept any property which will list out both types of network origin access points.

I am using the [ListAccessPointsAPIClient](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3control@v1.21.9#ListAccessPointsAPIClient), service client, to make the API call.

However, the AWS CLI call (` aws s3control list-access-points --account-id <Account Id> --profile <AWS profile> --region <Region>`) returns the correct set of the result set.

We have raised a support request with AWS SDK V2 repo by describing the bug, Commenting here for tracking purposes https://github.com/aws/aws-sdk-go-v2/issues/1932.

**Comment by ParthaI** [comment]
It seems there is no bug from the API side. We need to update the service client for table aws_s3_access_point.
Currently, the service client function is taking only the default region(`cfg, err := getClient(ctx, d, getDefaultAwsRegion(d))`) while creating a client for making API calls.
we need to pass the regions as per the spc file configuration.

**Comment by rajlearner17** [comment]
@ParthaI, can you start looking into it?
