### ISSUE TITLE
Add unsupported regions check for aws_rds_* tables

### ISSUE THREAD

**Issue by ParthaI** [turbot/steampipe-plugin-aws#1431]
**Describe the bug**
Add unsupported regions check for aws_rds_* tables.

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by misraved** [comment]
We are closing this issue in favor of the robust `v0.93.0` plugin release which fixes several unsupported regions.
