### ISSUE TITLE
Add document permission details to aws_ssm_document table

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-aws#145]
**Is your feature request related to a problem? Please describe.**
I want to be able to view document permissions for all documents I can view.

**Describe the solution you'd like**
We should add additional columns with this information to the aws_ssm_document table.

**Describe alternatives you've considered**
None

**Additional context**
Go SDK link to method - https://docs.aws.amazon.com/sdk-for-go/api/service/ssm/#SSM.DescribeDocumentPermission

**Comment by anisadas** [comment]
PR: https://github.com/turbot/steampipe-plugin-aws/pull/110
