### ISSUE TITLE
Steampipe query not working for ec2 related tables(ex: aws_ec2_instance)

### ISSUE THREAD

**Issue by sarita-ningappa** [turbot/steampipe-plugin-aws#1475]
Steampipe query is not working for aws_ec2_instance and other ec2 related tables with the following error

**Error: operation error EC2: DescribeInstances, https response error StatusCode: 403, RequestID: -------------------, api error UnauthorizedOperation: You are not authorized to perform this operation. (SQLSTATE HV000)**

key has administrator access and using the same on aws cli for ec2 servie is working fine. 
please help on the same.

**Comment by sarita-ningappa** [comment]
Hi ,
getting error as follows:
select * from aws_iam_account limit 10;
Error: relation "aws_01.aws_iam_account" does not exist (SQLSTATE 42P01)
> select * from aws_01.aws_s3_buckets limit 10;
Error: relation "aws_01.aws_s3_buckets" does not exist (SQLSTATE 42P01)

aws.spc file contents for reference:
connection "aws_all" {
   type        = "aggregator"
   plugin      = "aws"
   connections = ["aws_*"]
 }

connection "aws_01" {
  plugin = "aws"
  profile = "dev-account"
  regions = ["*"]
}

pointing to aws profile dev-account credentials

**Comment by misraved** [comment]
Relevant slack thread - https://steampipe.slack.com/archives/C01UECB59A7/p1669976937731209

**Comment by cbruno10** [comment]
Hi @sarita-ningappa , your table names appear to be incorrect, as we don't have an `aws_iam_account` or `aws_s3_buckets` table. A full list of tables can be found at https://hub.steampipe.io/plugins/turbot/aws/tables, or with the `.inspect` command while in `steampipe query`.

Can you please try running `select * from aws_account limit 10;` and `select * from aws_s3_bucket limit 10;` and post the query results here?
