### ISSUE TITLE
Add table aws_codecatalyst_project

### ISSUE THREAD

**Issue by misraved** [turbot/steampipe-plugin-aws#1479]
**References**
[Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.](https://github.com/aws/aws-sdk-go-v2/tree/main/service/codecatalyst)

**Comment by ParthaI** [comment]
While making API call for listing out the resource from console we are getting the `Nil pointer dereference` error from the API itself. Need to dig into the issue more a bit.
