### ISSUE TITLE
Support the new sso-session format for ~/.aws/config

### ISSUE THREAD

**Issue by marekjalovec** [turbot/steampipe-plugin-aws#1533]
**Is your feature request related to a problem? Please describe.**
AWS rolled out an updated format of the config file for SSO that's taking care of credential rotation: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html#sso-configure-profile-token

This new format moves some SSO-related fields to a separate block [sso-session xxx].

**Describe the solution you'd like**
Support the updated AWS SDK calls that can handle this format

```
[profile test]
sso_session = sso
sso_account_id = REDACTED
sso_role_name = REDACTED
region = eu-central-1
output = json

[sso-session sso]
sso_start_url = https://REDACTED.awsapps.com/start
sso_region = eu-central-1
sso_registration_scopes = sso:account:access
```

**Describe alternatives you've considered**
The old format still works, it's just a bit more hassle.

```
[profile finn_eng]
sso_start_url = https://REDACTED.awsapps.com/start
sso_region = eu-central-1
sso_account_id = REDACTED
sso_role_name = REDACTED
region = eu-central-1
output = json
```

**Additional context**
It seems like the correct version of SDK is used already and the custom plugin code just isn't using it right.

**Comment by misraved** [comment]
Thanks @marekjalovec for opening this issue 👍. 

I was just looking into the code, and from an initial look, I could come up with the following question
```
 What happens when you use the new SSO format to login into your AWS account and then try to query the account using Steampipe? Does it give an error?
```

**Comment by cbruno10** [comment]
@marekjalovec We haven't heard back from you, but if you're running into issues, feel free to re-open this issue with any details/error logs you're encountering. Thanks!

**Comment by isavcic** [comment]
@misraved let me answer how it looks in my case: I get an empty result set.

```
sso_session = foobar
sso_account_id = 1234567890
sso_role_name = AWSAdministratorAccess

[profile foobar-account]
region = us-east-1
sso_session = foobar
sso_account_id = 1234567890
sso_role_name = AWSAdministratorAccess
```

```
❯ steampipe query
Welcome to Steampipe v0.21.7
For more information, type .help
> select name from foobar_account.aws_lambda_function
+------+
| name |
+------+
+------+
```
