### ISSUE TITLE
AWS_lambda_function - Display the code in a lambda function.

### ISSUE THREAD

**Issue by valtranhealth** [turbot/steampipe-plugin-aws#1542]
We are trying to write a query to check lambda functions in AWS for any hardcoded/cleartext passwords. However we are having trouble accessing the code in the lambda functions via steampipe queries. The code attribute in the aws_lambda_function table provides: "The deployment package of the function or version.", but is doesn't display what we are seeking.

Currently the code column relies on GetFunction  API call, which returns the following parameters -
```
   "Code": { 
      "ImageUri": "string",
      "Location": "string",
      "RepositoryType": "string",
      "ResolvedImageUri": "string"
   },

```

We would like to be able to display/query the actual code. Ved Misra from the Steampipe Slack channel has kindly suggested we raise a request so  in order to search for other APIs that return the code data.

Thank you.

**Comment by rajlearner17** [comment]
Slack thread reference [here](https://steampipe.slack.com/archives/C01UECB59A7/p1673822945819969)

**Comment by ParthaI** [comment]
Currently there is no such [API](https://docs.aws.amazon.com/lambda/latest/dg/API_Operations.html) supported for Lambda Function that return the code data. We have started a discussion for it on SDK side, link: https://github.com/aws/aws-sdk-go-v2/discussions/1990

**Comment by ParthaI** [comment]
```
"Code": { 
      "ImageUri": "string",
      "Location": "string",
      "RepositoryType": "string",
      "ResolvedImageUri": "string"
   },
```

`Location` here will be an ARN to your bucket hosting the lambda code. You can make a request to that s3 bucket only if you are the one that provisioned it.
If you used lambda to provision the s3 bucket for you, you will get a 403 and wont be able to access it.
