### ISSUE TITLE
Test plan for plugin after major credentials, regions, caching and SDK v5 updates

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe-plugin-aws#1560]
We've updated a lot of key features in the core sections of the AWS plugin, so need to be sure it's working well before release. This issue will outline a set of tests that should be completed.

Credentials:
- [ ] SSO credentials - 1 account
- [ ] SSO credentials - 3 accounts with aggregator
- [ ] EC2 IAM role - 1 account
- [ ] EC2 IAM role - 3 accounts with aggregator
- [ ] Access & Secret key pair in config - 1 account
- [ ] Access & Secret key & Session token in config - 1 account
- [ ] Other methods?
- [ ] china account
- [ ] localstack

Regions:
- [ ] regions not set - should give results for default region only
- [ ] regions = [ "eu-west-2" ] - should give results for eu-west-2 only
- [ ] regions = [ "*" ] - should give results for all regions in partition
- [ ] regions = [] - should give results for ???
- [ ] regions = [], AWS_REGION=ap-south-1 - should give results for ap-south-1 only
- [ ] regions = [], AWS_REGION=eu-west-1 - should give results for eu-west-1 only
- [ ] regions = [ "us-*" ], AWS_REGION=eu-west-1 - should give results for eu-west-1 only
- [ ] govcloud account, regions = [ "*" ] - should give results for all regions in partition
- [ ] govcloud account, regions = [ "us-*" ]

Service regions:
- [ ] govcloud - `select * from aws_vpc` should give results for all regions
- [ ] govcloud - `select * from <service_not_in_partition>` should give zero results (no error)

Mods (run multi-account, multi-region, compare with results from old plugin):
- [ ] thrifty mod
- [ ] compliance mod
- [ ] tagging mod
- [ ] insights dashboards

**Comment by jchrisfarris** [comment]
I would add...

- ap-southeast-4 (Melbourne - the newest region that requires opt-in)
- ap-southeast-4 enabled in one account in the aggregate, but opted out in another account
- Disable the STS interface for some regions in an account. STS Endpoints are enabled via the [Account Page](https://us-east-1.console.aws.amazon.com/billing/home?region=us-east-1&skipRegion=true#/account). Enable some, disable some. See what chaos ensues. 
- When you enable the opt-in regions there is a setting that has to occur to expand STS tokens. This impact the ability of Account A in us-east-1 to assume role into Account B in ap-southeast-4.

**Comment by e-gineer** [comment]
I've added support for ap-southeast-4 to the branch.

The `default_region` will be the main decision around STS tokens. The STS token is obtained using the `default_region` and then used in all query `regions`. I assume this will require the STS endpoint to be enabled for your default_region and the setting to expand tokens may also be important.

**Comment by cbruno10** [comment]
Testing completed for https://github.com/turbot/steampipe-plugin-aws/commit/50f05e9458fc4d19c5de707d357e325af53063b1
