### ISSUE TITLE
Can't query AWS region for data if STS is disabled in that region

### ISSUE THREAD

**Issue by captainfalcon23** [turbot/steampipe-plugin-aws#1569]
**Describe the bug**
I have AWS accounts where we generally only use 1-2 regions. Only those regions have an STS endpoint enabled in IAM Console -> Account settings. I have some steampipe queries that I want to run in ALL regions, so I can catch if any EC2 instances for example are created in other regions.

The problem is, if I specify the region in aws.spc, I will get a RegionDisabledException because the STS endpoint is not enabled there, but instead, Steampipe should try the global endpoint instead. 

I don't really know if this is a bug or a feature....

**Steampipe version (`steampipe -v`)**
steampipe version  0.18.3

**Plugin version (`steampipe plugin list`)**
 0.92.1

**To reproduce**
Create a connection in aws.spc:
```
connection "aws1" {
  plugin  = "aws"
  ignore_error_codes = ["RegionDisabledException"]
  profile = "internal"
  regions = ["ap-south-1", "ca-central-1", "eu-central-1", "us-west-1", "us-west-2", "eu-north-1", "eu-west-3", "eu-west-2", "eu-west-1", "ap-northeast-3", "ap-northeast-2", "ap-northeast-1", "sa-east-1", "ap-southeast-1", "ap-southeast-2", "us-east-1", "us-east-2"]
}
```

Ensure at least 1 region does NOT have STS enabled in the AWS Account

Try and run any query against this region. 

**Expected behavior**
Steampipe tries the global endpoint instead.

**Comment by e-gineer** [comment]
Hey @captainfalcon23 ... We're currently testing a large set of changes to the AWS plugin that we hope to release soon in https://github.com/turbot/steampipe-plugin-aws/tree/creds-region-cache-refactor

Included in those changes is a `default_region` config setting. The `default_region` will be used for any global API calls, including getting credentials via STS.

I think that will address your question?

We'd appreciate any testing you might be able to do with that branch. Feedback welcome!

**Comment by captainfalcon23** [comment]
Thanks @e-gineer  I will give it a shot and see!

**Comment by misraved** [comment]
@captainfalcon23 we have released `v0.93.0` of the AWS plugin which includes a lot of optimizations around the base regions used for making the API calls. 

You can find more information about this release in https://steampipe.slack.com/archives/C01UECB59A7/p1676906592530609 and https://steampipe.slack.com/archives/C01UECB59A7/p1676906592530609

Please try it and let us know if it fixes your issue 👍. Any feedback on the changes made by us would be very helpful 😄

**Comment by captainfalcon23** [comment]
Thanks @misraved ... i got a bit busy and couldn't get the branch, but I will test this and let you know ASAP!

**Comment by captainfalcon23** [comment]
Hi @misraved / @e-gineer 

I tested today by adding the below to my aws.spc
```
  regions = ["*"]
  default_region = "ap-southeast-2"
```
And it looks good! No more errors, and resources retrieved from all regions! Thankyou so much, you can close off this issue :)

**Comment by e-gineer** [comment]
Awesome! Thanks for the confirmation 🚀
