### ISSUE TITLE
Querying the `aws_health_affected_entity` table will result in error

### ISSUE THREAD

**Issue by TrongBYM** [turbot/steampipe-plugin-aws#1580]
**Describe the bug**
A simple query against the `aws_health_affected_entity` table will result in error.

**Steampipe version (`steampipe -v`)**
Example: v0.18.5

**Plugin version (`steampipe plugin list`)**
```
hub.steampipe.io/plugins/turbot/aws@latest - v0.92.1
hub.steampipe.io/plugins/turbot/steampipe@latest - v0.6.0
```

**To reproduce**
Running the following query:
```
SELECT arn FROM aws_health_affected_entity;
```

will result in the following error
```
Error: operation error Health: DescribeAffectedEntities, 1 validation error(s) found.
- missing required field, DescribeAffectedEntitiesInput.Filter.EventArns.
 (SQLSTATE HV000)
```

and the following, empty table:
```
+-----+
| arn |
+-----+
+-----+
```

**Expected behavior**
A table containing the ARNs of affected entities found by AWS Health.

**Additional context**
The problem might stem from #1525, however I am not well-read when it comes to the codebase!

**Comment by cbruno10** [comment]
Hey @TrongBYM , sorry for the silence on this issue, we've picked it back up today and will post any updates here once we have them.

**Comment by karanpopat** [comment]
@TrongBYM can you please test this pull request whether it fixes your issue - https://github.com/turbot/steampipe-plugin-aws/pull/1659
