### ISSUE TITLE
Add table aws_api_gateway_domain_name

### ISSUE THREAD

**Issue by Wingless-Archangel** [turbot/steampipe-plugin-aws#1581]
When I tried to query for a custom domain name for the rest API gateway, and got the following error.

```SQL
> select * from aws_api_gateway_domain_name
Error: relation "aws_api_gateway_domain_name" does not exist (SQLSTATE 42P01)
```

According to the terraform AWS provider, they call different paths in `aws-sdk-go` as follows.
- aws_apigateway_domain_name [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/apigateway/domain_name.go#L11)
- aws_api_gatewayv2_domain_name [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/apigatewayv2/domain_name.go#L11)

I don't know if it's called the same API endpoint for both API gateways.
Could you please have a look?

**References**
- [Terraform resources](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_domain_name)
- [AWS documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html)

**Comment by misraved** [comment]
Welcome to Steampipe @Wingless-Archangel and thanks for raising this issue 👍.

Are you able to query for custom domain names by using the following query - 
`select * from aws_api_gatewayv2_domain_name`?

We currently don't have support for `aws_api_gateway_domain_name`, but by looking at the terraform documentation and the AWS API documentation that you have mentioned in the issue body, we could definitely add it 👍.

Once again, thanks for adding so many details to the issue, definitely made things extremely easy for me while I was trying to hunt down the relevant documents/references 👍 .
