### ISSUE TITLE
Selecting `tags` or `tags_src` from `aws_kms_key` table results in an access denied error when including some AWS KMS keys

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-aws#1594]
**Describe the bug**
When selecting the `tags` or `tags_src` column from the `aws_kms_key` table, it will fail if the query attempts to fetch rows for some AWS KMS keys, e.g.,
```
Error: table 'aws_kms_key' column 'tags_src' requires hydrate data from getAwsKmsKeyTagging, which failed with error operation error KMS: ListResourceTags, https response error StatusCode: 400, RequestID: b443b9b8-c425-4bbe-8436-4674a6a64658, api error AccessDeniedException: User: arn:aws:iam::0123456789012:user/test is not authorized to perform: kms:ListResourceTags on resource: arn:aws:kms:us-east-1:0123456789012:key/7b4b4b42-5df5-465c-3fd1-64ea534561bc because no resource-based policy allows the kms:ListResourceTags action.
```

This doesn't error out for all AWS KMS keys, but seems to be primarily happening with the `aws/acm` key. I tested 10-15 other keys in us-east-1 from other services, so my testing wasn't exhaustive.

**Steampipe version (`steampipe -v`)**
v0.18.4

**Plugin version (`steampipe plugin list`)**
v0.93.0

**To reproduce**
Run `select tags from aws_kms_key`

**Expected behavior**
Tags should be returned for keys that the caller has access to. Any AWS keys that the caller can't list tags for should be ignored. Any customer keys that the caller can't list tags for should be ignored or the errors should be reported properly.

**Additional context**

**Comment by cbruno10** [comment]
This worked in an older AWS plugin version when we were using AWS SDK v1 - https://github.com/turbot/steampipe-plugin-aws/blob/cdc72880cfea5ff98ca55c46efc0c044522b6e46/aws/table_aws_kms_key.go#L324-L329, so even if it wasn't the perfect way to handle it, the migration for this table had this regression.

**Comment by cbruno10** [comment]
I think ignoring all `AccessDeniedException` errors for this hydrate functions may not be the right solution, since only the `aws/acm` key so far is having this error and it would affect customer keys too, so just checking if key is `aws/acm` and we get that error is nice, but may require some more hydration data (since the initial key data we get only has the key ID and the key ARN, neither of which help us see if it's the `aws/acm` key).

**Comment by andy-werderman** [comment]
I also frequently run into this error.

**Comment by cbruno10** [comment]
Overall, we should consider how to handle access denied errors for any hydrate call (list, get, specific gets) for resources whose resource policies can block access.

We can ignore them in the code, or users can add them into the `ignore_error_codes` config arg. 

If we ignore them in the code, we don't have a good way to let users know in the query results if we're ignoring errors or if that value from the API is truly `null`, though having the query return the fields the user can see is probably more important.

If we expect users to add `AccessDeniedException` to `ignore_error_codes`, then unfortunately that would mean all `AccessDeniedException` errors would be ignored.

**Comment by pdecat** [comment]
> If we ignore them in the code, we don't have a good way to let users know in the query results if we're ignoring errors or if that value from the API is truly `null`, though having the query return the fields the user can see is probably more important.

How about raising `WARNING` messages like [can be done in PL/pgSQL](https://www.postgresql.org/docs/current/plpgsql-errors-and-messages.html)?
Is this something that could be done in the plugin code instead of raising errors that abort execution?

In the meantime, I'm using the following work-around:

```
WITH k AS (
  SELECT
    id,
    region,
    (aliases[0] ->> 'AliasName') AS "alias"
  FROM aws_kms_key
)

SELECT
  k.id AS "id",
  k.region AS "region",
  k.alias AS "alias",
  CASE WHEN k.alias = 'alias/aws/acm' THEN '[]'::jsonb ELSE (SELECT k2.tags FROM aws_kms_key AS k2 WHERE k2.id = k.id) END AS tags
FROM k
```

Note: the CTE is needed otherwise the `tags` column is eagerly fetched and triggers the error:
```
> SELECT id, region, (aliases[0] ->> 'AliasName') AS alias, CASE WHEN (aliases[0] ->> 'AliasName') = 'alias/aws/acm' THEN '[]'::jsonb ELSE tags END AS tags FROM aws_kms_key

Error: aws: operation error KMS: ListResourceTags, https response error StatusCode: 400, RequestID: ******, api error AccessDeniedException: User: arn:aws:sts::******:assumed-role/****** is not authorized to perform: kms:ListResourceTags on resource: arn:aws:kms:eu-west-3:******:key/****** because no resource-based policy allows the kms:ListResourceTags action (SQLSTATE HV000)

+----+--------+-------+------+
| id | region | alias | tags |
+----+--------+-------+------+
+----+--------+-------+------+

```

**Comment by pdecat** [comment]
Also worth noting this does not only occurs for the `aws/acm`  key, but for any key which does not the proper [resource based IAM policy](), e.g.:

```
rpc error: code = Unknown desc = aws_************: table 'aws_kms_key' column 'tags' requires hydrate data from getAwsKmsKeyTagging, which failed with error operation error KMS: ListResourceTags, https response error StatusCode: 400, RequestID: ************, api error AccessDeniedException: User: arn:aws:sts::************:assumed-role/my-iam-role is not authorized to perform: kms:ListResourceTags on resource: arn:aws:kms:eu-west-3:************:key/mrk-5d0e3b73350540d884ed9fbcb26c1ce0 because no resource-based policy allows the kms:ListResourceTags action.
```

![Image](https://github.com/user-attachments/assets/773c8646-e0ad-4967-868d-b0e52aaef2a2)

**Comment by pdecat** [comment]
My new work-around is now using a plpgSQL function to handle the permission denied errors and report the issues as WARNING to the postgresql client (psycopg in my case):
```
CREATE FUNCTION public.lenient_select_jsonb(select_jsonb text, keys text [] DEFAULT null, level text DEFAULT 'WARNING')
RETURNS jsonb
LANGUAGE plpgsql
IMMUTABLE PARALLEL SAFE
AS $BODY$
DECLARE r jsonb;
DECLARE d text;
DECLARE m text;
BEGIN
  EXECUTE format(select_jsonb, VARIADIC keys) INTO r;
  RETURN r;
EXCEPTION WHEN fdw_error THEN
  GET STACKED DIAGNOSTICS d = MESSAGE_TEXT;
  m := format('lenient_select_jsonb failed to execute query: %s', d);
  CASE level WHEN 'WARNING' THEN
    RAISE WARNING '%', m;
  WHEN 'NOTICE' THEN
    RAISE NOTICE '%', m;
  ELSE
    RAISE DEBUG '%', m;
  END CASE;
  RETURN NULL;
END $BODY$;
```

Used as:
```
WITH ka AS (
  SELECT
    substring(aliases[0] ->> 'AliasName' FROM 7) AS "alias", -- aliases start with 'alias/'
    id,
    region
  FROM aws_kms_key
)

SELECT
  coalesce(ka.alias, k.id) AS "name",
  k.arn,
  k.region,
  -- required to avoid errors with keys not providing the kms:ListResourceTags resource based permission,
  -- such as aws/acm
  (SELECT lenient_select_jsonb(
    $$
    SELECT tags
    FROM aws_kms_key
    WHERE id = '%s' AND region = '%s'
    $$,
    ARRAY[k.id, k.region],
    'NOTICE'
  )) AS "tags",
  k.creation_date,
  k.deletion_date,
  k.description,
  k.key_state,
  k.multi_region,
  k.multi_region_configuration
FROM
  aws_kms_key AS k
LEFT OUTER JOIN ka
  ON
    k.id = ka.id
    AND k.region = ka.region

```
