### ISSUE TITLE
Add table aws_codebuild_build with column end_time (build end time)

### ISSUE THREAD

**Issue by Priyanka-Chatterjee-2000** [turbot/steampipe-plugin-aws#1596]
List call : https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/codebuild@v1.20.1#Client.ListBuildBatches
Get call : https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/codebuild@v1.20.1#Client.BatchGetBuildBatches

**Comment by cbruno10** [comment]
@Priyanka-Chatterjee-2000 Can you please include a link to the API functions you'll be using to get this column's data? Thanks!
