### ISSUE TITLE
Add column website_configuration in table aws_s3_bucket

### ISSUE THREAD

**Issue by madhushreeray30** [turbot/steampipe-plugin-aws#1604]
terraform link : https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_website_configuration

SDK link : https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3@v1.30.1#Client.GetBucketWebsite

**Comment by cbruno10** [comment]
Should this be a separate table or a column in the `aws_s3_bucket` table?

**Comment by madhushreeray30** [comment]
@cbruno10 Initially I thought that it should be a separate table as we have a resource available for `aws_s3_bucket_website_configuration` in terraform however on seeing the `aws_s3_bucket` table I noticed we have established the same pattern for `aws_s3_bucket_logging` and `aws_s3_bucket_acl` as columns in the same table although we have resources for the same available in terraform. Thus after suggesting with @bigdatasourav I think it should be a column rather than a separate table.
