### ISSUE TITLE
The sns:ListTagsForResource API call 408 timeout errors should be handled as retryable

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-aws#1611]
**Describe the bug**
SNS can throw an error:
`ERROR: rpc error: code = Unknown desc = operation error SNS: ListTagsForResource, https response error StatusCode: 408, RequestID: , api error UnknownError: UnknownError (SQLSTATE HV0000`

This error doesn't seem to be marked as retryable though by AWS, but should be if it's truly a 408 (timeout) error

**Steampipe version (`steampipe -v`)**
v0.19.0-rc.2

**Plugin version (`steampipe plugin list`)**
v0.93.0

**To reproduce**
Create 10,000+ SNS topics, and run `select * from aws_sns_topic`

**Expected behavior**
The request for listing tags is retried until it hits the maximum number of attempts

**Additional context**
Related issue in SPC: https://github.com/turbotio/steampipe-cloud/issues/1762

**Comment by graza-io** [comment]
Attempted to look at this as part of something else by adding a `DefaultRetryConfig` to the table:
```go
func snsRetryConfig() *plugin.RetryConfig {
	return &plugin.RetryConfig{
		MaxAttempts:          20,
		BackoffAlgorithm:     "Exponential",
		RetryInterval:        1000,
		CappedDuration:       240000,
		ShouldRetryErrorFunc: snsRetryError,
	}
}

func snsRetryError(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData, err error) bool {
	if strings.Contains(err.Error(), "StatusCode: 408") {
		plugin.Logger(ctx).Debug("snsRetryError", "retrying 408", err.Error())
		return true
	}
	if strings.Contains(err.Error(), "no such host") {
		plugin.Logger(ctx).Debug("snsRetryError", "no such host", err.Error())
		return true
	}
	return false
}
```

This then retries these errors (& those matching the `no such host` issue) until it eventually failed with:
```
Error: table 'aws_sns_topic' column 'tags_src' requires hydrate data from listTagsForSnsTopic, which failed with error operation error SNS: ListTagsForResource, exceeded maximum number of attempts, 9, https response error StatusCode: 0, RequestID: , request send failed, Post "https://sns.eu-west-1.amazonaws.com/": dial tcp 3.250.244.32:443: connect: can't assign requested address. 
(SQLSTATE HV000)
```

More info on [internal slack](https://turbothq.slack.com/archives/C04HFMR3WKC/p1693557512547389?thread_ts=1693295735.105669&cid=C04HFMR3WKC)
