### ISSUE TITLE
Error: unexpected EOF when sorting by cidr 

### ISSUE THREAD

**Issue by dboeke** [turbot/steampipe-plugin-aws#1613]
**Describe the bug**
when sorting a table by a column with a datatype of cidr, I get an error (`Error: unexpected EOF`) when trying to sort by that column.

**Steampipe version (`steampipe -v`)**
v0.18.6

**Plugin version (`steampipe plugin list`)**
v0.93.0

**To reproduce**
```sql
SELECT 
  cidr_ipv4, 
  ip_protocol, 
  from_port, 
  to_port type 
FROM 
  aws_vpc_security_group_rule 
ORDER BY 
  cidr_ipv4;
```

**Expected behavior**
Result should display with rows sorted by cidr address.

**Additional context**
Sorting by other columns in this table works fine.

**Comment by rajlearner17** [comment]
@dboeke Thanks for raising this. Thank you. 
We will look into this more.

**Comment by judell** [comment]
@dboeke it seems to work if you cast the inet to text:

```
  select
    cidr_ipv4::text, 
    ip_protocol, 
    from_port, 
    to_port type 
  from
    aws_vpc_security_group_rule 
  order by
    cidr_ipv4
```

**Comment by dboeke** [comment]
@judell thanks for the work around, but I think the native type does support sorting, so we should as well.

**Comment by cbruno10** [comment]
@kaidaguerre Is ordering by inet columns currently supported in Steampipe? If so, is there something in the plugin table we need to adjust?
