### ISSUE TITLE
Add column managed_actions in `aws_elastic_beanstalk_environment` table

### ISSUE THREAD

**Issue by Priyanka-Chatterjee-2000** [turbot/steampipe-plugin-aws#1616]
Error in example query:
```pgsql
 select
  environment_name,
  a ->> 'ActionDescription' as action_description,
  a ->> 'ActionId' as action_id,
  a ->> 'ActionType' as action_type,
  a ->> 'Status' as action_status,
  a ->> 'WindowStartTime' as action_window_start_time
from
  aws_elastic_beanstalk_environment,
  jsonb_array_elements(managed_actions) as a;
  ```
  where `managed_actions` does not exist in `aws_elastic_beanstalk_environment` table

**Comment by cbruno10** [comment]
@ParthaI What's the status of the PR? Are we blocked by anything?

**Comment by ParthaI** [comment]
@cbruno10 We have raised a [PR](https://github.com/turbot/steampipe-plugin-aws/pull/1620) for this but the data for this column are not rendering after setting up the managed action details in Elastic Beanstalk Environment. So we could not validate the code changes. We had raise a support request with [SDK](https://github.com/aws/aws-sdk-go-v2/issues/2082) side.

We have got the response from support team, we need to do some more testing after configuring the `managed-actions` in the console. We will do it next week.

Thanks!

**Comment by cbruno10** [comment]
@ParthaI In that SDK issue, it looks like of the maintainers was trying to run the code snippet you gave him, but there may be an error. Can you please respond with the correct print statement so they have a chance to check from their end? Thanks!
