### ISSUE TITLE
Getting `ThrottlingException` error for column `account_sharing_info_list` in table `aws_ssm_document`

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-aws#1645]
**Describe the bug**
Getting below error in cloumn `account_sharing_info_list` for table `aws_ssm_document`

```
> select * from aws_ssm_document

Error: table 'aws_ssm_document' column 'account_sharing_info_list' requires hydrate data from getAwsSSMDocumentPermissionDetail, which failed with error operation error SSM: DescribeDocumentPermission, exceeded maximum number of attempts, 9, https response error StatusCode: 400, RequestID: 1366666d-3559-6666-8d04-fe66666610, api error ThrottlingException: Rate exceeded.
 (SQLSTATE HV000)
 ```
**Steampipe version (`steampipe -v`)**
Example: v0.19.1

**Plugin version (`steampipe plugin list`)**
Example: v0.92.2

**To reproduce**
select * from aws_ssm_document

**Expected behavior**

**Additional context**

**Comment by misraved** [comment]
We added a new table `aws_ssm_document_permission` which includes `account-sharing_info_list` and `account_ids` columns. We recommend you use this new table to query the above two columns.

We have also marked the `account-sharing_info_list` and `account_ids` columns in the `aws_ssm_document` table as deprecated and they will be removed in a future release.

PR reference. - https://github.com/turbot/steampipe-plugin-aws/pull/1670
