### ISSUE TITLE
Add table aws_cloudwatch_metric_data_point

### ISSUE THREAD

**Issue by bigdatasourav** [turbot/steampipe-plugin-aws#1654]
**References**
https://github.com/turbot/steampipe-plugin-aws/issues/1311

**Comment by roisec** [comment]
@bigdatasourav when this is supposed to realesed?

**Comment by rajlearner17** [comment]
@roisec Thanks for checking out!
https://github.com/turbot/steampipe-plugin-aws/pull/1655 & https://github.com/turbot/steampipe-plugin-aws/pull/1649 are expected to come next week. 

CC @misraved @cbruno10

**Comment by cbruno10** [comment]
@roisec Can you please open a new issue for this? I'm afraid the conversation will get lost in these PR comments and think they're worth of their own issue. Thanks!
