### ISSUE TITLE
Add tables aws_athena_query_executions and aws_athena_workgroup

### ISSUE THREAD

**Issue by rinzool** [turbot/steampipe-plugin-aws#1664]
**References**
> Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.
Athena Documentation: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/athena

**Ideas**
It could be nice to list query executions using [ListQueryExecutions](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/athena#Client.ListQueryExecutions) function and to have their details (duration, query, state, ...) using [GetQueryExecution](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/athena#Client.GetQueryExecution) or [BatchGetQueryExecution](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/athena#Client.BatchGetQueryExecution)

**Related PR**
https://github.com/turbot/steampipe-plugin-aws/pull/1666

**Comment by rajlearner17** [comment]
@rinzool Appreciate showing interest in Steampipe 👍 

To ensure we prioritise this, we would like to hear about your use case of Steampipe and the particularly requested feature. Happy to see your PR contribution to this issue as well. Here is [doc](https://steampipe.io/docs/develop/writing-your-first-table) reference.
Looking forward to hearing from you.

**Comment by rinzool** [comment]
> @rinzool Appreciate showing interest in Steampipe +1
> 
> To ensure we prioritise this, we would like to hear about your use case of Steampipe and the particularly requested feature. Happy to see your PR contribution to this issue as well. Here is [doc](https://steampipe.io/docs/develop/writing-your-first-table) reference. Looking forward to hearing from you.

We would like to build some dashboards / alerting based on the number of Athena query, their average duration, etc. 
Since we already use Steampipe, it would be a nice integration :+1:

**Comment by rinzool** [comment]
Hi @rajlearner17 I just opened the PR for review, I think it's ready! (Well locally it works exactly as I expected :grin:)
https://github.com/turbot/steampipe-plugin-aws/pull/1666
