### ISSUE TITLE
Add column `managed_action`  in table `aws_elastic_beanstalk_environment`

### ISSUE THREAD

**Issue by madhushreeray30** [turbot/steampipe-plugin-aws#1667]
sdk link : https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticbeanstalk@v1.15.0#Client.DescribeEnvironmentManagedActions

Required : well-architected (security_pillar_6 > control (conig rule : ELASTIC_BEANSTALK_MANAGED_UPDATES_ENABLED))

**Comment by ParthaI** [comment]
The [DescribeEnvironmentManagedActions](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticbeanstalk@v1.15.0#Client.DescribeEnvironmentManagedActions) API does not provide any managed action info.

Raised a support request with AWS Go SDK, Ref: https://github.com/aws/aws-sdk-go-v2/issues/2082

**Comment by ParthaI** [comment]
Addressed in https://github.com/turbot/steampipe-plugin-aws/pull/1620
