### ISSUE TITLE
Add table aws_ssoadmin_account_assignment

### ISSUE THREAD

**Issue by janslow** [turbot/steampipe-plugin-aws#1668]
Hi, thanks for the work you've done on this project!

I'd like to propose adding a `aws_ssoadmin_account_assignment` table, to allow "Account Assignments" in AWS Identity Centre (prefix: `ssoadmin`) to be queried. If you're happy with this proposal, **I'm happy to put a PR together for this**.

## Structure
I was imagining the table structure would look like this:

| Name | Type | Description |
| ---- | ---- | ----------- |
| `target_account_id` | `text` | The identifier of the AWS account from which to list the assignments. |
| `instance_arn` | `text` | The Amazon Resource Name (ARN) of the SSO Instance under which the operation will be executed. |
| `permission_set_arn` | `text` | The ARN of the permission set from which to list assignments. |
| `principal_type` | `text` | The entity type for which the assignment will be created. |
| `principal_id` | `text` | An identifier for an object in IAM Identity Center, such as a user or group. |

As a few notes:
* AWS provides no IDs/ARNs for this resource and doesn't support tags
* `permission_set_arn`, `instance_arn` and `target_account_id` would all be `KeyColumns` for the `List` config
* I've renamed the `AccountAssignment.account_id` field from the API result to `target_account_id` to avoid conflicts with [the standard `account_id`](https://steampipe.io/docs/develop/standards#standard-columns) column
    * Terraform also uses [the prefix `target_` for this attribute](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssoadmin_account_assignment#target_id)
* Terraform adds a `target_type` attribute (and uses `target_id` instead of `target_account_id`), but this doesn't align with the AWS API (account assignments can only target individual accounts), so I haven't followed this

## Decision: Optional `instance_arn`

As a potentially controversial decision, I'd propose making the `instance_arn` an optional key column to simplify the queries for users.

The `instance_arn` can be inferred from the `permission_set_arn`, because [AWS defines the Identity Centre ARNs as follows](https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiamidentitycentersuccessortoawssinglesign-on.html#awsiamidentitycentersuccessortoawssinglesign-on-resources-for-iam-policies):
* PermissionSet ARN as `arn:${Partition}:sso:::permissionSet/${InstanceId}/${PermissionSetId}` 
* Instance ARN is `arn:${Partition}:sso:::instance/${InstanceId}`

## Future Enchancements

_Out of scope of the initial implementation._

If you're trying to list all assignments across multiple accounts or permission sets, you currently have to call `ListAccountAssignements` for every combination of account and permission set, which is inefficient.

However, AWS also provides `ListPermissionSetsProvisionedToAccount` and `ListAccountsForProvisionedPermissionSet` which can optimise this query.

For example, if listing all assignments for an account, you can use the `ListPermissionSetsProvisionedToAccount` to list the relevant permission set ARNs (rather than `ListPermissionSets`), then use the `ListAccountAssignments` API to get the individual assignments.

As a future enhancement we could either:
* Add a new table which models provisioned permission sets, but not the individual assignments
* Make the key columns optional and use the extra APIs as part of the list hydrate function

### List all account assignments for a given account and permission set

```sql
select
    principal_type,
    principal_id,
from
    aws_ssoadmin_account_assignment
where
    permission_set_arn = 'arn:aws:sso:::permissionSet/ssoins-0123456789abcdef/ps-0123456789abcdef'
    and target_account_id = '012347678910'
```

### List the Identity Store group names of account assignments for a given account and permission set

```sql
select
    g.name
from
    aws_ssoadmin_account_assignment a
left join
    aws_identitystore_group g on g.id = a.principal_id
where
    permission_set_arn = 'arn:aws:sso:::permissionSet/ssoins-0123456789abcdef/ps-0123456789abcdef'
    and target_account_id = '012347678910'
    and principal_type = 'GROUP'
```

### List account assignments across an organization

```sql
select
    a.name,
    p.name,
    s.principal_type,
    s.principal_id,
from
    aws_ssoadmin_account_assignment s,
left join
    aws_ssoadmin_permission_set p on p.arn = s.permission_set_arn
left join
    aws_organizations_account a on a.id = s.target_account_id
```

## References
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

* [`ListAccountAssignments` API](https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_ListAccountAssignments.html)
    * Note, there is no Get/Describe API for this resource.
* [`AccountAssignment` resource](https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_AccountAssignment.html)
* [`aws_ssoadmin_account_assignment` Terraform resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssoadmin_account_assignment) (for the table name, as per [the naming convention](https://steampipe.io/docs/develop/standards#naming))

**Comment by misraved** [comment]
Welcome to Steampipe @janslow and thanks for raising the issue with a great set of details.

We would love a PR from you 👍.

**Comment by cbruno10** [comment]
Hey @janslow , wow, thanks for the great write-up! Any questions I had initially were answered (and more) in your initial comment, so thanks again for that 😄 

The proposed column names look good.

For the `instance_arn` column, if it were an optional qual, would `permission_set_arn` essentially be a required qual then? What happens if a user doesn't provide a `permission_set_arn`?

**Comment by cbruno10** [comment]
Ah @janslow , thanks, I missed that `PermissionSetArn` was required for that API call.

I was reading over docs around permission sets, as I haven't used them before, and wanted to check if I understood a typical workflow of how a user would set them up. Do the steps below make sense (with the corresponding API afterward), or am I misunderstanding any part?

- Create a permission set (https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_CreatePermissionSet.html)
- For custom permission sets, attach managed or put inline policies to the permission set (https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_AttachCustomerManagedPolicyReferenceToPermissionSet.html, https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_AttachManagedPolicyToPermissionSet.html, https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_PutInlinePolicyToPermissionSet.html)
- Provision the permission set to some or all AWS accounts (https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_ProvisionPermissionSet.html)
- Create an account assignment in one or more accounts to one or more users and groups (https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_CreateAccountAssignment.html)

Thanks!

**Comment by janslow** [comment]
> Do the steps below make sense (with the corresponding API afterward), or am I misunderstanding any part?

Yeah, that's pretty much it.

The permission set is a template for an IAM role in each AWS account, that can be assumed by AWS SSO.

The only difference is that step 3 is done automatically by the `CreateAccountAssignment` API.

You only have to run the `ProvisionPermissionSet` API when you update a permission set. For example, if you add a new managed policy, you'll need to run `ProvisionPermissionSet` to sync that change to the IAM roles in each account.
