### ISSUE TITLE
Throttle parameter to be added for concurrent AWS accounts

### ISSUE THREAD

**Issue by massyn** [turbot/steampipe-plugin-aws#1672]
**Is your feature request related to a problem? Please describe.**
When running steampipe on a large AWS environment, we inadvertently will hit problems like API rate limits, or the issue of running out of memory.  While we recognize that aggregators cannot scale infinitely, there are requirements to have steampipe manage the memory and the number of connections in a manner not to exhaust all resources.

**Describe the solution you'd like**
While an aggregator is great, there has to be a mechanism to tell steampipe to limit the number of concurrent AWS accounts it should query.

Instead of using the `--search-path-prefix`, the new feature request should be able to query each individual connection, one by one, or a number of connections at a time, and still return the same result.  This may take steampipe longer to run,  but it is a tradeoff between time-to-complete vs memory consumption and API rate limit exhaustion.

**Describe alternatives you've considered**
Building custom scripts to create a separate spc file for every account, and running the compliance module one AWS account at a time.

**Additional context**
We've been advised to use the `--search-path-prefix` option, however this is not useful, as Steampipe would still try to connect to all the connections, and allocate memory.  In some cases I found that steampipe would not respect the parameter, and still query every AWS account in the aggregator.

Rather than running our own adhoc script to run the queries against every account (thus accumulating technical debt), steampipe should be intelligent enough to limit the connections in such a manner as not to overwhelm the target API system, and not to fully exhaust all available memory on the running instance.

**Comment by bigdatasourav** [comment]
Hey @massyn, apologies for the delay in getting back to you.

Could you please explore the option of increasing the max_error_retry_attempts and/or min_error_retry_delay parameters? You can find more information on configuring these settings [here](https://hub.steampipe.io/plugins/turbot/aws#configuration). Please provide us with your feedback after making the adjustments.
