### ISSUE TITLE
Ideas for new AWS Well-Architected tables

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-aws#1688]
- `aws_wellarchitected_answer`
  - https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_ListAnswers.html
    - Requires lens alias and workload ID in request
  - https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_GetAnswer.html
    - Requires lens alias, workload ID, and question ID in request
- `aws_wellarchitected_check_detail`
  - https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_ListCheckDetails.html
    - Requires workload ID, lens alias, pillar ID, and choice ID in request
- `aws_wellarchitected_check_summary`
  - https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_ListCheckSummaries.html
    - Need workload ID, lens alias, pillar ID, and choice ID in request
- `aws_wellarchitected_consolidated_report`
  - https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_GetConsolidatedReport.html
  - Should use JSON format
  - Can also return Base64-Encoded representation of report
- `aws_wellarchitected_lens`
  - https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_ListLenses.html
  - https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_GetLens.html
- `aws_wellarchitected_lens_review`
  - https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_ListLensReviews.html
      - Use Workload table as parent hydrate
  - https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_GetLensReview.html
- `aws_wellarchitected_lens_review_improvement`
  - https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_ListLensReviewImprovements.html
    - Requires lens alias and workload ID in request
- `aws_wellarchitected_lens_review_report`
  - https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_GetLensReviewReport.html
    - Requires lens alias and workload ID in request
    - Can only return Base-64 encoded string of lens review report, which can be used to make a PDF
- `aws_wellarchitected_lens_share`
  - https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_ListLensShares.html
    - Use Lens table as parent hydrate
- `aws_wellarchitected_milestone`
  - https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_ListMilestones.html
    - Use Workload table as parent hydrate
  - https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_GetMilestone.html
- `aws_wellarchitected_notification`
  - https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_ListNotifications.html
- `aws_wellarchitected_share_invitation`
  - https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_ListShareInvitations.html
  - May need to split into 2 tables if the API can only return one type of lens vs. workload share invitation per API call
- `aws_wellarchitected_workload_share`
  - https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_ListWorkloadShares.html
  - Use Workload table as parent hydrate

**Comment by cbruno10** [comment]
Re-opening as the tables haven't been implemented yet, we can close once all valid tables have been added.

**Comment by misraved** [comment]
All the tables have been created and merged to the main 👍.
