### ISSUE TITLE
Refreshing session token does not update in connections 

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-aws#1691]
**Describe the bug**
If I have an AWS profile setup:
```
$ cat ~/.aws/credentials
[default]
aws_access_key_id = key_id
aws_secret_access_key = secret_key
aws_session_token = session_token
```

And my creds are good for an hour, after an hour if I still have the same Steampipe session running, and I run a query, I'll receive an error, `ExpiredToken: The provided token has expired.`

In the cred management code, when we get an access key, secret key, and session token, we use the [NewStaticCredentialsProvider type](https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/service.go#L1687), which the SDK will never expire.

**Steampipe version (`steampipe -v`)**
v0.19.3

**Plugin version (`steampipe plugin list`)**
v0.99.0

**To reproduce**
See above.

**Expected behavior**
The credentials should be refreshed.

**Additional context**

**Comment by ajoga** [comment]
Hey @cbruno10 -- if the postulate is that the end-user wrote in his `~/.aws/credentials` file temporary credentials, then there is no way you can refresh credentials to extend their life. The session token has an expiry in it, and AWS won't let you extend it or derive infinitely other credentials from these.

Your options are one of these: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials (or the go-equivalent page of documentation :) )

The official mod documentation page has some guides about using AWS SSO or other credentials: https://hub.steampipe.io/plugins/turbot/aws#assumerole-credentials-no-mfa 

I would not recommend Steampipe to write `~/.aws/credentials`.
