### ISSUE TITLE
Fix/Update TF scripts for integration test

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-aws#1710]
**Describe the bug**

Look into following integration test to rectify continuous failures

Note: Update AWS CLI version 2

- [ ] aws_auditmanager_assessment -- (Check the CLI command update)
```
Error running command 'aws auditmanager list-assessment-frameworks
--framework-type Standard --output json --profile default --region us-east-1
> /tmp/tests/aws_auditmanager_assessment/terraform/test/list-framework.json':
```
- [ ] aws_auditmanager_framework -- 
```
null_resource.named_test_resource (local-exec): Executing: ["/bin/sh" "-c" "aws auditmanager list-assessment-frameworks --framework-type Standard --output json --profile default --region us-east-1 > /tmp/tests/aws_auditmanager_framework/terraform/test/output.json"]
null_resource.named_test_resource (local-exec): usage:
null_resource.named_test_resource (local-exec): Note: AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use. For more information, see the AWS CLI version 2 installation instructions at: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html
```
- [ ] aws_dms_replication_instance -- The required role is not set properly
```
Error: creating DMS Replication Instance: AccessDeniedFault: The IAM Role arn:aws:iam::260848201234:role/dms-vpc-role is not configured properly.   with aws_dms_replication_instance.named_test_resource,
  on variables.tf line 50, in resource "aws_dms_replication_instance" "named_test_resource":
  50: resource "aws_dms_replication_instance" "named_test_resource" {
```
- [ ] aws_ec2_launch_template -- Probable TF fix
```
Error: creating License Manager License Configuration (turbottest57179): AccessDeniedException: Service role not found. Consult setup procedures in License Manager User Guide and create the required role for the service.
```
- [ ] aws_eks_addon_version 
- [ ] aws_elastic_beanstalk_environment -- Error: creating Elastic Beanstalk Environment (turbottest58694): InvalidParameterValue: No Solution Stack named '64bit Amazon Linux 2 v3.6.3 running Go 1' found. status code: 400, request id: 703adfdb-9338-491d-b074-47ff6577cdb8.   with aws_elastic_beanstalk_environment.named_test_resource, on variables.tf line 136,
- [ ] aws_glue_crawler -- (TF change to check to provide IAM role permission)
`Error: creating Glue Crawler (turbottest51441): InvalidInputException: User: arn:aws:sts::260848201234:assumed-role/turbottest51441/AWS-Crawler is not authorized to perform: dynamodb:DescribeTable on resource: arn:aws:dynamodb:us-east-1:260848201234:table/turbottest51441 because no identity-based policy allows the dynamodb:DescribeTable action (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: AccessDeniedException; Request ID: LLLKVRVK6IR4DGOE83B18HK5CFVV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null)
`

- [ ] aws_guardduty_finding - (CLI Update + TF change)
  ```
  Error running command 'AWS  guardduty create-sample-findings --region
  us-east-1 --detector-id c4c3ae727a86e9b670315fed5db7f402 --finding-types
  Backdoor:EC2/DenialOfService.Tcp': exit status 127. Output: /bin/sh: AWS:
  command not found,
  looks like the command is no more working
  command = "AWS  guardduty create-sample-findings --region ${var.aws_region} --detector-id ${aws_guardduty_detector.named_test_resource.id} --finding-types Backdoor:EC2/DenialOfService.Tcp"
  ```
- [ ] aws_guardduty_member - (Revisit the test queries)
    ```
    Running SQL query: test-get-query.sql
        null (FAILED)
        Running SQL query: test-list-query.sql
        null(FAILED)
    ```

- [ ] aws_iam_access_advisor -- (TF Change)
    ```
    Running SQL query: test-list-query.sql
    Error: operation error IAM: GenerateServiceLastAccessedDetails, https response error StatusCode: 400, RequestID: 19be4d14-33c3-4b46-879c-fbdsvfdfda25, InvalidInput: Invalid Entity Arn: arn:aws:sts::260848201234:assumed-role/steampipe-intg-test/i-0cf3eb1f54441eacf is not supported. (SQLSTATE HV000)
    {}
    ```
- [ ] aws_organizations_account

- [ ] aws_rds_db_cluster --  Revisit the TF & queries (test-get-query.sql & test-hydrate-query.sql) innodb_buffer_pool_load_now parameter

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by misraved** [comment]
Fixed in https://github.com/turbot/steampipe-plugin-aws/pull/1776
