### ISSUE TITLE
aws_s3_bucket should ignore GetBucketLocation failure

### ISSUE THREAD

**Issue by IgorMilavec** [turbot/steampipe-plugin-aws#1713]
**Is your feature request related to a problem? Please describe.**
If the caller does not have GetBucketLocation permissions on all the buckets, select from aws_s3_bucket fails with:
```
Error: operation error S3: GetBucketLocation, https response error StatusCode: 403, RequestID: ..., HostID: ..., api error AccessDenied: Access Denied (SQLSTATE HV000)
```

**Describe the solution you'd like**
Just skip the failed buckets. Think of it like row-level security.

**Describe alternatives you've considered**
Tried filtering the offending buckets with WHERE, but that did not help.

**Additional context**
I can submit a PR if the proposed solution is acceptable.
If #1586 is implemented, it will require ListBucket permission that is even more sensitive to acquire than GetBucketLocation permission. The best option would be to implement both at the same time. @ParthaI

**Comment by cbruno10** [comment]
Hi @IgorMilavec , I think some of the query got lost, can you please share the full query or queries that you're running? Depending what columns you're selecting, different hydrates/API calls will be used.

Thanks!

**Comment by IgorMilavec** [comment]
Oh, sorry, I did not think it was relevant. Here is the query:
```

SELECT  's3' AS service, title,
        COALESCE(tags->>'Environment',tags->>'Env') AS sr_environment,
        tags->>'Name' AS sr_name,
        tags->>'Project' AS sr_project,
        account_id,
        region, 
        arn
FROM    aws.aws_s3_bucket
WHERE   name NOT LIKE '%-some-suffix'
```

**Comment by e-gineer** [comment]
S3 is an interesting API flow. We can query the actual list of buckets from any region, but specific details about buckets can only be obtained by querying the specific region where the bucket is located. To get that location we need to first call `GetBucketLocation` - for example, to get the tags we first need to get the location so we can then query that region for the tags.

Does that make sense? Are you able to provide more details of the exact situations where this flow is not working?

**Comment by IgorMilavec** [comment]
Sure, it makes perfect sense. In my case my role has permissions to list the buckets, however it lacks permissions (including get bucket location) on some specific buckets.
The problem is that query is aborted by the error from GetBucketLocation and I do not get any results.
I propose to ignore this error which would allow me to get the requested information for all the other buckets for which I do have access.

**Comment by misraved** [comment]
Hey @IgorMilavec, you could use the `ignore_error_codes` config argument to ignore the errors of your choice 👍.

You could take a look at https://github.com/turbot/steampipe-plugin-aws/blob/main/config/aws.spc#L42 for more information on how to set up the `ignore_error_codes` argument.

Please let us know if you have more questions, happy to help 👍.

**Comment by bigdatasourav** [comment]
Hey @IgorMilavec, I believe the above-proposed solution helped you to resolve the issue you were facing. We are closing the issue now. Please feel free to reopen the issue if you want to share or discuss anything.
