### ISSUE TITLE
Add table aws_rds_db_instance_automated_backup

### ISSUE THREAD

**Issue by foolioo** [turbot/steampipe-plugin-aws#1714]
**Is your feature request related to a problem? Please describe.**
AWS RDS [automated backups](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithAutomatedBackups.html#USER_WorkingWithAutomatedBackups.Enabling) are available through AWS CLI

```shell
aws rds describe-db-instance-automated-backups --db-instance-identifier DBInstanceIdentifier
```

**Describe the solution you'd like**
`aws_rds_db_instance_automated_backup` table needs to include\reflect the automated backups.
The automated backup is disabled by default.

**Additional context**
- https://github.com/turbot/steampipe/discussions/3355
- CC @cbruno10

**Comment by ParthaI** [comment]
@foolioo I Appreciate raising this issue!
We have added a new table in the attached [PR](https://github.com/turbot/steampipe-plugin-aws/pull/1721). If you like to test and provide some early feedback would be great before our release.

To execute this branch:

```
1. git clone https://github.com/turbot/steampipe-plugin-aws.git
2. cd steampipe-plugin-aws
3. git checkout issue-1714
4. Execute make
5. Run your query
(Note in case you have already this checked out aws-plugin repo, prefer to checkout main > git pull > git checkout issue-1714 branch)
```
Thanks!
