### ISSUE TITLE
Add table aws_ec2_client_vpn_endpoint

### ISSUE THREAD

**Issue by mvanholsteijn** [turbot/steampipe-plugin-aws#1717]
**References**

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateClientVpnEndpoint.html
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_client_vpn_endpoint

**Comment by misraved** [comment]
Welcome to Steampipe @mvanholsteijn and thanks for raising the table request!!

For listing out the Client VPN endpoints we could use the following API - https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeClientVpnEndpoints.html

- `ListConfig`:
  - Hydrate - [listEC2ClientVPNEndpoints](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeClientVpnEndpoints.html)
  - Optional qual - `transport_protocol` can be used as an optional qual

- `GetConfig`:
  - Hydrate - [getEC2ClientVPNEndpoint](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeClientVpnEndpoints.html)
  - Required qual - `client_vpn_endpoint_id` 

- Pagination is supported

- Sample output response - https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ClientVpnEndpoint.html
