### ISSUE TITLE
AWS environment variables are not honored

### ISSUE THREAD

**Issue by electriquo** [turbot/steampipe-plugin-aws#1742]
**Describe the bug**
AWS CLI and AWS SDK honor [AWS environment variables](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html), while steampipe does not and displays the error

```txt
ERROR: rpc error: code = Unknown desc = operation error Elastic Load Balancing v2: DescribeLoadBalancers, https response error StatusCode: 403, RequestID: 9c80b7d8-6cc7-4d20-ae5d-7955fcde037a, api error AccessDenied: User: arn:aws:sts::1234:assumed-role/foo/i-xxx is not authorized to perform: elasticloadbalancing:DescribeLoadBalancers because no identity-based policy allows the elasticloadbalancing:DescribeLoadBalancers action (SQLSTATE HV000)
```

**Steampipe version (`steampipe -v`)**
```shell
$ steampipe --version
Steampipe v0.20.2
```

**Plugin version (`steampipe plugin list`)**
```shell
$ steampipe plugin list
+---------------------------------------------+---------+-------------+
| Installed Plugin                            | Version | Connections |
+---------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/aws@0.103.0 | 0.103.0 | aws         |
+---------------------------------------------+---------+-------------+
```

**To reproduce**
1. Expose AWS environment variables
   ```shell
   $ env | grep -o '^AWS.*='
   AWS_DEFAULT_REGION=
   AWS_REGION=
   AWS_ROLE_ARN=
   AWS_WEB_IDENTITY_TOKEN_FILE=
   AWS_STS_REGIONAL_ENDPOINTS=
   ```
2. Verify AWS environment variables are working, has [ReadOnlyAccess role policy](https://hub.steampipe.io/plugins/turbot/aws#credentials) and there are no AWS CLI credential file
   ```shell
   $ ls -x1R ~/.aws/
   /root/.aws/:
   cli

   /root/.aws/cli:
   cache

   $ aws --version
   aws-cli/2.11.21 Python/3.11.3 Linux/5.4.204-113.362.amzn2.x86_64 exe/x86_64.debian.11 prompt/off

   $ aws iam list-attached-role-policies --role-name $(aws sts get-caller-identity --query Arn --output text | rev | cut -d / -f 2 | rev)
   {
       "AttachedPolicies": [
           {
               "PolicyName": "ReadOnlyAccess",
               "PolicyArn": "arn:aws:iam::aws:policy/ReadOnlyAccess"
           }
       ]
   }
   ```
3. Install [steampipe aws plugin](https://hub.steampipe.io/plugins/turbot/aws)
4. Start steampipe dashboard
5. Open one of the AWS dashboards, e.g. `/aws_insights.dashboard.ec2_application_load_balancer_detail`

**Expected behavior**
AWS plugin should honor AWS environment variables.

**Additional context**
- AWS environment variables docs for `AWS_ROLE_ARN` states:
  > If defined, this environment variable overrides the value for the profile setting [role_arn](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-config-role_arn). You can't specify a role session name as a command line parameter.
- https://hub.steampipe.io/plugins/turbot/aws#configuring-aws-credentials

If there is no bug, then any guidance on how to make AWS plugin to honor AWS environment variables will be appreciated.

**Comment by cbruno10** [comment]
Hi @foolioo , can you please let us know which AWS environment variables specifically aren't working for you? Is it just `AWS_ROLE_ARN`, or are there others as well?

Are you running from an EC2 instance, or another environment, like a local laptop?

Also, if you run `steampipe query` using the same AWS Steampipe connections you're using with that load balance detail page, are you able to run queries like `select name from aws_iam_role`, `select instance_id from aws_ec2_instance`, and `select name from aws_s3_bucket`?

**Comment by cbruno10** [comment]
Thanks @foolioo for the additional info, we'll look to try and reproduce from our end using the environment variables you listed above and let you know what we find.

**Comment by cbruno10** [comment]
Hi @foolioo , no not yet, we're still investigating. We'll share more info once we have it.

**Comment by graza-io** [comment]
May not resolve issue but could you maybe try setting the env var `AWS_SDK_LOAD_CONFIG=true` 

I did attempt a basic example of testing environment variables for authentication (access/secret key combination) & that worked out fine.

```
❯ source .tempenv
❯ ls -x1R ~/.aws/
❯ ll -a ~/.aws
total 0
drwxr-xr-x   2 graza  staff    64B 31 May 10:28 .
drwxr-x---+ 42 graza  staff   1.3K 31 May 10:46 ..
❯ aws --version
aws-cli/2.11.23 Python/3.11.3 Darwin/22.5.0 exe/x86_64 prompt/off
❯ env | grep -o '^AWS.*='
AWS_SDK_LOAD_CONFIG=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=
❯ steampipe query "select count(*) from aws_s3_bucket"
+-------+
| count |
+-------+
| 121   |
+-------+
```

Also would it be possible to test if writing the env vars to relevant config/credentials files works successfully with Steampipe?

**Comment by e-gineer** [comment]
@foolioo I think you should remove this from your spc file:
```hcl
profile = "default"
``` 

since you don’t have any aws config files defined then I assume you do not have a default profile to reference?

**Comment by graza-io** [comment]
Good catch, I didn't set `profile` in my `aws.spc` 
```
❯ cat ~/.steampipe/config/aws.spc
connection "aws" {
  plugin = "aws"
  regions = ["eu-*"]
}
```

When adding the line back in I do indeed get a (different) but understandable error.
```
❯ vi ~/.steampipe/config/aws.spc
❯ cat ~/.steampipe/config/aws.spc
connection "aws" {
  plugin = "aws"
  regions = ["eu-*"]
  profile = "default"
}

❯ steampipe query "select count(*) from aws_s3_bucket"

Error: operation error S3: ListBuckets, exceeded maximum number of attempts, 9, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect: no route to host (SQLSTATE HV000)

+-------+
| count |
+-------+
+-------+
```

**Comment by graza-io** [comment]
Hey @foolioo - can you check/confirm that removing the `profile` from your `.spc` file allowed you to successfully use the environment variables as expected?
