### ISSUE TITLE
table 'aws_ssoadmin_account_assignment' - feature request

### ISSUE THREAD

**Issue by ahkai86** [turbot/steampipe-plugin-aws#1748]
**Is your feature request related to a problem? Please describe.**
Unable to list multiple targeted AWS account ID and PermissionSets with respective users in a single table 
(tried my best below to provision the table but missing qualifications 'permission_set_arn' and 'target_account_id'.

**Describe the solution you'd like**
Would like to display on AWS IAM Identity Center -> AWS Accounts with associated PermissionSets and Users

**Describe alternatives you've considered**
I am trying to overcome the limitation of table 'aws_ssoadmin_account_assignment' , is there a way in the 'WHERE' statement to allow multiple subqueries?

Currently AWS SSO doesn't have a centralized dashboard, if steampipe could work, it will definitely boost the usage for those using AWS Identity Center (formally AWS SSO) =)

I am stuck at the last 'WHERE' statement to allow multiple AWS targeted_account_ID and PermissionSets to be ingested within the master IAM Identity Center account :

```
  with orgs as (
    SELECT DISTINCT id FROM aws_master.aws_organizations_account
  )
  , 
  aws_ssoadmin_principal as (
  select
    i.arn as instance_arn,
    'GROUP' as "type",
    g.id,
    g.title
  from
    aws_master.aws_ssoadmin_instance i
    left join aws_identitystore_group g on i.identity_store_id = g.identity_store_id
  union
  select
    i.arn as instance_arn,
    'USER' as "type",
    u.id,
    u.title
  from
    aws_master.aws_ssoadmin_instance i
    left join aws_identitystore_user u on i.identity_store_id = u.identity_store_id
)
SELECT
  a.name as AWSAccountName,
  a.id as AccountID,
  u.title as User,
  g.type as Type,
  p.name as PermissionSet
FROM
  aws_master.aws_organizations_account a
  LEFT JOIN aws_master.aws_ssoadmin_account_assignment aa ON aa.target_account_id = a.id
  JOIN aws_ssoadmin_principal u ON u.id = aa.principal_id 
  LEFT JOIN aws_ssoadmin_principal g ON g.id = u.id
  JOIN aws_master.aws_ssoadmin_permission_set p ON p.arn = aa.permission_set_arn
WHERE 
    target_account_id IN(SELECT id FROM orgs) 
    AND permission_set_arn  IN(SELECT arn 
    FROM aws_master.aws_ssoadmin_permission_set);
```

if the last WHERE statement is input with a specific target ID and PermissionSet, it works well !
But it is not for multiple AWS 'target_account_IDs' and 'PermissionSets'.

Will there be any updates to the table 'aws_ssoadmin_account_assignment' in near future?
Thanks so much!

**Additional context**

**Comment by ahkai86** [comment]
Managed to work around with SQL Query finding to list whole AWS Organization AWS accounts and PermissionSets with IAM Users/Group associated with it.

**Comment by ahkai86** [comment]
Hi Steampipe team, with the query working but the response load is v v slow. There are 5 tables to cross-relates to 
1. https://hub.steampipe.io/plugins/turbot/aws/tables/aws_organizations_account
2. https://hub.steampipe.io/plugins/turbot/aws/tables/aws_ssoadmin_instance
3. https://hub.steampipe.io/plugins/turbot/aws/tables/aws_identitystore_user
4. https://hub.steampipe.io/plugins/turbot/aws/tables/aws_identitystore_group
5. https://hub.steampipe.io/plugins/turbot/aws/tables/aws_ssoadmin_permission_set

Can i humbly submit for a new feature request on AWS Identity Center queries where 1 single API can co-related to 5 tables directly?

The output will show like this:
![image](https://github.com/turbot/steampipe-plugin-aws/assets/38812404/0040ca5a-2ab9-47cc-a029-b2305cab6da8)

**Comment by rajlearner17** [comment]
@ahkai86, I appreciate your patience & input on this use case. Thank you! This is a bit experimental area for sure. 

Just wanted to clarify, Do you want us to look into the provided SQL query and explore  [1] the possibility of optimisation, or do you like us to consider any [2] design change where we can use one table with all related data to provide a smooth experience to query for such use-cases?

Option 2 may lead to many other considerations to ensure this is not binding users to address only fewer use-cases and performance limiting etc.

Feel free to submit PR (if any from your side) or provide more input in the feature request, which will give more insight to the team reviewing, testing and engaging further in case we need any decisions to proceed.

**Comment by ahkai86** [comment]
Hi @rajlearner17,

Good Day! Thanks for the follow up, option [2] will be much useful and easier for users to get the required information for AWS IAM Identity Center, as AWS has undocumented API to retrieve all those info.

and AWS IAM Identity Center only gets information from 1 aws master account, theoretically i think it shouldn't traverse through the rest of the AWS accounts to get the necessary information except the master account for AWS Identity Center.

As for now on option [1], i tried various ways to optimize and encountered alot of impediments with SQL tables correlating with different tables.
Additionally, I tried to run the sql query twice and the 2nd time will just hang there, meaning i can only run once per SQL query when steampipe query dashboard is executed via "steampipe dashboard"

**Comment by rajlearner17** [comment]
Just referencing the other issue with the same context https://github.com/turbot/steampipe-plugin-aws/issues/1723

**Comment by bigdatasourav** [comment]
Hey @ahkai86, At Steampipe, our standard practice is maintaining a one-table-per-resource model. This design choice is intentional to ensure that each table is easy to understand and use, and it helps to keep the execution times as efficient as possible.

Combining multiple resources into a single table might seem like a solution for correlating data more directly. Still, it could significantly increase the table's complexity and the query execution time.

@cbruno10 your thoughts?

**Comment by bigdatasourav** [comment]
We are closing this issue as we will not be creating a multi-API table. However, we encourage you to reopen this issue if you would like to share your query; we're more than happy to assist with its optimization.
