### ISSUE TITLE
aws_cloudwatch_metric_data_point table limited for 3 hours. 

### ISSUE THREAD

**Issue by roisec** [turbot/steampipe-plugin-aws#1757]
**Describe the bug**
Hi @cbruno10 @misraved
I didn't succeed to fetch data from Cloudwatch for more than the default period.
the query is:
select * from aws_cloudwatch_metric_data_point where id='m1' and expression = 'SELECT AVG(MetadataNoToken) FROM "AWS/EC2" GROUP BY InstanceId' and timestamp >= now() - interval '7 day'
I am not able to fetch data from the history.
I am able to see only 3 hours ago

**To reproduce**
select * from aws_cloudwatch_metric_data_point where id='m1' and expression = 'SELECT AVG(MetadataNoToken) FROM "AWS/EC2" GROUP BY InstanceId' and timestamp >= now() - interval '7 day'

**Expected behavior**
I am trying to see more than 3 hours, for 30 days for example.

**Additional context**

**Comment by roisec** [comment]
@bigdatasourav 
Yea, your query works! for older than 3 hours, but it's related only to one instance-id...

**Comment by cbruno10** [comment]
Hi @roisec , based on what we could find, when using an expression, there is a limit of only getting data for the last 3 hours according to [Metrics Insights limits](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-metrics-insights-limits.html).

The queries that @bigdatasourav provided use [MetricStats](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_MetricStat.html) instead, which don't have the same limitation.

One suggestion that we haven't had a chance to try yet is using CloudWatch's ability to aggregate statistics for instances that have detailed monitoring enabled. This will require [enabling detailed monitoring](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-cloudwatch-new.html#enable-detailed-monitoring), which does come at an extra cost unfortunately, but you can try with only one, or a few instances, at first. 

@roisec Can you please try enabling detailed monitoring on a few instances and then follow the example AWS CLI command in https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/GetSingleMetricAllDimensions.html, replacing the arguments like `--metric-name`, `--start-time` and `--end-time` (and possibly others based on your requirements)?

If that works (or doesn't work but looks like it should), can you please share the output of the command here, like you did above?

Thanks!

**Comment by roisec** [comment]
@cbruno10  I didn't succeed to see the data through mentioned command. (I don't see any data)
this is the command:
`aws cloudwatch get-metric-statistics --namespace AWS/EC2 --metric-name MetadataNoToken --period 3600  --statistics "Average" --start-time 2023-05-30T15:15:00 --end-time 2023-05-31T17:15:00+05:30 --region us-east-1`

Do you think I missed something?

**Comment by cbruno10** [comment]
@roisec Can you please confirm that you've enabled detailed monitoring for instances that you expect to see data for? Also, if you try a different `--metric-name` and/or start from a shorter duration, e.g., 2 hours, then 3 hours, then 12 hours, etc., are you able to get any data?

**Comment by bigdatasourav** [comment]
Hey @roisec, We are closing this issue because we have not heard from you. Please feel free to reopen the issue if you want to share or discuss anything.
