### ISSUE TITLE
AWS - Route 53 - Query logging configurations 

### ISSUE THREAD

**Issue by Musseri10** [turbot/steampipe-plugin-aws#1769]
Hey, 
I want to understand if there is a option to query the records of "Route53 query logging configurations" and see that all the vpc's are configured.

Thanks.

**Comment by Musseri10** [comment]
Hey,

It's seems that the table doesn't contains data. We configured destination type s3. Can you check this? 

10x

**Comment by rajlearner17** [comment]
@Musseri10, Thanks for reaching out!
We're letting you know we've received this and provide further updates. Just wanted to confirm which table you are specifying here. is it `aws_route53_query_log`?

**Comment by Musseri10** [comment]
Hey,
In AWS the configuration is under Route53 --> Resolver --> Query Logging --> Query Logging Configuration

10x

**Comment by ParthaI** [comment]
Hi @Musseri10, Sorry we may misunderstand the issue. We have 2 sets of Query Logging Configuration.

- Route53 Query Logging Configuration
- Route53 Resolver Query Logging Configuration

According to the issue title/description, we added a table Route53 Query Logging Configuration table. Feel free to create another issue for it along with your use case; this will help us take quick decisions for this table. Looking forward to assisting.
[AWS Ref](https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListResolverQueryLogConfigAssociations.html)
Thank you!
