### ISSUE TITLE
Add table aws_ec2_managed_prefix_list_entry

### ISSUE THREAD

**Issue by iyesin** [turbot/steampipe-plugin-aws#1773]
*Should* return `prefixlist_id`, `cidr`, `description`.
**References**
[GetManagedPrefixListEntries](https://github.com/aws/aws-sdk-go/blob/f9eb254e13478ed2832366f4cd3b19c440a63016/models/apis/ec2/2016-11-15/api-2.json#LL3867C6-L3867C33)

**Comment by ParthaI** [comment]
Welcome to Steampipe @iyesin and thanks for raising the issue with references to the relevant API 👍.
