### ISSUE TITLE
Add image_uri column in aws_ecr_image table

### ISSUE THREAD

**Issue by bigdatasourav** [turbot/steampipe-plugin-aws#1784]
**Is your feature request related to a problem? Please describe.**
<img width="909" alt="image" src="https://github.com/turbot/steampipe-plugin-aws/assets/78197905/1f2031cf-cc22-4f7e-a06a-d62e182ced67">

If API does not provide this value, we can create it with the below format - 
concat(account_id,'.dkr.ecr.',region,'.amazonaws.com/',repository_name,'@',image_digest) // where tag is unaviable
concat(account_id,'.dkr.ecr.',region,'.amazonaws.com/',repository_name,'@',image_tag) // where tags are available

A sample URI looks like this with tag - 097234455.dkr.ecr.ap-south-1.amazonaws.com/hello:hello
Without tag - 097234455.dkr.ecr.ap-south-1.amazonaws.com/hello@sha256:984804a8ed358e0a3bce2df193c6b4d687076cc3a8f9606d5e30f3660e8f6e60

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cbruno10** [comment]
@bigdatasourav How do you get the account ID? If it's a base image URI, do we use the Amazon account IDs listed at https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/docker-custom-images-tag.html?

@johnsmyth It seems useful to have a column like this, as the `aws_ecr_repository` table has a `repository_uri` column (from the API), so users don't have to compose it.

I'm unsure of how to handle missing tags though and returning slightly different URI formats in a single column would be accurate, but potentially confusing if users don't understand how we decide which format to use.

Would it make sense to have 2 columns, e.g., `image_uri_tags`, `image_uri_digest`, and `image_uri_tags` would be `null` if no tags existed? Or would 1 column, `image_uri`, be sufficient?

**Comment by johnsmyth** [comment]
I don't think we need to have 2 columns.  I'm ok with @bigdatasourav's suggestion (use the first tab if there are tags, else the sha) -- thats what the AWS console seems to do when you do 'Copy URI'.  I would also be ok if we always use the SHA.

**Comment by bigdatasourav** [comment]
@cbruno10 The image URI format uses AWS account ID when we push any images to the private repository -https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html

The one you have shared is for EMR on EKS. While creating an EMR cluster on EKS, from Amazon EMR 6.9.0 releases and later, we can choose the base image from ECR public [gallery](https://gallery.ecr.aws/emr-on-eks/spark/emr-6.11.0), to pull those base images we have to follow that format.
