### ISSUE TITLE
Add column user_data in the table aws_ec2_launch_template_version

### ISSUE THREAD

**Issue by paulgrosskopf** [turbot/steampipe-plugin-aws#1791]
**Is your feature request related to a problem? Please describe.**
Currently, querying aws_ec2_launch_template_version returns the User Data field in 64 bit encoding. Is it possible to have this automatically decoded when displaying the launch_template_data column?

**Describe the solution you'd like**
I would like to have the User Data field be decoded into a human readable format

**Describe alternatives you've considered**
Alternatives are decoding as suggested by John Smyth or using a non Steampipe method to pull the data.

**Additional context**
This was discussed on Slack with John, Cody, & Jon

**Comment by ParthaI** [comment]
@paulgrosskopf Thank you for creating the issue and bringing it to our attention. We appreciate the time you've taken to notify us, and we will promptly address the matter.👍
