### ISSUE TITLE
Update/Enhance documentation to include permissions required for a table and/or the AWS API calls made

### ISSUE THREAD

**Issue by captainfalcon23** [turbot/steampipe-plugin-aws#1793]
**Is your feature request related to a problem? Please describe.**
When troubleshooting issues, or deploying queries to various environments, or writing new queries, it is often difficult to understand what AWS API calls are specifically being made to populate a table, or the permissions required. 

**Describe the solution you'd like**
It would be great if either the online documentation was updated to include this, or better yet, if ".inspect"ing a table would surface this info.

**Describe alternatives you've considered**
Trial and error :(

**Comment by captainfalcon23** [comment]
This is probably wider than just this plugin, but since this is the plugin I use most/care about, I have raised this here and not in the main steampipe project.

**Comment by judell** [comment]
@captainfalcon23 this also came up in our Slack community today, so clearly a need, thanks for raising the issue here.

**Comment by ajoga** [comment]
I would also add that sometimes I have query that I scope with a `WHERE region="xxx"` and it feels like all regions are still queried, but I'm mostly guessing too

**Comment by captainfalcon23** [comment]
Commenting to remove stale label.

**Comment by cbruno10** [comment]
Hey @captainfalcon23 , we currently don't have any plans to include these permissions in the plugin documentation, but here are some suggestions on how to get AWS API call information today:
- Look in the table source code to find the API call that particular List/Get/hydrate call is making. For instance, in `aws_ec2_ami`, for listing images, we use the [DescribeImages API call](https://github.com/turbot/steampipe-plugin-aws/blob/9817e2f9d7cfeb3454ed788a473dac401d79fbef/aws/table_aws_ec2_ami.go#L238), which would correspond to the IAM action `ec2:DescribeImages`.
  - Some columns that aren't included in the List or Get call, like `launch_permissions` in the same `aws_ec2_ami` table, have a [Hydrate](https://github.com/turbot/steampipe-plugin-aws/blob/9817e2f9d7cfeb3454ed788a473dac401d79fbef/aws/table_aws_ec2_ami.go#L186), which has the [DescribeImageAttribute API call](https://github.com/turbot/steampipe-plugin-aws/blob/9817e2f9d7cfeb3454ed788a473dac401d79fbef/aws/table_aws_ec2_ami.go#L313), which uses the `ec2:DescribeImageAttribute` IAM action.
- Steampipe also supports [OpenTelemetry](https://steampipe.io/blog/release-0-15-0#telemetry), which can provide more information on what's happening under the hood and more information about API calls the plugin is making. 

I'm closing this issue for now, but will re-open it if we plan to revisit this issue (in the form of doc updates or another approach).
