### ISSUE TITLE
aws_acm_certificate should return the certificetes of all type of key_algorithm

### ISSUE THREAD

**Issue by andy-werderman** [turbot/steampipe-plugin-aws#1794]
**Is your feature request related to a problem? Please describe.**
Yes. From the [Go AWS SDK documentation](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/acm#Client.ListCertificates):
> Default filtering returns only RSA_2048 certificates.

Because of the default filtering, a number of my certificates are missing from Steampipe (specifically ECDSA certificates). 

**Describe the solution you'd like**
I would like for there to be no default filtering on certificate key algorithms. I guess what this means for the plugin is to pass all key-algorithms to the `ListCertificates` API call.

**Describe alternatives you've considered**
I'm not sure this is possible with how the plugin is setup, but an alternative would be to be able to pass in the key algorithm to the api call.

**Comment by ParthaI** [comment]
@andy-werderman, I apologize for the inconvenience you are facing and appreciate your involvement with Steampipe.

- We have incorporated pagination in the List API call to retrieve all available certificates within an account.
- It appears that we overlooked the default filter applied during the API call, as mentioned in the [documentation](https://docs.aws.amazon.com/acm/latest/APIReference/API_Filters.html). Without specifying a filter for the algorithm type, the API will only return certificates with the algorithm types `RSA_1024` and `RSA_2048`.
- To address this, we have added a filter in the input parameter of the List API call to fetch certificates with all algorithm types.
- Currently, we only have a certificate with the algorithm type `RSA-2048`, so we have not been able to test with other algorithm types.
 
Could you please test the code changes in this [PR](https://github.com/turbot/steampipe-plugin-aws/pull/1797)?

Here's how to test the code changes:

- git clone https://github.com/turbot/steampipe-plugin-aws.git
- cd steampipe-plugin-aws
- git checkout `issue-1794`
- make
- Run steampipe query

Your feedback would be highly appreciated.

Thank you for your understanding and cooperation.
