### ISSUE TITLE
AWS IAM Identity Center - support for AWS SSO tables?

### ISSUE THREAD

**Issue by ahkai86** [turbot/steampipe-plugin-aws#1795]
**Is your feature request related to a problem? Please describe.**
Not a problem but a feature request =)

**Describe the solution you'd like**
IAM Identity Center table able to list IAM Users , IAM Group with respective IAM PermissionSets associated to targeted AWS Accounts within AWS Organization.
Would like to have a table or multiple tables to list 

**Describe alternatives you've considered**
i am trying to build a dashboard to list IAM Users and IAM Group associated to targeted AWS Accounts within AWS Organization.

**Additional context**

**Comment by cbruno10** [comment]
Hi @ahkai86 , we have some SSO Admin tables today in the AWS plugin (https://hub.steampipe.io/plugins/turbot/aws/tables?filter=sso), but if there are any particular resources we don't have tables for today, please let us know which ones and we can re-open this issue to discuss more. Thanks!
