### ISSUE TITLE
Add table aws_cost_usage_with_resources

### ISSUE THREAD

**Issue by thiagoeh** [turbot/steampipe-plugin-aws#1803]
AWS Cost Explorer have the optional functionality of giving resource and hourly level granularity, but it is not accessible through any of the `aws_cost_*` tables.

I'm not sure if it's best to create an additional table or to expand the existing `aws_cost_usage` table to accomodate this kind of query.

**References**
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ce/get-cost-and-usage-with-resources.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/costexplorer/#CostExplorer.GetCostAndUsageWithResources

**Comment by ParthaI** [comment]
Thank you, @thiagoeh, for initiating this issue, and I extend my apologies for the prolonged delay in responding.

- We acknowledge your request for retrieving a Cost and Usage report for a specific resource.
- Could you kindly share more details about your use case? Specifically, how you use Steampipe and the ways in which an additional table would address your current challenges?
- It's important to be aware that each API request carries associated costs. Making resource-specific requests may lead to increased expenses. Your additional insights will assist us in prioritizing this matter for further investigation. [Pricing documentation](https://aws.amazon.com/aws-cost-management/aws-cost-explorer/pricing/#:~:text=The%20AWS%20Cost%20Explorer%20API,incur%20a%20cost%20of%20%240.01).

Thanks!

**Comment by bigdatasourav** [comment]
Hey @thiagoeh, We are closing this issue as we have not heard from you. Please feel free to reopen the issue if you want to share or discuss anything.
