### ISSUE TITLE
Logs: DescribeLogStreams api error ThrottlingException: Rate exceeded

### ISSUE THREAD

**Issue by airmonitor** [turbot/steampipe-plugin-aws#1807]
**Describe the bug**
Querying hundreds of CW log groups causing ThrottlingException

operation error CloudWatch Logs: DescribeLogStreams, exceeded maximum number of attempts, 9, https response error StatusCode: 400, RequestID: 1c8266d9-2e98-48cd-b296-b52384128df9, api error ThrottlingException: Rate exceeded (SQLSTATE HV000)

**Steampipe version (`steampipe -v`)**
Example: v0.19.5

**Plugin version (`steampipe plugin list`)**
Example: hub.steampipe.io/plugins/turbot/aws@latest  0.101.0

**To reproduce**
cd steampipe-mod-aws-thrifty
aws iam generate-credential-report
steampipe dashboard

```
[ Wait    ] Loading Workspace
[ Wait    ] Starting Dashboard Server
[ Message ] Workspace loaded
[ Message ] Initialization complete
[ Ready   ] Dashboard server started on 9194 and listening on local
[ Message ] Visit http://localhost:9194
[ Message ] Press Ctrl+C to exit
[ Wait    ] Dashboard execution started: aws_thrifty.benchmark.cloudwatch
[ Ready   ] Execution complete: aws_thrifty.benchmark.cloudwatch```

**Expected behavior**
aws_thrifty.benchmark.cloudwatch could handle ThrottlingException in a better way?

**Additional context**
Add any other context about the problem here.

**Comment by misraved** [comment]
@airmonitor thanks for raising this issue and welcome to Steampipe 👍.

This error is deep-rooted in the table implementation.

Could you please try to run the control by altering the rate limit parameters (`max_error_retry_attempts` and `min_error_retry_delay`) in the `aws.spc` file?

I am transferring this issue to the `steampipe-plugin-aws` repo for deeper analysis.

**Comment by bigdatasourav** [comment]
Hey @airmonitor, We are closing this issue because we have not heard from you. Please feel free to reopen the issue if you want to share or discuss anything.
