### ISSUE TITLE
Add content column to aws_ssm_document

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-aws#1808]
**Is your feature request related to a problem? Please describe.**

Purpose - Having content available in JSON  format will help run a query to check for any sensitive data patterns or to  have the content available for analysis purposes.

Currently, we are using [func getAwsSSMDocument ](https://github.com/turbot/steampipe-plugin-aws/blob/c6377287e5a3235d1148cf9d5eedf30b4772a440/aws/table_aws_ssm_document.go#L302C1-L302C1), which has got most/all used columns (to be verified)

Maybe we can explore the below function, which provides additional columns such as `content` 

type [GetDocumentOutput](https://github.com/aws/aws-sdk-go-v2/blob/service/ssm/v1.35.1/service/ssm/api_op_GetDocument.go#L54) [¶](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ssm@v1.35.1#GetDocumentOutput)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ParthaI** [comment]
Will be addressed in https://github.com/turbot/steampipe-plugin-aws/issues/1837
