### ISSUE TITLE
ECS Task unable to fetch STOPPED or PENDING tasks

### ISSUE THREAD

**Issue by Eitan1112** [turbot/steampipe-plugin-aws#1813]
**Describe the bug**
Unable to fetch stopped/pending ECS tasks.

**Steampipe version (`steampipe -v`)**
v0.20.8

**Plugin version (`steampipe plugin list`)**
v0.108.0

**To reproduce**
Create an ECS cluster, service and start and stop a task. Once it is in stopped state, try fetching it by querying:
`SELECT * FROM aws_ecs_task`
Unfortunately it fails because the AWS API is a bit weird and filters by default only for running tasks, and only if you specify desired_status=stopped/pending it will fetch those too.

**Expected behavior**
Even tho that's how AWS API behaves, in a sql environment you don't expect to have a default filter in a table. The expected behavior is that stopped/pending tasks will be fetched too.

**Additional context**
[AWS API reference](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ListTasks.html). Scroll to the desiredStatus section.

**Comment by rajlearner17** [comment]
@Eitan1112 Appreciate using Steampipe!

Sorry to see this blocker for you; we will look into it.

**Comment by ParthaI** [comment]
@Eitan1112, Thanks for raising this issue. While looking into it, I have a few findings to share with you. Feel free to revalidate and feedback,

- The table's entry point is the list config, which utilizes the [ListTasks](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ListTasks.html) API.
- The API allows filtering of tasks based on various parameters such as `cluster name`, `container instance`, `desired status`, `family`, `service name`, and `launch type`.
- The `desired status` parameter can be set to `PENDING`, `RUNNING`, or `STOPPED`, specifying the desired task status.
- By default, the API returns tasks with the desired status set to `RUNNING`.
- It is not possible to pass multiple desired statuses in a single API call.

**Query without using any optional quals in the where clause:**

Query: `select * from aws_ecs_task`
Result: 
```
+-----------------------------------------------------------------------------------------+------------------------+----------------+----------------+-------------+-------------------+------------------->
| task_arn                                                                                | container_instance_arn | cluster_name   | desired_status | launch_type | availability_zone | capacity_provider_>
+-----------------------------------------------------------------------------------------+------------------------+----------------+----------------+-------------+-------------------+------------------->
| arn:aws:ecs:us-east-1:222222222222:task/test53-cluster/c1afe9b34f35443e9c4e6e4b46690dd0 | <null>                 | test53-cluster | RUNNING        | FARGATE     | us-east-1a        | FARGATE           >
+-----------------------------------------------------------------------------------------+------------------------+----------------+----------------+-------------+-------------------+-------------------
```

**Query with `desired_status` set to `STOPPED` in the where clause:**

Query: `select * from aws_ecs_task where desired_status = 'STOPPED'`
Result: 
```
+-----------------------------------------------------------------------------------------+------------------------+----------------+----------------+-------------+-------------------+------------------->
| task_arn                                                                                | container_instance_arn | cluster_name   | desired_status | launch_type | availability_zone | capacity_provider_>
+-----------------------------------------------------------------------------------------+------------------------+----------------+----------------+-------------+-------------------+------------------->
| arn:aws:ecs:us-east-1:222222222222:task/test53-cluster/33c6b0ed0e3f4ba595e6d959f1df4b1c | <null>                 | test53-cluster | STOPPED        | FARGATE     | us-east-1a        | FARGATE           >
| arn:aws:ecs:us-east-1:222222222222:task/test53-cluster/c1afe9b34f35443e9c4e6e4b46690dd0 | <null>                 | test53-cluster | STOPPED        | FARGATE     | us-east-1a        | FARGATE           >
| arn:aws:ecs:us-east-1:222222222222:task/test53-cluster/0db42a0fa38040e18dd620aac1201ac5 | <null>                 | test53-cluster | STOPPED        | FARGATE     | us-east-1b        | FARGATE           >
| arn:aws:ecs:us-east-1:222222222222:task/test53-cluster/98e0d28ee081436eb8381f75a15eeda3 | <null>                 | test53-cluster | STOPPED        | FARGATE     | us-east-1a        | FARGATE           >
+-----------------------------------------------------------------------------------------+------------------------+----------------+----------------+-------------+-------------------+------------------->

```

**Query with `desired_status` set to `PENDING` in the where clause:**

Query: `select * from aws_ecs_task where desired_status = 'PENDING'`
Result: 
```
+----------+------------------------+--------------+----------------+-------------+-------------------+------------------------+-------------+--------------+-----------------+-----+------------+--------->
| task_arn | container_instance_arn | cluster_name | desired_status | launch_type | availability_zone | capacity_provider_name | cluster_arn | connectivity | connectivity_at | cpu | created_at | enable_e>
+----------+------------------------+--------------+----------------+-------------+-------------------+------------------------+-------------+--------------+-----------------+-----+------------+--------->
+----------+------------------------+--------------+----------------+-------------+-------------------+------------------------+-------------+--------------+-----------------+-----+------------+--------->
```

Please note that according to the [API documentation](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ListTasks.html), specifying `PENDING` as the desired status does not return any results.

```
Although you can filter results based on a desired status of PENDING, this doesn't return any results. Amazon ECS never sets the desired status of a task to that value (only a task's lastStatus may have a value of PENDING).
```

Also I observed the same behaviour using the AWS CLI command:

`aws ecs list-tasks --cluster test53-cluster`: It returns the tasks with desired status RUNNING only.
`aws ecs list-tasks --cluster test53-cluster --desired-status STOPPED`: We can list the tasks with desired status STOPPED.
`aws ecs list-tasks --cluster test53-cluster --desired-status PENDING`: It does not return any result.

Thank You!
