### ISSUE TITLE
Add `Incomplete Multipart Upload Storage Bytes` metric for AWS S3 Bucket

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-aws#1829]
**References**

https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage_lens_metrics_glossary.html
https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-lens-cloudwatch-metrics-dimensions.html#storage-lens-cloudwatch-metrics

Note: This is required to add new control `S3 Buckets with incomplete multipart upload should be reviewed'  in AWS Thrifty mod.

**Comment by cbruno10** [comment]
Are we able to get this info from the https://hub.steampipe.io/plugins/turbot/aws/tables/aws_cloudwatch_metric_data_point or https://hub.steampipe.io/plugins/turbot/aws/tables/aws_cloudwatch_metric_statistic_data_point if we were able to pass in bucket names to the quals? I know this currently doesn't work, but it seems like if that capability worked, we wouldn't necessarily need as many specific metric tables.

**Comment by ParthaI** [comment]
@cbruno10 / @khushboo9024, I attempted to create a separate table for obtaining metric statistics related to storage lenses, specifically for the "Incomplete Multipart Upload Storage Bytes" metric. Unfortunately, I encountered some issues and couldn't retrieve the data successfully. Here are the key findings:

- To gather the metric statistics for the new table, the following data is required:
  - Granularity: Daily
  - Namespace: [AWS/S3/Storage-Lens](https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-lens-cloudwatch-monitoring-cloudwatch.html#storage-lens-cloudwatch-monitoring-cloudwatch-dimensions)
  - MetricName: [IncompleteMultipartUploadStorageBytes](https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage_lens_metrics_glossary.html)
  - Dimension Name: [configuration_id, aws_account_number, aws_region, or bucket_name](https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-lens-cloudwatch-monitoring-cloudwatch.html#storage-lens-cloudwatch-monitoring-cloudwatch-dimensions)

- To obtain the metric statistics, I used the API [GetMetricStatistics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html). However, despite trying various `Dimension Name` combinations, the API didn't return any data for the "Incomplete Multipart Upload Storage Bytes" metric.

Please review these findings and let me know if there are any suggestions or if further investigation is needed. Thank you!

**Comment by cbruno10** [comment]
@ParthaI Did you try using the tables I mentioned above at all? If so, can you please share the queries you tried and the unexpected results/errors you received? We may need to create another table as well, but if we can't use the current metric tables to get the data we need, we should figure out the correct queries and/or table updates to have them work for our use cases.

**Comment by khushboo9024** [comment]
@cbruno10 I attempted to run a below query on the `aws_cloudwatch_metric_statistic_data_point` table with the namespace set to `AWS/S3/Storage-Lens` and requested data for a specific metric `ObjectCount`. However, the query did not return any data. I believe that the `aws_cloudwatch_metric_statistic_data_point` table does not provide any data for the namespace `AWS/S3/Storage-Lens`.

```
select
  jsonb_pretty(dimensions) as dimensions,
  timestamp,
  minimum
from
  aws_cloudwatch_metric_statistic_data_point
where
  namespace = 'AWS/S3/Storage-Lens'
  and metric_name = 'ObjectCount'
  and timestamp between '2023-03-6T00:00:00Z' and '2023-03-15T00:00:00Z'
  and period = 86400
  and dimensions = '[
    {"Name": "BucketName", "Value": "cis-secret"},
    {"Name": "StorageType", "Value": "StandardStorage"}
  ]'
order by
  timestamp;
  ```

**Comment by cbruno10** [comment]
@khushboo9024 Does the AWS CLI return data if you pass in the same args/params from the query above? If so, do you know what's causing the table to not return the data we'd expect?

**Comment by khushboo9024** [comment]
@cbruno10 Despite attempting the provided query with the AWS CLI, it still did not return any data.
```
aws cloudwatch get-metric-statistics --namespace AWS/S3/Storage-Lens --metric-name ObjectCount  --start-time 2023-03-6T00:00:00Z --end-time 2023-03-15T00:00:00Z  --period 86400 --dimensions '[{"Name":"BucketName","Value":"cis-secret"}, {"Name":"StorageType","Value":"StandardStorage"}]'  --statistics '["Minimum"]' 

```

**Comment by rajlearner17** [comment]
@khushboo9024 Pls give it anaother try https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-lens-cloudwatch-monitoring-cloudwatch.html

**Comment by khushboo9024** [comment]
@cody @raj I reattempted the AWS CLI commands for the `ObjectCount` metric within the `AWS/S3/Storage-Lens` namespace, this time ensuring all dimensions were correctly provided. As a result, we successfully obtained the data. However, we currently lack data for the `IncompleteMultipartUploadStorageBytes` metric, making it impossible to test at the moment. We assume that once we create incomplete multipart uploads, the data for this metric will be available."

```
aws cloudwatch get-metric-statistics --namespace "AWS/S3/Storage-Lens"  --metric-name "ObjectCount" --start-time "2023-07-26T00:00:00Z"  --end-time "2023-07-30T00:00:00Z" --period 300 --statistics "Sum" --dimensions "Name=metrics_version,Value=1.0" "Name=bucket_name,Value=cis-secret"  "Name=configuration_id,Value=test-len" "Name=storage_class,Value=STANDARD" "Name=aws_region,Value=us-east-1" "Name=record_type,Value=BUCKET"  "Name=aws_account_number,Value=123456781989" --profile aab


aws cloudwatch get-metric-statistics --namespace "AWS/S3/Storage-Lens"  --metric-name "IncompleteMPUObjectCountOlderThan7Days" --start-time "2023-07-26T00:00:00Z"  --end-time "2023-07-30T00:00:00Z" --period 300 --statistics "Sum" --dimensions "Name=metrics_version,Value=1.0" "Name=bucket_name,Value=aa-parth-test"  "Name=configuration_id,Value=test-len" "Name=storage_class,Value=STANDARD" "Name=aws_region,Value=ap-south-1" "Name=record_type,Value=BUCKET"  "Name=aws_account_number,Value=123456781989" --profile aab
```

I tested the above provided AWS CLI command, using our existing table, and it successfully returned the data we needed.

```
select
  jsonb_pretty(dimensions) as dimensions,
  timestamp,
  minimum
from
  aws_cloudwatch_metric_statistic_data_point
where
  namespace = 'AWS/S3/Storage-Lens'
  and metric_name = 'ObjectCount'
  and timestamp between '2023-07-26T00:00:00Z' and '2023-07-30T00:00:00Z'
  and period = 300
  and dimensions = '[
    {"Name": "bucket_name", "Value": "cis-secret"},
    {"Name": "storage_class", "Value": "STANDARD"},
    {"Name": "configuration_id" , "Value": "test-len"},
    {"Name": "metrics_version" , "Value": "1.0"},
    {"Name": "record_type" , "Value": "BUCKET"},
    {"Name": "aws_region" , "Value": "us-east-1"},
    {"Name": "aws_account_number" , "Value": "123456781989"}
  ]'
order by
  timestamp;
```

Note: The query mentioned above lacks the capability to include bucket names in the quals. We already have an [issue](https://github.com/turbot/steampipe-postgres-fdw/issues/328) opened. As a possible solution, we can try creating a new table dedicated to the 'IncompleteMultipartUploadStorageBytes' metric, similar to the one we have for the `aws_vpc_nat_gateway_metric_bytes_out_to_destination` metric associated with NAT gateways.

@partha can try once again with all the dimensions passed in the API `GetMetricStatistics`.

**Comment by cody** [comment]
> @cody @raj I reattempted the AWS CLI commands for the `ObjectCount` metric within the `AWS/S3/Storage-Lens` namespace, this time ensuring all dimensions were correctly provided. As a result, we successfully obtained the data. However, we currently lack data for the `IncompleteMultipartUploadStorageBytes` metric, making it impossible to test at the moment. We assume that once we create incomplete multipart uploads, the data for this metric will be available."
> 
> ```
> aws cloudwatch get-metric-statistics --namespace "AWS/S3/Storage-Lens"  --metric-name "ObjectCount" --start-time "2023-07-26T00:00:00Z"  --end-time "2023-07-30T00:00:00Z" --period 300 --statistics "Sum" --dimensions "Name=metrics_version,Value=1.0" "Name=bucket_name,Value=cis-secret"  "Name=configuration_id,Value=test-len" "Name=storage_class,Value=STANDARD" "Name=aws_region,Value=us-east-1" "Name=record_type,Value=BUCKET"  "Name=aws_account_number,Value=123456781989" --profile aab
> 
> 
> aws cloudwatch get-metric-statistics --namespace "AWS/S3/Storage-Lens"  --metric-name "IncompleteMPUObjectCountOlderThan7Days" --start-time "2023-07-26T00:00:00Z"  --end-time "2023-07-30T00:00:00Z" --period 300 --statistics "Sum" --dimensions "Name=metrics_version,Value=1.0" "Name=bucket_name,Value=aa-parth-test"  "Name=configuration_id,Value=test-len" "Name=storage_class,Value=STANDARD" "Name=aws_region,Value=ap-south-1" "Name=record_type,Value=BUCKET"  "Name=aws_account_number,Value=123456781989" --profile aab
> ```
> 
> I tested the above provided AWS CLI command, using our existing table, and it successfully returned the data we needed.
> 
> ```
> select
>   jsonb_pretty(dimensions) as dimensions,
>   timestamp,
>   minimum
> from
>   aws_cloudwatch_metric_statistic_data_point
> where
>   namespace = 'AWS/S3/Storage-Lens'
>   and metric_name = 'ObjectCount'
>   and timestamp between '2023-07-26T00:00:00Z' and '2023-07-30T00:00:00Z'
>   and period = 300
>   and dimensions = '[
>     {"Name": "bucket_name", "Value": "cis-secret"},
>     {"Name": "storage_class", "Value": "STANDARD"},
>     {"Name": "configuration_id" , "Value": "test-len"},
>     {"Name": "metrics_version" , "Value": "1.0"},
>     {"Name": "record_type" , "Value": "BUCKET"},
>     {"Name": "aws_region" , "Value": "us-east-1"},
>     {"Name": "aws_account_number" , "Value": "123456781989"}
>   ]'
> order by
>   timestamp;
> ```
> 
> Note: The query mentioned above lacks the capability to include bucket names in the quals. We already have an [issue](https://github.com/turbot/steampipe-postgres-fdw/issues/328) opened. As a possible solution, we can try creating a new table dedicated to the 'IncompleteMultipartUploadStorageBytes' metric, similar to the one we have for the `aws_vpc_nat_gateway_metric_bytes_out_to_destination` metric associated with NAT gateways.
> 
> @partha can try once again with all the dimensions passed in the API `GetMetricStatistics`.

Hey, there! @‘d the wrong Cody on this one—wanted to let you know just in case it mattered. Thanks!

**Comment by khushboo9024** [comment]
> > @cody @raj I reattempted the AWS CLI commands for the `ObjectCount` metric within the `AWS/S3/Storage-Lens` namespace, this time ensuring all dimensions were correctly provided. As a result, we successfully obtained the data. However, we currently lack data for the `IncompleteMultipartUploadStorageBytes` metric, making it impossible to test at the moment. We assume that once we create incomplete multipart uploads, the data for this metric will be available."
> > ```
> > aws cloudwatch get-metric-statistics --namespace "AWS/S3/Storage-Lens"  --metric-name "ObjectCount" --start-time "2023-07-26T00:00:00Z"  --end-time "2023-07-30T00:00:00Z" --period 300 --statistics "Sum" --dimensions "Name=metrics_version,Value=1.0" "Name=bucket_name,Value=cis-secret"  "Name=configuration_id,Value=test-len" "Name=storage_class,Value=STANDARD" "Name=aws_region,Value=us-east-1" "Name=record_type,Value=BUCKET"  "Name=aws_account_number,Value=123456781989" --profile aab
> > 
> > 
> > aws cloudwatch get-metric-statistics --namespace "AWS/S3/Storage-Lens"  --metric-name "IncompleteMPUObjectCountOlderThan7Days" --start-time "2023-07-26T00:00:00Z"  --end-time "2023-07-30T00:00:00Z" --period 300 --statistics "Sum" --dimensions "Name=metrics_version,Value=1.0" "Name=bucket_name,Value=aa-parth-test"  "Name=configuration_id,Value=test-len" "Name=storage_class,Value=STANDARD" "Name=aws_region,Value=ap-south-1" "Name=record_type,Value=BUCKET"  "Name=aws_account_number,Value=123456781989" --profile aab
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tested the above provided AWS CLI command, using our existing table, and it successfully returned the data we needed.
> > ```
> > select
> >   jsonb_pretty(dimensions) as dimensions,
> >   timestamp,
> >   minimum
> > from
> >   aws_cloudwatch_metric_statistic_data_point
> > where
> >   namespace = 'AWS/S3/Storage-Lens'
> >   and metric_name = 'ObjectCount'
> >   and timestamp between '2023-07-26T00:00:00Z' and '2023-07-30T00:00:00Z'
> >   and period = 300
> >   and dimensions = '[
> >     {"Name": "bucket_name", "Value": "cis-secret"},
> >     {"Name": "storage_class", "Value": "STANDARD"},
> >     {"Name": "configuration_id" , "Value": "test-len"},
> >     {"Name": "metrics_version" , "Value": "1.0"},
> >     {"Name": "record_type" , "Value": "BUCKET"},
> >     {"Name": "aws_region" , "Value": "us-east-1"},
> >     {"Name": "aws_account_number" , "Value": "123456781989"}
> >   ]'
> > order by
> >   timestamp;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Note: The query mentioned above lacks the capability to include bucket names in the quals. We already have an [issue](https://github.com/turbot/steampipe-postgres-fdw/issues/328) opened. As a possible solution, we can try creating a new table dedicated to the 'IncompleteMultipartUploadStorageBytes' metric, similar to the one we have for the `aws_vpc_nat_gateway_metric_bytes_out_to_destination` metric associated with NAT gateways.
> > @partha can try once again with all the dimensions passed in the API `GetMetricStatistics`.
> 
> Hey, there! @‘d the wrong Cody on this one—wanted to let you know just in case it mattered. Thanks!

@cody Thank you for bringing this to our attention. It appears there was a mistake in the tagging.
