### ISSUE TITLE
Add better error message when AWS creds resolver fails 

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-aws#1846]
**Is your feature request related to a problem? Please describe.**
When I pass in missing credentials, e.g., specify a profile in `aws.spc` that doesn't exist in my AWS config or credentials file, the plugin returns an error:
```
Error: rpc error: code = DeadlineExceeded desc = operation error S3: ListBuckets, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline exceeded (SQLSTATE HV000)
```

This is most likely due to the way AWS SDK Go v2 resolves creds, https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/#specifying-credentials, and doesn't error when a missing profile is provided to it when setting up the shared config.

**Describe the solution you'd like**
The plugin should provide a better error message to point me in the right direction that my creds are missing or not specified

**Describe alternatives you've considered**
n/A

**Additional context**

**Comment by misraved** [comment]
Reopening the issue to figure out the scope of the changes made in https://github.com/turbot/steampipe-plugin-aws/pull/1873
