### ISSUE TITLE
Add tables `aws_cognito_user_pool` and `aws_cognito_identity_provider`

### ISSUE THREAD

**Issue by pdecat** [turbot/steampipe-plugin-aws#1850]
**References**

Terraform provider resources:
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_identity_provider

**Comment by rajlearner17** [comment]
@pdecat Thanks for raising the issues and your interest in working on them. [Slack Reference](https://steampipe.slack.com/archives/C044P668806/p1689858106401739)

I just assigned you Looking forward to seeing PRs 👍 
[Doc](https://steampipe.io/docs/develop/overview)

**Comment by pdecat** [comment]
Submitted https://github.com/turbot/steampipe-plugin-aws/pull/1854
