### ISSUE TITLE
Remove 'security_groups' column from 'aws_ec2_network_load_balancer' table

### ISSUE THREAD

**Issue by tinder-tder** [turbot/steampipe-plugin-aws#1871]
**Describe the bug**
AWS NLBs do not use security group associations so that column is always empty.

NLB table and docs look like they were forked from the alb table

**Steampipe version (`steampipe -v`)**
v0.20.9

**Plugin version (`steampipe plugin list`)**
latest

**Additional context**
https://github.com/turbot/steampipe-plugin-aws/pull/1869

is this all that is needed for the pr? (I havent done any code submissions here)
```
diff --git a/aws/table_aws_ec2_network_load_balancer.go b/aws/table_aws_ec2_network_load_balancer.go
index e07ca75..ebf655b 100644
--- a/aws/table_aws_ec2_network_load_balancer.go
+++ b/aws/table_aws_ec2_network_load_balancer.go
@@ -111,11 +111,6 @@ func tableAwsEc2NetworkLoadBalancer(_ context.Context) *plugin.Table {
                                Description: "The subnets for the load balancer",
                                Type:        proto.ColumnType_JSON,
                        },
-                       {
-                               Name:        "security_groups",
-                               Description: "The IDs of the security groups for the load balancer",
-                               Type:        proto.ColumnType_JSON,
-                       },
                        {
                                Name:        "load_balancer_attributes",
                                Description: "The AWS account ID of the image owner",
```

**Comment by misraved** [comment]
The changes that you have mentioned in the issue body look great, you can definitely proceed with a PR 👍.

Are there any other columns that should be removed as well?

**Comment by rajlearner17** [comment]
@tinder-tder @misraved  Recently, AWS announced the support for the same, probably while we were working on it. Closing this as already we released. 

I have raised the new issue for the same; feel free to comment, https://github.com/turbot/steampipe-plugin-aws/issues/1875
