### ISSUE TITLE
Add/Update support for AWS GuardDuty

### ISSUE THREAD

**Issue by paulsewardasc** [turbot/steampipe-plugin-aws#1878]
**Is your feature request related to a problem? Please describe.**
select status as detector_status, jsonb_pretty(data_sources) from aws_guardduty_detector

does not show the following data_sources

EBS_MALWARE_PROTECTION
RDS_LOGIN_EVENTS
EKS_RUNTIME_MONITORING
LAMBDA_NETWORK_LOGS

This is for plugin hub.steampipe.io/plugins/turbot/aws v0.115.0

**Describe the solution you'd like**
Could these be included in the data_sources, the are showing in aws-cli/2.13.10

**Describe alternatives you've considered**
I can use AWS CLI to view them.

**Comment by cbruno10** [comment]
I think the AWS plugin probably needs an update to the `guardduty` module, we’re on [v1.17.0](https://github.com/turbot/steampipe-plugin-aws/blob/main/go.mod#L63), but I can see in [v1.18.0](https://github.com/aws/aws-sdk-go-v2/blob/main/CHANGELOG.md#module-highlights-101) they added support for new features (which may have the info you’re seeing in the CLI)

The latest version is v1.26.0, so there are probably other helpful updates as well.

**Comment by paulsewardasc** [comment]
Any update on this?

**Comment by rajlearner17** [comment]
@paulsewardasc,Thanks for reminding.We have this in our TO DO backlog. We will prioritise this in coming days.

**Comment by bigdatasourav** [comment]
I have raised a [PR](https://github.com/turbot/steampipe-plugin-aws/pull/1958) to add the `features` column in the `aws_guardduty_detector` table.
