### ISSUE TITLE
Add table aws_elastic_beanstalk_configuration_settings

### ISSUE THREAD

**Issue by shaicoleman** [turbot/steampipe-plugin-aws#1906]
`aws elasticbeanstalk describe-configuration-settings --application-name 'myapp' --environment-name 'myappenv'`

https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DescribeConfigurationSettings.html

Specifically, I would like to get environment variables for the Elastic Beanstalk environments

**Comment by misraved** [comment]
Welcome to Steampipe @shaicoleman  and thanks for raising the table request 👍 !!
