### ISSUE TITLE
Resource Types in AWS tables

### ISSUE THREAD

**Issue by Lingom-R** [turbot/steampipe-plugin-aws#1907]
Hi,
I would like to know if there is any identifier that represents resource types in AWS tables. If not is there any way to bring the resource type as a column in all the aws tables?

E.g. The table "aws_iam_user" lists the resources available in the IAM services from the integrated account. But don't see any identifier that says which resource type that resource belongs to.

Note: I prefer not to get the resource type from the table name.

Any help would be appreciated.

**Comment by cbruno10** [comment]
Hi @Lingom-R , I think the best way to know what resource type a table returns is typically to look at its `arn` column. Not all tables have it, but I believe most do, and it's probably the most consistent way (in Steampipe and for AWS resources in general) on being able to tell which resources are being returned.

**Comment by misraved** [comment]
Hi @Lingom-R, welcome to Steampipe, and thanks for opening the issue. Just as @cbruno10 mentioned, the resource type can be figured out by looking at the `arn` column 👍.

We are closing this issue for now, but please feel free to reopen the issue in case you have more questions 👍.
