### ISSUE TITLE
Please make GH Releases for each new version

### ISSUE THREAD

**Issue by KTamas** [turbot/steampipe-plugin-aws#1911]
GH releases gives you an RSS feed which makes it easy to keep up with new versions with an RSS reader. The Tags page, unfortunately, does not. I already keep track of several projects like this and it'd be great if I could add this plugin to that list. I bet it'd be useful for other people as well.

**Comment by cbruno10** [comment]
Hi @KTamas , does a link like https://github.com/turbot/steampipe-plugin-aws/tags.atom provide you the feed you're looking for?

**Comment by KTamas** [comment]
That doesn't give me a changelog but yes, it works, thanks.

**Comment by cbruno10** [comment]
@KTamas Thanks for confirming that works for you!

We don't have any plans to create releases at the moment, but if you have any other questions please let us know.
