### ISSUE TITLE
The table aws_dynamodb_backup returns error BackupNotFoundException

### ISSUE THREAD

**Issue by ParthaI** [turbot/steampipe-plugin-aws#1913]
**Describe the bug**
When running the get query for the table `aws_dynamodb_backup` it returns the error.

```
Getting Error while doing get call:
select jsonb_pretty(_ctx),* from aws_dynamodb_backup where arn= 'arn:aws:dynamodb:us-east-1:xxxxxxxxxxx:table/turbottest89794/backup/01681997703770-aa93528e'

Error: 17 list calls returned errors:
 operation error DynamoDB: DescribeBackup, https response error StatusCode: 400, RequestID: 51IL6KPIANM80GN11PLVAJQCG3VV4KQNSO5AEMVJF66Q9ASUAAJG, BackupNotFoundException: Backup not found: arn:aws:dynamodb:us-east-1:xxxxxxxxxxxx:table/turbottest89794/backup/01681997703770-aa93528e
```

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Run the query `select jsonb_pretty(_ctx),* from aws_dynamodb_backup where arn= 'arn:aws:dynamodb:us-east-1:xxxxxxxxxxx:table/turbottest89794/backup/01681997703770-aa93528e'`

**Expected behavior**
We should not get any error if we will run the query.

**Additional context**

**Comment by misraved** [comment]
Fixed in https://github.com/turbot/steampipe-plugin-aws/pull/1914
