### ISSUE TITLE
Steampipe Error: 'Access Denied' when querying 's3 list buckets' in a specific region.

### ISSUE THREAD

**Issue by karan-mungra** [turbot/steampipe-plugin-aws#1952]
**Bug Description:**
When performing a 's3 list buckets' query using an IAM role with full S3 access and specifying 'requestedRegion' as 'ap-south-1,' the AWS CLI returns the expected output. However, the Steampipe CLI returns an 'AccessDenied' error. This issue occurs despite AWS functioning correctly, as evidenced by the AWS CLI's proper behavior.

**Output:**
```
steampipe query "select * from aws_s3_bucket"
Error: Operation Error S3: ListBuckets
HTTPS response error StatusCode: 403
RequestID: *******
HostID: **************
API Error: AccessDenied - Access Denied
(SQLSTATE HV000)
```

**Steampipe Version:** *Steampipe v0.21.1*

**Steps to Reproduce the Bug:**

1. **Create an IAM Role with a Specific S3 Policy:**
   - Access the AWS Identity and Access Management (IAM) console.
   - Create a new IAM role for use by an EC2 instance.
   - Attach a custom policy to this role with the following configuration (as previously described).

2. **Attach the IAM Role to an EC2 Instance:**
   - Launch a new EC2 instance or choose an existing one.
   - During instance creation or modification, assign the IAM role created in step 1 to the instance. Ensure that the EC2 instance has the necessary permissions to assume this role.

3. **Use AWS CLI to List S3 Buckets:**
   - Log in to the EC2 instance via SSH or your preferred method.
   - Verify the AWS CLI is installed on the instance (as previously mentioned).
   - Execute the following command to list S3 buckets:

   ```
   aws s3 ls
   ```

   - This command should return the expected output, displaying a list of S3 buckets without errors.

4. **Use Steampipe CLI to Execute the Query:**
   - On the same EC2 instance, use the Steampipe CLI to run the query mentioned previously.
   - Execute the query:

   ```
   steampipe query "select * from aws_s3_bucket"
   ```

   - Unfortunately, this command results in an 'Access Denied' error, despite the AWS CLI providing the correct output in the previous step.

**Comment by karan-mungra** [comment]
Hello @cbruno10, we ran the following queries:
(For 'us-east-1' runs successfully and fails for 'ap-south-1')
`select name from aws_s3_bucket`
`select name aws_s3_bucket where region = 'ap-south-1'`
`select name aws_s3_bucket where region = 'us-east-1'`
`select name, description from aws_iam_role`
(Ran successfully for both the regions)
`select group_name from aws_vpc_security_group`
`select instance_id from aws_ec2_instance`

And we found something interesting,
- In the 'us-east-1' region, the steampipe queries run successfully, but with the region as 'ap-south-1' the queries execution fails.
- We also noticed that for global resources like s3, iam steampipe run queries successfully for the 'us-east-1' region and not for the 'ap-south-1'.
- Whereas for resources like ec2, vpc which are local to region, steampipe run queries successfully for both the regions.
- We think the issue might be that steampipe allows execution for such queries related to global resources as mention previously in the 'us-east-1' region only, due to which steampipe is unable to run such queries in the 'ap-south-1' region.
- Can you please verify our assumption. And help us to know if there is any way around with this setting and how to use other regions like 'ap-south-1' for global resources.
- Also, `aws.spc` is the same as default generated by the steampipe, we have not updated it. Hence I am not sharing it here.

**Comment by rajlearner17** [comment]
CC @ParthaI

**Comment by ParthaI** [comment]
@karan-mungra, I apologize for not communicating earlier about this issue.

- It's possible that this situation is related to a bucket access policy that's been applied to a specific bucket, potentially resulting in an `Access Denied` error. Usually, Steampipe doesn't manage the `Access Denied` error. 
- Nevertheless, Steampipe offers the capability to handle API errors. This can be done by setting up the `ignore_error_codes` section in your connection configuration file located at `~/.steampipe/config/aws.spc`.
- For more detailed information, you can refer to the Steampipe documentation: [Steampipe AWS Plugin Configuration](https://hub.steampipe.io/plugins/turbot/aws#configuration).

Could you please try this solution and let us know your feedback? It would be greatly appreciated.

Thank you!

**Comment by ParthaI** [comment]
@karan-mungra, Thank you for your quick response.
We are closing this issue as it seems to be resolved. Please feel free to reopen the issue if you encounter any further issues.

Thanks!
