### ISSUE TITLE
Want to have record set limit column in aws_route53_zone table

### ISSUE THREAD

**Issue by keyolk** [turbot/steampipe-plugin-aws#1970]
**Is your feature request related to a problem? Please describe.**
I'm using the steampipe as Grafana datasource for alerting.
Would be helpful if it had the column.

**Describe the solution you'd like**

I wrote simple PR here
https://github.com/turbot/steampipe-plugin-aws/pull/1969

**Describe alternatives you've considered**

**Additional context**

**Comment by ParthaI** [comment]
Addressed in this PR https://github.com/turbot/steampipe-plugin-aws/pull/1969
