### ISSUE TITLE
Get available regions from control tower instead of ec2 describe regions when using it

### ISSUE THREAD

**Issue by CiolFr** [turbot/steampipe-plugin-aws#2004]
**Is your feature request related to a problem? Please describe.**
I'm using control tower and the landing zone feature that allow me to deactivate some regions even the opt-in-not-required one's.
Unfortunately the actual method to get the available region is through the ec2 describe-regions api that does not match control tower configuration. So some when using compliance mod some illegitimate error raise (Ex: aws config or security hub not being activated)

**Describe the solution you'd like**
The controltower get-landing-zone return a list of allowed region, example :
`"governedRegions": [
                "eu-west-1",
                "us-east-1"
            ],
`
Could we imagine a config that specify that we are using control tower and in this case use it's api instead of of the ec2 one.

**Comment by ParthaI** [comment]
@CiolFr, Thank you for taking the time to report this issue. We appreciate your contribution to the project. We will take a look into it. 👍
