### ISSUE TITLE
Add table aws_iam_user_ssh_key

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-aws#2006]
**References**
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user_ssh_key

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2@v0.24.0/service/iam#ListSSHPublicKeysOutput

**Comment by rajlearner17** [comment]
https://github.com/turbot/steampipe-plugin-aws/pull/1364
