### ISSUE TITLE
The aws_rds_db_instance.processor_features column returns null value

### ISSUE THREAD

**Issue by toddwh50** [turbot/steampipe-plugin-aws#2018]
**Describe the bug**
Querying RDS instance details, the processor_features column returned by aws_rds_db_instance queries returns only null values.

**Steampipe version (`steampipe -v`)**
v0.21.2

**Plugin version (`steampipe plugin list`)**
v0.123.0

**To reproduce**
Query rds instances with the processor_features column and see is null:
```
> select title, engine, class, processor_features from aws_rds_db_instance;
+------------+------------+----------------+--------------------+
| title      | engine     | class          | processor_features |
+------------+------------+----------------+--------------------+
| ora-a-db01 | oracle-ee  | db.r6i.4xlarge | <null>             |
| ora-a-db02 | oracle-se2 | db.m5.xlarge   | <null>             |
+------------+------------+----------------+--------------------+
```

**Expected behavior**
The processor_features should return json containing the number of cores and threads per core.

Per docs (.instpect aws_rds_db_instance):

> The number of CPU cores and the number of threads per core for the DB instance class of the DB instance.

**Comment by ParthaI** [comment]
Thank you, @toddwh50, for bringing the issue to our attention. We will investigate why the column (`processor_features`) consistently returns as null and take the necessary steps to address it.

**Comment by ParthaI** [comment]
Hi @toddwh50, I was digging into the above issue. I am sharing a few key points from my observations; please have a look.

- The column `processor_features` will have data if the RDS DB Instance engine is of type `oracle`
- Could you please confirm you are still getting the null value for the Oracle DB instance classes?
- In this table, we depend on the [DescribeDBInstances](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBInstances.html) API to populate the `processor_features` column value, as per the [AWS documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html#USER_ConfigureProcessor):
  - If you call `DescribeDBInstances`, `ProcessorFeature` returns non-null values only if the following conditions are met:
    - You are accessing an Oracle DB instance.
    - Your Oracle DB instance class supports configuring the number of CPU cores and threads per core.
    - The current number of CPU cores and threads is set to a non-default value.
 - Additionally, you can view the valid processor values for a particular instance class by calling the `DescribeOrderableDBInstanceOptions` action and specifying the instance class for the `DBInstanceClass` parameter.
 - Relevant AWS CLI command for valid processor values for a particular instance class `aws rds describe-orderable-db-instance-options --engine mysql --db-instance-class db.t3.2xlarge`.
 - I got the `processor_features` column value by querying this table.

```
> select title, engine, class, processor_features from aws_rds_db_instance;
+-----------------+-----------+-------------+--------------------------------------------------------------------------+
| title           | engine    | class       | processor_features                                                       |
+-----------------+-----------+-------------+--------------------------------------------------------------------------+
| database-1      | oracle-ee | db.m5.large | [{"Name":"coreCount","Value":"1"},{"Name":"threadsPerCore","Value":"2"}] |
| turbottest19059 | mysql     | db.m5.large | <null>                                                                   |
+-----------------+-----------+-------------+--------------------------------------------------------------------------+
```

Please feel free to inform me if I have a clear understanding of the issue, or if you need any further assistance.

Thank you!

**Comment by ParthaI** [comment]
Hello @toddwh50, I trust you're doing well. I wanted to follow up on the above comment and kindly ask if you had an opportunity to review it. Your insights are highly appreciated, and your feedback is invaluable to us. Thank you!

**Comment by toddwh50** [comment]
Hi @ParthaI, thanks for the response.

With the criteria you describe, I think the problem might be that we are using the default values for cores/memory in our instances. But, in your example, 1 core and 2 threadsPerCore are the defaults, so I'm not sure why it is showing for you but not for me.

It doesn't look like there is currently a way to query the DescribeOrderableDBInstanceOptions in the aws plugin for steampipe. Am I missing it?

I am trying to query vCPUs per instance to better verify our Oracle license compliance, but don't see a way to do it if the ProcessorFeatures truly are returned only when they are non-default values.

**Comment by ParthaI** [comment]
Hello @toddwh50, Appreciate your quick response!
> With the criteria you describe, I think the problem might be that we are using the default values for cores/memory in our instances. But, in your example, 1 core and 2 threadsPerCore are the defaults, so I'm not sure why it is showing for you but not for me.

In this table we are using [DescribeDBInstances](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBInstances.html) API to populate the processor_features column value. This API returns the value if the configuration meets the following criteria([Please take a look at the point number `#3`](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ProcessorFeature.html)).
- You are accessing an Oracle DB instance.
- Your Oracle DB instance class supports configuring the number of CPU cores and threads per core.
- **_The current number CPU cores and threads is set to a non-default value._**

Could you please confirm/share the output of the AWS CLI commands `aws rds describe-db-instances --query "DBInstances[].{DBInstanceIdentifier:DBInstanceIdentifier,DBInstanceClass:DBInstanceClass,Engine:Engine,ProcessorFeatures:ProcessorFeatures}"` if you are able to see the `ProcessorFeatures` value for the instance you are looking for?

I am not able to get the default `ProcessorFeatures` value for the DB instance of engine type `Oracle`. However I am able to get the `ProcessorFeatures` value if I am overriding the default values.

---

> It doesn't look like there is currently a way to query the DescribeOrderableDBInstanceOptions in the aws plugin for steampipe. Am I missing it?

Yes, the table does not use the `DescribeOrderableDBInstanceOptions` API call to populate any of the column values.

---

I've submitted a [pull request (PR)](https://github.com/turbot/steampipe-plugin-aws/pull/2028) that updates the `processor_features` column. It now populates values for both default and non-default scenarios. If an RDS DB Instance has a non-default `ProcessorFeatures` value, it will be displayed; otherwise, it will fall back to the default value based on the engine type, storage type, DB instance class, engine version, and availability zone.

Your feedback on this improvement is highly valued. Feel free to test it in the PR branch `issue-2018` and share your thoughts with us.

Steps to validate the code changes:

- git clone https://github.com/turbot/steampipe-plugin-aws.git
- cd steampipe-plugin-aws
- git checkout `issue-2018`
- make
- Run the query `select db_instance_identifier, engine,engine_version, availability_zone, class, processor_features from aws_rds_db_instance;`

Query result with a default `ProcessorFeatures` setup for an RDS DB Instance.

```
> select db_instance_identifier, engine,engine_version, availability_zone, class, processor_features from aws_rds_db_instance;
+------------------------+-----------+------------------------------------+-------------------+--------------+--------------------------------------------------------------------------+
| db_instance_identifier | engine    | engine_version                     | availability_zone | class        | processor_features                                                       |
+------------------------+-----------+------------------------------------+-------------------+--------------+--------------------------------------------------------------------------+
| database-2             | oracle-ee | 19.0.0.0.ru-2023-10.rur-2023-10.r1 | us-east-1b        | db.m5d.large | [{"Name":"threadsPerCore","Value":"2"},{"Name":"coreCount","Value":"1"}] |
| database-1             | mysql     | 8.0.33                             | us-east-1b        | db.t3.micro  | <null>                                                                   |
+------------------------+-----------+------------------------------------+-------------------+--------------+--------------------------------------------------------------------------+
```

**_Note: The `ProcessorFeatures` details for an RDS DB instance will not be available if the engine type does not support this feature._**

Please let us know if you need any further assistance.

Thanks!

**Comment by toddwh50** [comment]
Results for the "issue-2018" change:
```
> select engine,engine_version, availability_zone, class, processor_features from vir.aws_rds_db_instance where engine like 'ora%';
+------------+------------------------------------+-------------------+----------------+--------------------------------------------------------------------------+
| engine     | engine_version                     | availability_zone | class          | processor_features                                                       |
+------------+------------------------------------+-------------------+----------------+--------------------------------------------------------------------------+
| oracle-se2 | 19.0.0.0.ru-2023-07.rur-2023-07.r1 | eu-west-2b        | db.t3.xlarge   | <null>                                                                   |
| oracle-se2 | 19.0.0.0.ru-2023-07.rur-2023-07.r1 | eu-west-2a        | db.t3.xlarge   | <null>                                                                   |
| oracle-se2 | 19.0.0.0.ru-2023-10.rur-2023-10.r1 | eu-west-2a        | db.r6i.2xlarge | [{"Name":"coreCount","Value":"4"},{"Name":"threadsPerCore","Value":"2"}] |
| oracle-se2 | 19.0.0.0.ru-2023-07.rur-2023-07.r1 | eu-west-2a        | db.t3.xlarge   | <null>                                                                   |
| oracle-se2 | 19.0.0.0.ru-2023-07.rur-2023-07.r1 | eu-west-2a        | db.r5.xlarge   | [{"Name":"coreCount","Value":"2"},{"Name":"threadsPerCore","Value":"2"}] |
| oracle-se2 | 19.0.0.0.ru-2023-07.rur-2023-07.r1 | eu-west-2a        | db.t3.xlarge   | <null>                                                                   |
| oracle-se2 | 19.0.0.0.ru-2023-10.rur-2023-10.r1 | eu-west-1b        | db.r6i.2xlarge | [{"Name":"coreCount","Value":"4"},{"Name":"threadsPerCore","Value":"2"}] |
+------------+------------------------------------+-------------------+----------------+--------------------------------------------------------------------------+
```

It seems to pull the features for the higher instance classes, not for the t3s.

**Comment by ParthaI** [comment]
Hello, @toddwh50. We appreciate your feedback regarding the code changes.

I've tested it myself by making the `DescribeOrderableDBInstanceOptions` API call with the necessary parameters. It appears that the default value for `ProcessorFeatures` is not accessible in the specified region.

It's worth noting that the AWS CLI is exhibiting the same behavior as Steampipe.

**CLI command:**
`aws rds describe-orderable-db-instance-options --engine oracle-se2 --db-instance-class db.t3.xlarge --availability-zone-group eu-west-2 --engine-version 19.0.0.0.ru-2023-07.rur-2023-07.r1 --region eu-west-2`

**_The API call doesn't return `ProcessorFeatures` information if the engine does not support it._**

**Result:** 

```
[
    {
        "Engine": "oracle-se2",
        "EngineVersion": "19.0.0.0.ru-2023-07.rur-2023-07.r1",
        "DBInstanceClass": "db.t3.xlarge",
        "AvailabilityZones": [
            {
                "Name": "eu-west-2a"
            },
            {
                "Name": "eu-west-2b"
            },
            {
                "Name": "eu-west-2c"
            }
        ],
        "StorageType": "gp2",
        "AvailableProcessorFeatures": []
    },
    {
        "Engine": "oracle-se2",
        "EngineVersion": "19.0.0.0.ru-2023-07.rur-2023-07.r1",
        "DBInstanceClass": "db.t3.xlarge",
        "AvailabilityZones": [
            {
                "Name": "eu-west-2a"
            },
            {
                "Name": "eu-west-2b"
            },
            {
                "Name": "eu-west-2c"
            }
        ],
        "StorageType": "gp3",
        "AvailableProcessorFeatures": []
    },
    {
        "Engine": "oracle-se2",
        "EngineVersion": "19.0.0.0.ru-2023-07.rur-2023-07.r1",
        "DBInstanceClass": "db.t3.xlarge",
        "AvailabilityZones": [
            {
                "Name": "eu-west-2a"
            },
            {
                "Name": "eu-west-2b"
            },
            {
                "Name": "eu-west-2c"
            }
        ],
        "StorageType": "io1",
        "AvailableProcessorFeatures": []
    },
    {
        "Engine": "oracle-se2",
        "EngineVersion": "19.0.0.0.ru-2023-07.rur-2023-07.r1",
        "DBInstanceClass": "db.t3.xlarge",
        "AvailabilityZones": [
            {
                "Name": "eu-west-2a"
            },
            {
                "Name": "eu-west-2b"
            },
            {
                "Name": "eu-west-2c"
            }
        ],
        "StorageType": "standard",
        "AvailableProcessorFeatures": []
    },
    {
        "Engine": "oracle-se2",
        "EngineVersion": "19.0.0.0.ru-2023-07.rur-2023-07.r1",
        "DBInstanceClass": "db.t3.xlarge",
        "AvailabilityZones": [
            {
                "Name": "eu-west-2a"
            },
            {
                "Name": "eu-west-2b"
            },
            {
                "Name": "eu-west-2c"
            }
        ],
        "StorageType": "gp2",
        "AvailableProcessorFeatures": []
    },
    {
        "Engine": "oracle-se2",
        "EngineVersion": "19.0.0.0.ru-2023-07.rur-2023-07.r1",
        "DBInstanceClass": "db.t3.xlarge",
        "AvailabilityZones": [
            {
                "Name": "eu-west-2a"
            },
            {
                "Name": "eu-west-2b"
            },
            {
                "Name": "eu-west-2c"
            }
        ],
        "StorageType": "gp3",
        "AvailableProcessorFeatures": []
    },
    {
        "Engine": "oracle-se2",
        "EngineVersion": "19.0.0.0.ru-2023-07.rur-2023-07.r1",
        "DBInstanceClass": "db.t3.xlarge",
        "AvailabilityZones": [
            {
                "Name": "eu-west-2a"
            },
            {
                "Name": "eu-west-2b"
            },
            {
                "Name": "eu-west-2c"
            }
        ],
        "StorageType": "io1",
        "AvailableProcessorFeatures": []
    },
    {
        "Engine": "oracle-se2",
        "EngineVersion": "19.0.0.0.ru-2023-07.rur-2023-07.r1",
        "DBInstanceClass": "db.t3.xlarge",
        "AvailabilityZones": [
            {
                "Name": "eu-west-2a"
            },
            {
                "Name": "eu-west-2b"
            },
            {
                "Name": "eu-west-2c"
            }
        ],
        "StorageType": "standard",
        "AvailableProcessorFeatures": []
    }
]

```

Thanks!

**Comment by toddwh50** [comment]
Interesting, thanks!  I'll report the inconsistency to AWS.
