### ISSUE TITLE
Support `tags` for `aws_backup_vault` and `aws_backup_recovery_point`

### ISSUE THREAD

**Issue by Veetaha** [turbot/steampipe-plugin-aws#2031]
**Is your feature request related to a problem? Please describe.**
I would like to know the tags for AWS Backup vaults and recovery points to implement filtering them by tags in my automation.

**Describe the solution you'd like**
The tables `aws_backup_vault` and `aws_backup_recovery_point` should both contain a map of `tags`.
This should be easy to implement for AWS Backup vaults, but it's not that straightforward for AWS Backup RPs. The problem with recovery points is that not all kinds of RPs are supported by the native AWS Backup `ListTags` API ([docs](https://docs.aws.amazon.com/aws-backup/latest/devguide/API_ListTags.html)):
> ListTags only works for resource types that support full AWS Backup management of their backups. Those resource types are listed in the "Full AWS Backup management" section of the [Feature availability by resource](https://docs.aws.amazon.com/aws-backup/latest/devguide/whatisbackup.html#features-by-resource) table.

For those kinds of AWS Backup RPs that aren't marked as "Full AWS Backup management" the plugin should reach out to the service-specific implementation of the RP. For example, the AWS Backup RP ID for a backup of an EC2 instance is the ARN of an EC2 AMI, and the RP ID of the EBS volume is the ARN of the EBS snapshot. So the `tags` column for such kinds of RPs should use EC2's `DescribeTags` API, etc.

**Comment by ParthaI** [comment]
Hi @Veetaha, Thank you for bringing the issue to our attention and for providing such a comprehensive description.

- Regarding the changes made in the [PR](https://github.com/turbot/steampipe-plugin-aws/pull/2033), I have introduced a new column named `tags` in the `aws_backup_vault` table, while no alterations have been made to the `aws_backup_recovery_point` table.

- As per the established table development standards:
  - Each table should encompass details pertinent to its specific resource type.
  - Given that the `recovery_point_arn` column can represent ARNs for various resource types (e.g., EC2, EBS, S3, etc.) as outlined [here](https://docs.aws.amazon.com/aws-backup/latest/devguide/whatisbackup.html#features-by-resource), it may not be ideal for including the `tags` column in this table and populating the values based on the resource type.

- I believe we can attain our objective within the current plugin version. We can craft a query to retrieve associated tags for a resource by incorporating a switch case that considers the `resource_type` column in the `aws_backup_recovery_point` table.

Here is a sample query that is returning the result as expected:

**Query:**

```sql
SELECT
  r.backup_vault_name as backup_vault_name,
  r.recovery_point_arn as recovery_point_arn,
  r.resource_type as resource_type,
  CASE
    WHEN r.resource_type = 'EBS' THEN (
      SELECT tags FROM aws_ebs_snapshot WHERE arn = CONCAT(
        (string_to_array(r.recovery_point_arn, '::'))[1],
        ':',
        r.account_id,
        ':',
        (string_to_array(r.recovery_point_arn, '::'))[2]
      )
    )
    WHEN r.resource_type = 'EC2' THEN (
      SELECT tags FROM aws_ec2_instance WHERE arn = CONCAT(
        (string_to_array(r.recovery_point_arn, '::'))[1],
        ':',
        r.account_id,
        ':',
        (string_to_array(r.recovery_point_arn, '::'))[2]
      )
    )
  END AS target_resource_tags,
  r.region,
  r.account_id
FROM
  aws_backup_recovery_point as r;
```

**Result:**

```
+--------------------------------+--------------------------------------------------------+---------------+--------------------------------------------------------------------------------------+-----------+--------------+
| backup_vault_name              | recovery_point_arn                                     | resource_type | target_resource_tags                                                                 | region    | account_id   |
+--------------------------------+--------------------------------------------------------+---------------+--------------------------------------------------------------------------------------+-----------+--------------+
| aws/efs/automatic-backup-vault | arn:aws:ec2:us-east-1::snapshot/snap-06ff60334c460fcd7 | EBS           | {"aws:backup:source-resource":"0a72b796-a631-4e6a-bcc7-fcadb7d683d9","backup":"yes"} | us-east-1 | 33333333333 |
+--------------------------------+--------------------------------------------------------+---------------+--------------------------------------------------------------------------------------+-----------+--------------+
```

Your feedback and insights are highly valued, and I look forward to collaborating on the best approach to address this matter.

Thanks you!

**Comment by Veetaha** [comment]
@ParthaI thanks for the quick turnaround!

> Given that the recovery_point_arn column can represent ARNs for various resource types (e.g., EC2, EBS, S3, etc.) as outlined [here](https://docs.aws.amazon.com/aws-backup/latest/devguide/whatisbackup.html#features-by-resource), it may not be ideal for including the tags column in this table and populating the values based on the resource type.

Yeah, I definitely understand the opposition to reach out to service-specific APIs to populate tags here. I still think it would be cleaner if steampipe did this for us, or maybe it had some explicit helpers or docs about this.

> I believe we can attain our objective within the current plugin version. We can craft a query to retrieve associated tags for a resource by incorporating a switch case that considers the resource_type column in the aws_backup_recovery_point table.

I like the approach as it would actually solve the problem with tags for RPs, so I think this is already something worthwhile! The query is rather big, but at least it achives the desired result, however, I'd like to point out several things about this query:
1. The provided query doesn't work in the current version of the AWS plugin for the following reasons.
  - The case for EC2 has to be fixed a bit to use the `aws_ec2_ami` table instead. I updated the query, so this one fixes this problem:
  ```sql
  SELECT
    r.backup_vault_name as backup_vault_name,
    r.recovery_point_arn as recovery_point_arn,
    r.resource_type as resource_type,
  CASE
      WHEN r.resource_type = 'EBS' THEN (
        SELECT tags FROM aws_ebs_snapshot WHERE arn = CONCAT(
          (string_to_array(r.recovery_point_arn, '::'))[1],
          ':',
          r.account_id,
          ':',
          (string_to_array(r.recovery_point_arn, '::'))[2]
        )
      )
      WHEN r.resource_type = 'EC2' THEN (
        SELECT tags FROM aws_ec2_ami
        WHERE image_id = (string_to_array(r.recovery_point_arn, '::image/'))[2]
      )
  END AS target_resource_tags,
    r.region,
    r.account_id
  FROM
    aws_backup_recovery_point as r;
  ```
  - **Critical**. The is simply no `tags` field on the `aws_recovery_point` table. So there is nothing we could do for kinds of recovery points such as `S3` or `EFS` because they have "Full AWS Backup management", so they have no service-specific APIs to fetch the tags for them. The native AWS Backup `ListTags` is the only way to get tags for such RPs. I have examples of both of these recovery points with some sample tags in my dev AWS account, so I can provide you with some samples of API requests and their responses. I put them in the section "API requests examples" below.

  The gist of it is that there **are** kinds of recovery points where to fetch the tags one is required to use the `ListTags` API of AWS Backup service. Among them, I'm mostly interested in `EFS` and `S3`. I know it's supper-confusing, but this is how AWS Backup works. If you want to list RP tags in AWS Backup you must have a bunch of switch-cases.

2. Given all of the hussle, what if steampipe could somehow provide a materialized view or a generated column or an SQL function or some other way of having that large SQL query within the steampipe FDW or SQLite extension itself? I'm not really an SQL expert yet though, so not sure which exact mechanism this pre-made query could be expressed with. I understand that steampipe plugin SDK may be limited to defining only tables, and it may require significant groundwork in the plugin SDK itself to make it possible for a plugin to provide something like a pre-made query. If so, consider putting that query into the docs for the `aws_backup_recovery_point` where it could be maintained. Then steampipe users could just copy it from the docs. The query doesn't need to cover all possible kinds of AWS Backup recovery points, but I think `EC2, EBS, EFS, S3` (ones I'm interested in) could be in that query for a good start. If some else would be interested in more kinds of RPs they would probably contribute with the documentation update PR on their side.


# API requests examples

These are some AWS API query examples with responses that I pasted from my research at work. They include some API calls not relevant to this issue, but may be useful to you anyway, so I'm sharing them all.

I redacted the AWS account ID with AWS_ACCOUNT_ID.


## EFS recovery point

<details>
<summary>describe-recovery-point</summary>

```bash
aws backup describe-recovery-point \
  --backup-vault-name Default \
  --recovery-point-arn arn:aws:backup:us-east-2:AWS_ACCOUNT_ID:recovery-point:99a471dc-2b5e-40d3-ac5f-7d3546d56447
```
```json
{
    "RecoveryPointArn": "arn:aws:backup:us-east-2:AWS_ACCOUNT_ID:recovery-point:99a471dc-2b5e-40d3-ac5f-7d3546d56447",
    "BackupVaultName": "Default",
    "BackupVaultArn": "arn:aws:backup:us-east-2:AWS_ACCOUNT_ID:backup-vault:Default",
    "ResourceArn": "arn:aws:elasticfilesystem:us-east-2:AWS_ACCOUNT_ID:file-system/fs-03d4399ab01e21f4d",
    "ResourceType": "EFS",
    "IamRoleArn": "arn:aws:iam::AWS_ACCOUNT_ID:role/service-role/AWSBackupDefaultServiceRole",
    "Status": "COMPLETED",
    "CreationDate": "2023-10-27T16:14:11.726000+02:00",
    "CompletionDate": "2023-10-27T16:14:22.567000+02:00",
    "BackupSizeInBytes": 73,
    "CalculatedLifecycle": {
        "MoveToColdStorageAt": "2023-10-30T15:14:11.726000+01:00",
        "DeleteAt": "2024-01-28T15:14:11.726000+01:00"
    },
    "Lifecycle": {
        "MoveToColdStorageAfterDays": 3,
        "DeleteAfterDays": 93
    },
    "EncryptionKeyArn": "arn:aws:kms:us-east-2:AWS_ACCOUNT_ID:key/71ea99af-1f6d-4f80-ab30-65c58318c674",
    "IsEncrypted": true,
    "StorageClass": "WARM",
    "IsParent": false,
    "ResourceName": "vkryvenko-sample"
}
```

</details>


<details>
<summary>get-recovery-point-restore-metadata</summary>

```bash
aws backup get-recovery-point-restore-metadata
	--backup-vault-name Default \
	--recovery-point-arn arn:aws:backup:us-east-2:AWS_ACCOUNT_ID:recovery-point:99a471dc-2b5e-40d3-ac5f-7d3546d56447
```
```json
{
    "BackupVaultArn": "arn:aws:backup:us-east-2:AWS_ACCOUNT_ID:backup-vault:Default",
    "RecoveryPointArn": "arn:aws:backup:us-east-2:AWS_ACCOUNT_ID:recovery-point:99a471dc-2b5e-40d3-ac5f-7d3546d56447",
    "RestoreMetadata": {
        "aws:backup:request-id": "3d86b624-cb6c-436f-bf72-2938f50e1954",
        "file-system-id": "fs-03d4399ab01e21f4d"
    }
}
```

</details>


<details>
<summary>list-tags</summary>

```bash
aws backup list-tags --resource-arn arn:aws:backup:us-east-2:AWS_ACCOUNT_ID:recovery-point:a71a03a1-f99e-446a-ab9b-ea0f298218a9
```
```json
{
    "Tags": {
        "Name": "vkryvenko-sample",
        "elastio:resource": "true"
    }
}
```

</details>

## S3 recovery point

When I experimented with this it took 16m 10s to create a sample S3 RP with just one small file in the bucket (😰).

<details>
<summary>describe-recovery-point</summary>

```bash
aws backup describe-recovery-point \
	--backup-vault-name Default \
  --recovery-point-arn arn:aws:backup:us-east-2:AWS_ACCOUNT_ID:recovery-point:99a471dc-2b5e-40d3-ac5f-7d3546d56447
```
```json
{
    "RecoveryPointArn": "arn:aws:backup:us-east-2:AWS_ACCOUNT_ID:recovery-point:99a471dc-2b5e-40d3-ac5f-7d3546d56447",
    "BackupVaultName": "Default",
    "BackupVaultArn": "arn:aws:backup:us-east-2:AWS_ACCOUNT_ID:backup-vault:Default",
    "ResourceArn": "arn:aws:elasticfilesystem:us-east-2:AWS_ACCOUNT_ID:file-system/fs-03d4399ab01e21f4d",
    "ResourceType": "EFS",
    "IamRoleArn": "arn:aws:iam::AWS_ACCOUNT_ID:role/service-role/AWSBackupDefaultServiceRole",
    "Status": "COMPLETED",
    "CreationDate": "2023-10-27T16:14:11.726000+02:00",
    "CompletionDate": "2023-10-27T16:14:22.567000+02:00",
    "BackupSizeInBytes": 73,
    "CalculatedLifecycle": {
        "MoveToColdStorageAt": "2023-10-30T15:14:11.726000+01:00",
        "DeleteAt": "2024-01-28T15:14:11.726000+01:00"
    },
    "Lifecycle": {
        "MoveToColdStorageAfterDays": 3,
        "DeleteAfterDays": 93
    },
    "EncryptionKeyArn": "arn:aws:kms:us-east-2:AWS_ACCOUNT_ID:key/71ea99af-1f6d-4f80-ab30-65c58318c674",
    "IsEncrypted": true,
    "StorageClass": "WARM",
    "IsParent": false,
    "ResourceName": "vkryvenko-sample"
}
```

</details>

<details>
<summary>get-recovery-point-restore-metadata</summary>

```bash
aws backup get-recovery-point-restore-metadata \
	--backup-vault-name Default \
  --recovery-point-arn arn:aws:backup:us-east-2:AWS_ACCOUNT_ID:recovery-point:vkryvenko-sample-20231027154316-df0a0866
```
```json
{
    "BackupVaultArn": "arn:aws:backup:us-east-2:AWS_ACCOUNT_ID:backup-vault:Default",
    "RecoveryPointArn": "arn:aws:backup:us-east-2:AWS_ACCOUNT_ID:recovery-point:vkryvenko-sample-20231027154316-df0a0866",
    "RestoreMetadata": {
        "InitialRestoreTime": "2023-10-27T15:51:31Z",
        "LatestRestoreTime": "2023-10-27T15:51:31Z",
        "aws:backup:request-id": "418ea350-7a6f-499e-96a2-3592f3d554ad"
    }
}
```

</details>


<details>
<summary>list-tags</summary>

```bash
aws backup list-tags --resource-arn arn:aws:backup:us-east-2:AWS_ACCOUNT_ID:recovery-point:vkryvenko-sample-20231031163856-1dabc68c
```
```json
{
    "Tags": {
        "elastio:resource": "true"
    }
}
```

</details>

# Docs

I forgot to mention this in the issue body, but right docs now the docs for the `aws_backup_vault/aws_backup_recovery_point` tables mention this:

> The schema outlines the various attributes of the backup vault for you, including the vault name, ARN, creation date, last resource backup time, and associated tags.

Although tags aren't supported for them in the current version of AWS plugin. Since #2033 implements tags for vaults, the docs for vaults will now be correct, but the docs for recovery points should at least mention the caveat that not all RPs will have the tags populated.

**Comment by ParthaI** [comment]
@Veetaha, Thank you for describing things more clearly and figuring out the mistake in the table docs. The `API requests examples` section of comment was very helpful for understanding about the service/resource.

Definitely, we will think about it if there is any feasibility to support the feature:
> Given all of the hussle, what if steampipe could somehow provide a materialized view or a generated column or an SQL function or some other way of having that large SQL query within the steampipe FDW or SQLite extension itself? 

In the existing PR(#2033), I have added the `tags` column for the table `aws_backup_recovery_point` and updated the doc with an admonition for `tags` column usage.

Once again, thank you for the detailed research and cooperation!
