### ISSUE TITLE
 aws_iam_credential_report <root_account> breaks nunit XML

### ISSUE THREAD

**Issue by srobroek-aws** [turbot/steampipe-plugin-aws#2071]
**Describe the bug**
When using aws_iam_credential_report in various checks, the root user's friendly name is reported as <root_account>. When exporting unit tests in nunit3 xml this breaks the XML as nunit consider this is XML tag.

**Steampipe version (`steampipe -v`)**
 v0.21.1

**Plugin version (`steampipe plugin list`)**
Example: select user_name from aws_iam_credential_report

**To reproduce**
query `select user_name from aws_iam_credential_report`, which produces

| user_name         |
|----------------|
| <root_account> |

**Expected behavior**
2 possibilities exist here:

- Individual queries should be built in such a way that <> are replaced in results. 
- The nunit exporter should be built in such a way that <> are replaced in results.

My preference would go towards the second one, as it's more foolproof and works across all plugins and mods, not just the aws plugin/aws compliance mod.

**Comment by srobroek-aws** [comment]
Update on this, this seems to be an issue with more than just this benchmark. If i run the pci_dss_v321 benchmark or the gdpr benchmark, i'm running into the same issue. Seems to be related to `aws_compliance.control.iam_user_console_access_mfa_enabled` and `aws_compliance.control.iam_user_console_access_mfa_enabled as well. 

From what i can see this is related to how AWS generates IAM credential reports (as per https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_getting-report.html#getting-credential-reports-cliapi). When generating a report directly through the CLI or UI the root user is also reported as <root account>. 

Easiest solution would likely be to fix this in the iam report generation and sanitise the output.

**Comment by ParthaI** [comment]
Dear @srobroek-aws,

Thank you very much for bringing this issue to our attention.

Upon reviewing the matter, I have gathered some insights that I believe may be helpful. I kindly invite you to consider the following points:

1. The table `aws_iam_credential_report` retrieves its data via the [GetCredentialReport](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/iam@v1.19.0#Client.GetCredentialReport) API, which notably includes the username formatted as `<root_account>`.
2. In alignment with this, the corresponding CLI command (`aws iam get-credential-report`) yields an identical outcome, mirroring the results provided by Steampipe.
3. It is our usual practice to refrain from altering the API response. This approach stems from a consideration of the diverse ways in which users might be leveraging this table, coupled with the potential for introducing breaking changes through such modifications.
4. May I suggest attempting the following query to exclude the `<>` symbols from the username? While this solution has been tested in a controlled environment, the specific nuances of your use case might necessitate further adjustments. Please feel empowered to modify the query as you see fit.

```sql
select 
  user_name,
  replace(replace(user_name, '<', ''), '>', '') as clean_user_name
from 
  aws_iam_credential_report 
where 
  user_name = '<root_account>';
```

Result:

```
+----------------+-----------------+
| user_name      | clean_user_name |
+----------------+-----------------+
| <root_account> | root_account    |
+----------------+-----------------+
```

Your feedback and insights are highly valued, and I look forward to any additional questions or clarifications you might have.

Thanks you!

**Comment by srobroek-aws** [comment]
Thanks, that would work for me.
Sent from my iPhone

On 13 Feb 2024, at 12:53, ParthaI ***@***.***> wrote:

﻿

Dear @srobroek-aws<https://github.com/srobroek-aws>,

Thank you very much for bringing this issue to our attention.

Upon reviewing the matter, I have gathered some insights that I believe may be helpful. I kindly invite you to consider the following points:

  1.  The table aws_iam_credential_report retrieves its data via the ***@***.***#Client.GetCredentialReport> API, which notably includes the username formatted as <root_account>.
  2.  In alignment with this, the corresponding CLI command (aws iam get-credential-report) yields an identical outcome, mirroring the results provided by Steampipe.
  3.  It is our usual practice to refrain from altering the API response. This approach stems from a consideration of the diverse ways in which users might be leveraging this table, coupled with the potential for introducing breaking changes through such modifications.
  4.  May I suggest attempting the following query to exclude the <> symbols from the username? While this solution has been tested in a controlled environment, the specific nuances of your use case might necessitate further adjustments. Please feel empowered to modify the query as you see fit.

select
  user_name,
  replace(replace(user_name, '<', ''), '>', '') as clean_user_name
from
  aws_iam_credential_report
where
  user_name = '<root_account>';

Result:

+----------------+-----------------+
| user_name      | clean_user_name |
+----------------+-----------------+
| <root_account> | root_account    |
+----------------+-----------------+


Your feedback and insights are highly valued, and I look forward to any additional questions or clarifications you might have.

Thanks you!

**Comment by ParthaI** [comment]
Thank you, @srobroek-aws, for your prompt reply.

Following our recent conversation, it appears that the problem has been successfully addressed using the alternative query mentioned in this [comment](https://github.com/turbot/steampipe-plugin-aws/issues/2071#issuecomment-1940796013).

Therefore, I'll be closing this issue momentarily. Should you face any additional challenges, please don't hesitate to reopen the issue.

Many thanks once more!
