### ISSUE TITLE
Fix typo for a table name in docs

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-aws#211]
**Describe the bug**
The table name should be `aws_vpc_security_group_rule` instead of `aws_ec2_security_group_rule`

**Additional context**
https://steampipe.io/docs
![image](https://user-images.githubusercontent.com/43408569/111643337-e6f5ca00-8824-11eb-97bd-c773d6c0e803.png)
![image](https://user-images.githubusercontent.com/43408569/111643630-1c9ab300-8825-11eb-9585-329cd5842cd0.png)

**Comment by cbruno10** [comment]
@debabrat-git Closing this issue as it needs to be raised in the steampipe.io repo? Plugin related docs that show up on hub.steampipe.io can be fixed here, but content on steampipe.io is managed separately.
