### ISSUE TITLE
Why doesn't aws_ec2_instance_type table support the account_id (and region) column?

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe-plugin-aws#2195]
It's hard to query instance types as a single list because this table does not allow you to filter to a single account. As a result you get many duplicates.

Also - do instance types vary by region? If so, should this table be querying by region?

**Comment by graza-io** [comment]
In addition to the above, would be also useful to be able to filter by instance family `m5a`, `m5`, `t3`, etc - This would drastically increase performance.

**Comment by ParthaI** [comment]
@e-gineer / @graza-io, I've submitted a [PR](https://github.com/turbot/steampipe-plugin-aws/pull/2200) to address this issue. Here are the changes implemented:
- We can now obtain results for each region.
- It's possible to filter by instance type as demonstrated (`select instance_type, region from aws_ec2_instance_type where instance_type = 'r6g.large'`).
- The API does not support filtering by instance family. While specific instances like `m6g.metal` can be filtered, broader family filters like `m6g` are not supported. Reference: [AWS API Documentation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstanceTypeOfferings.html#API_DescribeInstanceTypeOfferings_RequestParameters)

---

> Also - do instance types vary by region? If so, should this table be querying by region?

Yes, it varies from region to region.

```
> select count(*) from aws_ec2_instance_type where region = 'us-east-1'
+-------+
| count |
+-------+
| 776   |
+-------+

> select count(*) from aws_ec2_instance_type where region = 'ap-south-1'
+-------+
| count |
+-------+
| 518   |
+-------+
```

Please let me know if I have missed any other implementations.

Thank you!
