### ISSUE TITLE
aws_ec2_instance_type returns incorrect data

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-plugin-aws#2202]
`t2` instance types are not the current generation, however they're reported as such:

```sql
select * 
from aws_ec2_instance_type 
where instance_type like 't2.%'
```
<img width="1282" alt="Screenshot 2024-05-28 at 15 33 48" src="https://github.com/turbot/steampipe-plugin-aws/assets/53316123/8dc5a192-9b63-44e9-890a-517357902941">

**Comment by ParthaI** [comment]
Hello @graza-io, I've been reviewing the `aws_ec2_instance_type` table and would like to share my findings regarding this issue.

- The table utilizes two API calls: [DescribeInstanceTypeOfferings](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstanceTypeOfferings.html) and [DescribeInstanceTypes](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstanceTypes.html).
- `DescribeInstanceTypeOfferings` provides the available instance types per region, while `DescribeInstanceTypes` details the characteristics of each instance type.
- The `DescribeInstanceTypes` API specifically returns the `CurrentGeneration` property.
- I also verified these findings using the AWS CLI command: `aws ec2 describe-instance-types --query 'InstanceTypes[*].{InstanceType:InstanceType, CurrentGeneration:CurrentGeneration}' --region eu-north-1`, and the results matched exactly.
- Also in the console, I can see the `t2.micro` instance type under the `us-east-1` region is the current generation.
<img width="588" alt="Screenshot 2024-05-29 at 12 28 58 PM" src="https://github.com/turbot/steampipe-plugin-aws/assets/47887552/9378e5c4-65e8-4525-a37c-2759ff06ad03">

Did you find any deviation between the results returned by AWS CLI, AWS Console, and Steampipe?

Note: The current implementation in the main branch for the `aws_ec2_instance_type` table returns data for the `us-east-1` region. However, there's an [open PR](https://github.com/turbot/steampipe-plugin-aws/pull/2200) that updates this to retrieve results for all supported regions for an AWS account.

Thank you!

**Comment by graza-io** [comment]
Ah, looks like `current_generation` doesn't show if it's current as in `latest` as I thought it would... (cc: @e-gineer for reference)

A quick check in eu-north-1 only shows `d2` as not being in `current_generation` but also equally doesn't even list the `t2` options.

![image](https://github.com/turbot/steampipe-plugin-aws/assets/53316123/a2ae5cba-c4d1-4ee5-be33-caeada25fd67)
```sh
❯ aws ec2 describe-instance-types --query 'InstanceTypes[*].{InstanceType:InstanceType, CurrentGeneration:CurrentGeneration}' --region eu-north-1 | jq '[.[] | select(.InstanceType | startswith("t"))]'
```
```json
[
  {
    "InstanceType": "t3.2xlarge",
    "CurrentGeneration": true
  },
  {
    "InstanceType": "t4g.nano",
    "CurrentGeneration": true
  },
  {
    "InstanceType": "t3.medium",
    "CurrentGeneration": true
  },
  {
    "InstanceType": "t4g.medium",
    "CurrentGeneration": true
  },
  {
    "InstanceType": "t4g.2xlarge",
    "CurrentGeneration": true
  },
  {
    "InstanceType": "t3.xlarge",
    "CurrentGeneration": true
  },
  {
    "InstanceType": "t3.large",
    "CurrentGeneration": true
  },
  {
    "InstanceType": "t3.micro",
    "CurrentGeneration": true
  },
  {
    "InstanceType": "t3.nano",
    "CurrentGeneration": true
  },
  {
    "InstanceType": "t4g.xlarge",
    "CurrentGeneration": true
  },
  {
    "InstanceType": "t4g.small",
    "CurrentGeneration": true
  },
  {
    "InstanceType": "t4g.micro",
    "CurrentGeneration": true
  },
  {
    "InstanceType": "t4g.large",
    "CurrentGeneration": true
  },
  {
    "InstanceType": "t3.small",
    "CurrentGeneration": true
  }
]
```

Thanks for digging into this @ParthaI - will close now as it appears the table is behaving as intended just not as desired ;)
