### ISSUE TITLE
The region column for aws_health_event query displays 'global' value instead of actual region value.

### ISSUE THREAD

**Issue by nasrien86** [turbot/steampipe-plugin-aws#2222]
When querying for region details for aws_health_event, the result displays the region as 'global' instead of the region name ex us-east-1, us-west-2

Steampipe v0.22.2

**Plugin version (`steampipe plugin list`)**
v0.10.0

**Expected behavior**
The region column should show the correct region instead of 'global' value

**Comment by ParthaI** [comment]
Hello @nasrien86,

Since AWS Health is a global service, the region column value is expected to be populated as `global`. I am closing this issue for now as the value is as expected. Please feel free to reopen this issue or create a new one if you encounter any further problems.

Thank you!
