### ISSUE TITLE
aws_lambda_version does not include point-in-time configuration snapshot

### ISSUE THREAD

**Issue by skeggse** [turbot/steampipe-plugin-aws#2228]
**Describe the bug**

When I run `GetFunctionConfiguration`, I can specify a `Qualifier` to show the configuration for a particular function version.

Similarly, when I run `ListVersionsByFunction`, I can see the configuration for each version of a given function.

In Steampipe, I can get at the configuration information for previous versions through neither the`aws_lambda_function` nor the `aws_lambda_version` tables.

**Steampipe version (`steampipe -v`)**
Example: v0.22.2

**Plugin version (`steampipe plugin list`)**
Example: v0.137.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

```sql
select * from aws_lambda_version limit 2;
```

observe a lack of any configuration information

**Expected behavior**

the `aws_lambda_version` table includes configuration information.

**Additional context**

**Comment by ParthaI** [comment]
Hi @skeggse, Apologies for the inconvenience, I noticed there were a few missing columns in the table `aws_lambda_version`. I have raised a [PR](https://github.com/turbot/steampipe-plugin-aws/pull/2229) by addressing the missing columns. Please let us know if you need any other configuration details for lambda function versions.

You can give it a shot in the PR branch `issue-2228` if you want to.

Thanks!
