### ISSUE TITLE
table 'aws_appautoscaling_target' is missing 1 required qual: column:'service_namespace'

### ISSUE THREAD

**Issue by electriquo** [turbot/steampipe-plugin-aws#2246]
**Describe the bug**
Error when querying `aws_appautoscaling_target` table.

**Steampipe version (`steampipe -v`)**
v0.23.3

**Plugin version (`steampipe plugin list`)**
0.144.0

**To reproduce**

```shell
$ steampipe query "select * from aws_appautoscaling_target limit 1" --output csv
Error: aws_redislabs: rpc error: code = Internal desc = 'List' call for table 'aws_appautoscaling_target' is missing 1 required qual: column:'service_namespace' operator: =

	aws_sec: rpc error: code = Internal desc = 'List' call for table 'aws_appautoscaling_target' is missing 1 required qual: column:'service_namespace' operator: =

	aws_tst: rpc error: code = Internal desc = 'List' call for table 'aws_appautoscaling_target' is missing 1 required qual: column:'service_namespace' operator: =

	aws_scylladb: rpc error: code = Internal desc = 'List' call for table 'aws_appautoscaling_target' is missing 1 required qual: column:'service_namespace' operator: =

	aws_stg: rpc error: code = Internal desc = 'List' call for table 'aws_appautoscaling_target' is missing 1 required qual: column:'service_namespace' operator: =

	aws_mgmt: rpc error: code = Internal desc = 'List' call for table 'aws_appautoscaling_target' is missing 1 required qual: column:'service_namespace' operator: =

	aws_logs: rpc error: code = Internal desc = 'List' call for table 'aws_appautoscaling_target' is missing 1 required qual: column:'service_namespace' operator: =

	aws_dyaws: rpc error: code = Internal desc = 'List' call for table 'aws_appautoscaling_target' is missing 1 required qual: column:'service_namespace' operator: =

	aws_external: rpc error: code = Internal desc = 'List' call for table 'aws_appautoscaling_target' is missing 1 required qual: column:'service_namespace' operator: =

	aws_dev: rpc error: code = Internal desc = 'List' call for table 'aws_appautoscaling_target' is missing 1 required qual: column:'service_namespace' operator: =

	aws_dy_mcd_prod: rpc error: code = Internal desc = 'List' call for table 'aws_appautoscaling_target' is missing 1 required qual: column:'service_namespace' operator: =
 (SQLSTATE HV000)
```

**Expected behavior**
No errors should occur.

**Comment by ParthaI** [comment]
Hello @electriquo,

I don't think this is a bug in the plugin. The behavior you are seeing is expected for the `aws_appautoscaling_target` table. Here’s why:

- The table uses the [DescribeScalableTargets](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_DescribeScalableTargets.html#API_DescribeScalableTargets_RequestSyntax) API call to populate the column values.
- This API call requires the [ServiceNamespace](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_DescribeScalableTargets.html#autoscaling-DescribeScalableTargets-request-ServiceNamespace) value as a query parameter.
- Valid values for ServiceNamespace are: `ecs | elasticmapreduce | ec2 | appstream | dynamodb | rds | sagemaker | custom-resource | comprehend | lambda | cassandra | kafka | elasticache | neptune | workspaces`.

To use this table, you need to query it with a specific service namespace, like this: `select * from aws_appautoscaling_target where service_namespace = 'ec2'`.

It looks like we might have missed updating the [table documentation](https://hub.steampipe.io/plugins/turbot/aws/tables/aws_appautoscaling_target). I will review it and make the necessary updates. Apologies for the confusion.

Thanks!
