### ISSUE TITLE
Add table aws_IPAM_Public_IP_Insights

### ISSUE THREAD

**Issue by idesofoctober** [turbot/steampipe-plugin-aws#2249]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

**Comment by misraved** [comment]
Thanks @idesofoctober for raising the request 👍 !

If anyone would like to attempt to develop this table, the documentation [here](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_GetIpamDiscoveredPublicAddresses.html) is an excellent place to start.

Please let us know if there are questions 👍!
