### ISSUE TITLE
Add "EBS encryption" setting as part of Account attribute

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-aws#225]
**Is your feature request related to a problem? Please describe.**
want to verify `EBS Default Encryption` is enabled or not. Unable to find any column storing this field value in ```aws_account``` table.  Not sure if that exists in any other table.

**Additional context**

![image](https://user-images.githubusercontent.com/43408569/111956661-089ace00-8b11-11eb-84a7-088f57849517.png)

**Comment by debabrat-git** [comment]
![image](https://user-images.githubusercontent.com/43408569/111971833-ca0e0f00-8b22-11eb-8278-6615c5afce71.png)

**Comment by Subhajit97** [comment]
@debabrat-git We have released a new table `aws_ec2_regional_settings` as part of new AWS plugin(`0.21.0`), that stores the settings(i.e. `EBS encryption`) for a region.
You can update AWS plugin to latest i.e. `steampipe plugin update aws`, and try the following query to get the `EBS Default Encryption`

```sql
select
  region,
  default_ebs_encryption_enabled,
  default_ebs_encryption_key
from
  aws_ec2_regional_settings;
```

**Comment by debabrat-git** [comment]
new table `aws_ec2_regional_settings`
