### ISSUE TITLE
Dynamic values are not evaluated

### ISSUE THREAD

**Issue by electriquo** [turbot/steampipe-plugin-aws#2251]
**Describe the bug**

By examining the logs, it appears that the plugin does not work with dynamic values.

Refer to`isEqual` column in the following query, where it shows that the static and the dynamic values are equal from PostgreSQL perspective.

```sql
select
	'[{"Name": "LoadBalancer", "Value": "app/4b511df3d24f8ea194/7bff74fbf81116"}]' = jsonb_build_array(
    jsonb_build_object('Name', 'LoadBalancer', 'Value', 'app/4b511df3d24f8ea194/7bff74fbf81116')
  ) as isEqual;
```

That means, that we could replace each value with the other. But while the following query does work as expected

```sql
select
  sum(cw.sum)
from
  aws_cloudwatch_metric_statistic_data_point as cw
where
  cw.namespace = 'AWS/ApplicationELB'
  and cw.metric_name = 'RequestCount'
  and cw.region = 'us-east-1'
  and cw.timestamp >= '2024-07-01 00:00:00+00'
  and cw.dimensions = '[{"Name": "LoadBalancer", "Value": "app/4b511df3d24f8ea194/7bff74fbf81116"}]'
  and cw.period = 2592000
limit
  1;
```

The following query does **not** work as expected

```sql
select
  sum(cw.sum)
from
  aws_cloudwatch_metric_statistic_data_point as cw
where
  cw.namespace = 'AWS/ApplicationELB'
  and cw.metric_name = 'RequestCount'
  and cw.region = 'us-east-1'
  and cw.timestamp >= '2024-06-02 00:00:00+00'
  and cw.dimensions = jsonb_build_array(
    jsonb_build_object('Name', 'LoadBalancer', 'Value', 'app/4b511df3d24f8ea194/7bff74fbf81116')
  )
  and cw.period = 2592000
limit
  1;
```

This also holds for dynamic value for the timestamp column.

**Steampipe version (`steampipe -v`)**
v0.23.3

**Plugin version (`steampipe plugin list`)**
0.144.0

**To reproduce**
Refer to the description above.

**Expected behavior**
The plugin behavior should coincide with PostgreSQL behavior

**Comment by ParthaI** [comment]
Hello @electriquo,

Sorry to hear that you are encountering this issue.

Based on my previous experience, the query plan generation can significantly impact the results.

I've made some adjustments to the query mentioned above to better populate the dynamic values. 
Could you please try it again and let us know if it resolves the issue?

```sql
with dimensioncte as (
  select
    concat(
      '[{"Name":"LoadBalancer","Value":"app/4b511df3d24f8ea194/7bff74fbf81116"},',']'
    )::jsonb as dimensions
)
select
  sum(cw.sum)
from
  aws_cloudwatch_metric_statistic_data_point as cw
join
  dimensioncte as d
on
  cw.dimensions = d.dimensions
where
  cw.namespace = 'AWS/ApplicationELB'
  and cw.metric_name = 'RequestCount'
  and cw.region = 'us-east-1'
  and cw.timestamp >= '2024-06-02 00:00:00+00'
  and cw.period = 2592000
```

Related discussions https://github.com/turbot/steampipe-plugin-aws/issues/2096#issuecomment-1983530619

Thanks!
