### ISSUE TITLE
Add table aws_qldb_ledger

### ISSUE THREAD

**Issue by Priyanka-Chatterjee-2000** [turbot/steampipe-plugin-aws#2265]
**References**
[Go SDK List](https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.55.5/service/qldb#QLDB.DescribeLedger)
[Terraform Link](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/qldb_ledger)

**Comment by ParthaI** [comment]
#### Closing this issue since the Amazon QLDB service is in a retirement state, and they have stopped supporting the creation of resources under the QLDB service. Announcement: https://docs.aws.amazon.com/qldb/latest/developerguide/what-is.html
