### ISSUE TITLE
Add table aws_mwaa_environment

### ISSUE THREAD

**Issue by gist-infrastructuresecurity** [turbot/steampipe-plugin-aws#2278]
**References**

https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.55.5/service/mwaa
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mwaa_environment

**Comment by misraved** [comment]
Thanks @gist-infrastructuresecurity  for raising the request 👍 !

If anyone would like to attempt to develop this table, the API mentioned by @gist-infrastructuresecurity  is an excellent place to start.

Please let us know if there are questions 👍!
