### ISSUE TITLE
Can Custom Controls be queried ?

### ISSUE THREAD

**Issue by swagatDevops** [turbot/steampipe-plugin-aws#2280]
In our Landing Zone , we are using Custom Controls specific to our requirement.
Is there any table on aws_securityhub_standards_control where I can look for Custom controls ?

**Comment by khushboo9024** [comment]
Hi @swagatDevops ,

Thank you for raising the issue. Could you please specify which custom control you are referring to? Are you talking about the custom control in `Audit Manager`? Please find the screenshot below and let us know.

<img width="1183" alt="image" src="https://github.com/user-attachments/assets/9f248336-3266-420e-8660-a91e1733654a">

**Comment by swagatDevops** [comment]
No , I am talking about Custom Controls in Security Hun Findings .
If you are aware of , Security Hub provides findings based on AWS managed controls , right now we have some Custom controls for security hub and AWS Config , we want to extract the report based on our custom controls.

**Comment by ParthaI** [comment]
Hello, @swagatDevops,

Before I proceed, I just wanted to clarify a couple of things:

- Based on the above discussion, it seems that the `aws_securityhub_standards_control` table doesn't provide the custom control details for your environment, correct?
- Could you please share the specific **AWS CLI** command you use to retrieve your custom control details and their findings?

**Comment by misraved** [comment]
Hi @swagatDevops 

We haven’t heard back from you in a while, so we’re going to close this issue for now. If you’re still experiencing this problem or have additional information to share, please feel free to reopen the issue or create a new one.

Thank you for your understanding!
