### ISSUE TITLE
Add table aws_elastic_container_registry

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-aws#229]
**References**
https://docs.aws.amazon.com/AmazonECR/latest/userguide/what-is-ecr.html

Scenario to validate:
to verify ```image scan on push```  is enabled for ECR repo or not.
![image](https://user-images.githubusercontent.com/43408569/111981115-3a219280-8b2d-11eb-8179-87c7595d6a2f.png)

**Comment by bigdatasourav** [comment]
as discussed - table aws_ecr_repository is already created -
> select repository_name,registry_id,repository_uri,image_scanning_configuration from aws_ecr_repository;
+-----------------+--------------+---------------------------------------------------+------------------------------+
| repository_name | registry_id  | repository_uri                                    | image_scanning_configuration |
+-----------------+--------------+---------------------------------------------------+------------------------------+
| test            | 013122550996 | 013122550996.dkr.ecr.us-east-1.amazonaws.com/test | {"ScanOnPush":true}          |
+-----------------+--------------+---------------------------------------------------+------------------------------+
