### ISSUE TITLE
aws_ec2_instance_type takes over 4 minutes

### ISSUE THREAD

**Issue by zickzackv** [turbot/steampipe-plugin-aws#2292]
**Describe the bug**
A Query on the instance type table aws_ec2_instance_type took over 4 minutes to be finished.

**Steampipe version (`steampipe -v`)**
Steampipe v0.23.1

**Plugin version (`steampipe plugin list`)**

+--------------------------------------------+---------+----------------------------------------------------------------------+
| Installed                                  | Version | Connections                                                          |
+--------------------------------------------+---------+----------------------------------------------------------------------+
| hub.steampipe.io/plugins/turbot/aws@latest | 0.145.0 | .....                                                                |
+--------------------------------------------+---------+----------------------------------------------------------------------+

**To reproduce**
select * from dsp.aws_ec2_instance_type where instance_type like 't2%';

**Expected behavior**

A shorter time for finishing the query, like 40s max.

**Additional context**

**Comment by e-gineer** [comment]
4 minutes is surprising ... do you have a lot of instances?

Even across all regions that query returns for me in a 347ms.

**Comment by zickzackv** [comment]
The query should be actually quite static because the instance types is not the list of instances but just the available types within a region. From the aws webconsole its possible to download an CSV file with around 720 entries.


My anonymous-ed config.

```ini
connection "d10af457daa1deed54e2c36b5f295e7e" {
  plugin         = "aws"
  profile        = 3af582afe82dee8b77c44b5ef15f8fe7"
  regions        = ["eu-central-1"]
  default_region = "eu-central-1"
}

connection "220226394582d7117410e3c021748c2a" {
  plugin         = "aws"
  profile        = 1ec395bdfd9d444d9d5ba27174e5c9ca"
  regions        = ["eu-central-1"]
  default_region = "eu-central-1"
}

connection "f57c4e385a9dfe278204e6918a890b4a" {
  plugin         = "aws"
  profile        = 3c002f5c961cbc1e0ce178872095b255"
  regions        = ["eu-central-1"]
  default_region = "eu-central-1"
}

connection "dsp" {
  plugin      = "aws"
  type        = "aggregator"
  connections = ["d10af457daa1deed54e2c36b5f295e7e", "220226394582d7117410e3c021748c2a", "f57c4e385a9dfe278204e6918a890b4a"]
}


connection "494b9c02760aad17bd379cd1fad126a4" {
  plugin         = "aws"
  profile        = 1c3cab3e467d2bd4abf2cf1b8dfb1e9e"
  regions        = ["eu-central-1"]
  default_region = "eu-central-1"
}

connection "a030b2e2c53bb2da236f78803d60380a" {
  plugin         = "aws"
  profile        = 9b5058a48053a53b16630561ea55f2f4"
  regions        = ["eu-central-1"]
  default_region = "eu-central-1"
}

connection "820248a8adf19dab253683541903d8d6" {
  plugin         = "aws"
  profile        = 116ef965bd34a91a6c4586165213505a"
  regions        = ["eu-central-1"]
  default_region = "eu-central-1"
}

connection "ec1f5310644af71b065b8f5806e35034" {
  plugin         = "aws"
  profile        = e1b07b0ea388477f9b141755d7508827"
  regions        = ["eu-central-1"]
  default_region = "eu-central-1"
}

connection "ab8a1d3403cf822e734f1a8297ddf4be" {
  plugin         = "aws"
  profile        = 2e81402ef017d313f1823d13775b80c6"
  regions        = ["eu-central-1"]
  default_region = "eu-central-1"
}

connection "6576ffa62eef95cd794f0ee30615fe86" {
  plugin         = "aws"
  profile        = 5e2d48dcde5cad5552d43e394e7704cb"
  regions        = ["eu-central-1"]
  default_region = "eu-central-1"
}

connection "sop" {
  plugin      = "aws"
  type        = "aggregator"
  connections = ["820248a8adf19dab253683541903d8d6", "494b9c02760aad17bd379cd1fad126a4", "a030b2e2c53bb2da236f78803d60380a", "6576ffa62eef95cd794f0ee30615fe86", "ec1f5310644af71b065b8f5806e35034", "ab8a1d3403cf822e734f1a8297ddf4be"]
}


connection "aws" {
  plugin      = "aws"
  type        = "aggregator"
  connections = ["d10af457daa1deed54e2c36b5f295e7e", "220226394582d7117410e3c021748c2a", "f57c4e385a9dfe278204e6918a890b4a", "820248a8adf19dab253683541903d8d6", "494b9c02760aad17bd379cd1fad126a4", "a030b2e2c53bb2da236f78803d60380a", "6576ffa62eef95cd794f0ee30615fe86", "ec1f5310644af71b065b8f5806e35034", "ab8a1d3403cf822e734f1a8297ddf4be"]
}

```

A query of the instance_types over all accounts taking long and hanging at 3,250 results.

```
❯ steampipe query
Welcome to Steampipe v0.23.1
For more information, type .help
> select * from aws_ec2_instance_type
⠏ Loading results: 3,182
```

A query over just one account never ends, just hangs.

```
select * from 220226394582d7117410e3c021748c2a.aws_ec2_instance_type
⠋ Loading results: 325
```

The previous query that took 4 minutes was against a `steampipe service` postgresql server with `pgcli`

**Comment by zickzackv** [comment]
forgot to mention:

We are using AWS SSO for all the mentioned accounts.

**Comment by e-gineer** [comment]
Sorry, my mistake - I thought you asked about `aws_ec2_instance` rather than `aws_ec2_instance_type` <facepalm>

This query has to phases:
1. List the instance type offerings. This is fast, but returns everything since the API doesn't support wildcard searches.
2. For each offering, call an API to get details about it. This is heavily throttled since there are hundreds of types.
3. Filter results to `t2%`. Results are filtered in the postgres layer at the end.

To improve performance, I'd try something like this:
```
select
  -- specific columns can reduce sub-API calls
  instance_type
from
  aws_ec2_instance_type
where
  -- limit to a single account
  account_id = '<account_id>'
  -- limit to a single region
  and region = '<region>'
```

This query has some of advantages:
1. It only queries the required column, which actually avoids step 2 above since it's returned in the list API results anyway.
2. Limits the query to a specific account & region preventing redundant work.

Unfortunately in my testing it was still slow. This was because of a bug where we were doing unnecessary "hydration" of the instance_type column - in effect calling the describe API for each row when we didn't need to for that column. I'll submit a PR for that now.

Thanks for letting us know and sorry for the inconvenience!

**Comment by e-gineer** [comment]
Technically the DescribeInstanceTypes API supports gathering results for up to 100 instance types at the same time. It would be possible to update the plugin to batch these hydration steps together into a single API call - which would make a massive speed difference if more details were required about each type.

[AWS docs link](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstanceTypes.html#:~:text=Array%20Members%3A%20Minimum%20number%20of%200%20items.%20Maximum%20number%20of%20100%20items.)

**Comment by zickzackv** [comment]
Thanks, for looking into that issue and addressing the optimizations.
