### ISSUE TITLE
aws_s3_bucket table queries returns errors after v1.2.0 [2024-11-04]

### ISSUE THREAD

**Issue by idesofoctober** [turbot/steampipe-plugin-aws#2340]
**Describe the bug**
- Queries against aws_s3_bucket table including the website

**Steampipe version (`steampipe -v`)**
- v1.0.0

**Plugin version (`steampipe plugin list`)**
v1.2.0 [2024-11-04]

**To reproduce**
select * from aws_s3_bucket

**Expected behavior**
Get the data from the query

**Additional context**
Seem that this was caused by this commit:

https://github.com/turbot/steampipe-plugin-aws/pull/2324/files

	if err != nil {
		plugin.Logger(ctx).Error("aws_s3_bucket.getBucketWebsite", "api_error", err)
		return nil, err

**Comment by misraved** [comment]
@idesofoctober thanks for raising the issue, we have merged the fix into main.

We will be releasing a new plugin version tomorrow that fixes the issue.
