### ISSUE TITLE
Decoding of secrets rendered in the encoded user_data for EC2.

### ISSUE THREAD

**Issue by rajmohanty17** [turbot/steampipe-plugin-aws#261]
**Is your feature request related to a problem? Please describe.**
Find secrets in EC2 User Data is one of the ISO-27001 requirement.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Autoscaling - https://docs.aws.amazon.com/autoscaling/ec2/userguide/create-launch-config.html
EC2 - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-add-user-data.html

**Comment by e-gineer** [comment]
As an initial suggestion, you could use postgres regexp tests against the user_data field. Primitive, but would be a start.
