### ISSUE TITLE
aws_iam_role.instance_profile_arn is missing some Instance Profile ARNs 

### ISSUE THREAD

**Issue by jackdelab** [turbot/steampipe-plugin-aws#285]
**Describe the bug**
Only Instance Profiles with the default path and the same name as the role they are attached to are listed in aws_iam_role.instance_profile_arn. Only one Instance Profile ARN is listed for roles that have more than one Instance Profile associated with them.

**Steampipe version (`steampipe -v`)**
Example: v0.3.5

**Plugin version (`steampipe plugin list`)**
Example: v0.10.1

**To reproduce**
Create 3 IAM roles:

1. test-role-1, with an instance profile name test-role-1
2. test-role-2, with an instance profile named test-role-2-profile
3. test role-3, with an instance profile name test-role-3 and an instance profile named test-role-3-profile

**Expected behavior**
`steampipe query "select name, instance_profile_arn from aws_iam_role where name like 'test-role%'"` should return the same 4 Instance Profile ARNs as 
```
aws iam list-instance-profiles-for-role --role-name test-role-1
aws iam list-instance-profiles-for-role --role-name test-role-2
aws iam list-instance-profiles-for-role --role-name test-role-3
```

**Actual Behavior**
the query only returns Instance Profile ARNs for instance-profile/test-role-1 and instance-profile/test-role-3

**Comment by e-gineer** [comment]
Thanks @jackdelab for reporting this!

The code is incorrectly using `GetInstanceProfile` and passing it the role name - https://github.com/turbot/steampipe-plugin-aws/blob/dd02b8ed972e46f88661049d74970c10f0897220/aws/table_aws_iam_role.go#L237

It should use `ListInstanceProfilesForRole` instead - https://docs.aws.amazon.com/sdk-for-go/api/service/iam/#IAM.ListInstanceProfilesForRole
