### ISSUE TITLE
Not getting Instance stopped time in `aws_ec2_instance` table to validate below mentioned use case

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-aws#316]
**Is your feature request related to a problem? Please describe.**
As per the AWS foundation security best practices

```This control checks whether any EC2 instances have been stopped for more than the allowed number of days. An EC2 instance fails this check if it is stopped for longer than the maximum allowed time period, which by default is 30 days.```

```Stopped EC2 instances should be removed after a specified time period and the `allowedDays: 30`. But not getting any column storing the value when the instance got stopped.```

**Describe the solution you'd like**
Would like to know if there is any column storing this stopped time for an ec2 instance.

**Additional context**
https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#ec2-4-remediation

**Comment by Subhajit97** [comment]
@debabrat-git We have added a new column `state_change_time`, which will store the date and time when the instance is being stopped.
You can use the following query to get the instances have been stopped for more than allowed days (i.i. 30 days)
```sql
select
  instance_id,
  instance_state,
  launch_time,
  state_change_time
from
  aws_ec2_instance
where
  instance_state = 'stopped'
  and state_change_time <= (current_date - interval '30' day);
```
