### ISSUE TITLE
S3 akas column should not hardcode the partition to `:aws:`

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe-plugin-aws#320]
**Describe the bug**

The akas column does not set the partition properly.

**Steampipe version (`steampipe -v`)**

N/A

**Plugin version (`steampipe plugin list`)**

Example: v0.12.0

**Additional context**

https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_s3_bucket.go#L575

**Comment by cbruno10** [comment]
There are also issues with hardcoding ARN formats in `table_aws_iam_policy.go` and `table_aws_ec2_instance_type.go`:

https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_iam_policy.go#L216
https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_ec2_instance_type.go#L289
