### ISSUE TITLE
`aws_ecr_repository` table not storing `Public` repositories

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-aws#334]
**Describe the bug**
Public repositories are not being stored in `aws_ecr_repository` table. Only storing `Private` repositories. Need to validate below use case:- 
Ensure there are no ECR repositories set as Public

**Steampipe version (`steampipe -v`)**
Example: v0.4.0

**Plugin version (`steampipe plugin list`)**
aws: v0.13.0

**To reproduce**
Create a repository as Public and check.

**Expected behavior**
It should insert that record in the table.

**Additional context**
![image](https://user-images.githubusercontent.com/43408569/115556356-3ae54a00-a2ce-11eb-93ba-72e4c41cbd2a.png)
![image](https://user-images.githubusercontent.com/43408569/115556429-4a649300-a2ce-11eb-9938-d419ece9d05b.png)

```
> select * from aws_ecr_repository;
+-----------------+--------------+---------------------------------------------------------+--------------------------------------------------------+---------------------+--------------------
| repository_name | registry_id  | arn                                                     | repository_uri                                         | created_at          | image_tag_mutabilit
+-----------------+--------------+---------------------------------------------------------+--------------------------------------------------------+---------------------+--------------------
| testing         | 632902152528 | arn:aws:ecr:ap-south-1:632902152528:repository/testing  | 632902152528.dkr.ecr.ap-south-1.amazonaws.com/testing  | 2021-04-21 12:17:13 | MUTABLE            
| dfgdfdfg        | 632902152528 | arn:aws:ecr:ap-south-1:632902152528:repository/dfgdfdfg | 632902152528.dkr.ecr.ap-south-1.amazonaws.com/dfgdfdfg | 2021-04-21 12:24:57 | MUTABLE            
+-----------------+--------------+------------------------------------------------------

**Comment by bigdatasourav** [comment]
will create a new table aws_ecrpublic_repository as ecrpublic is a separate service. In terraform also ecr and ecrpublic are separate resource

**Comment by cbruno10** [comment]
Will be handled in https://github.com/turbot/steampipe-plugin-aws/issues/342
