### ISSUE TITLE
Getting an error as `Error: NotFound: Topic does not exist, status code: 404` from aws_sns_topic_subscription table

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-aws#335]
**Describe the bug**
Execute the below query and got the above error.

```
select * from aws_sns_topic_subscription
Error: NotFound: Topic does not exist
	status code: 404, request id: 6a97ba47-7e3e-5ff1-b12b-e2bc1434b884
```

**Steampipe version (`steampipe -v`)**
 v0.4.0

**Plugin version (`steampipe plugin list`)**
aws: v0.13.0

**To reproduce**
Just execute the above query. Not sure if there any subscription in the account for which Topic doesn't exist. If that might be the case. 

**Additional context**

**Comment by rajmohanty17** [comment]
It works for me, may be revalidated again

**Comment by visiit** [comment]
It's working for me.
