### ISSUE TITLE
Using `cidr_ip` in a `group by` clause causes steampipe to hang

### ISSUE THREAD

**Issue by dboeke** [turbot/steampipe-plugin-aws#379]
**Describe the bug**
Running a query with `cidr_ip` as a group by column results in steampipe hanging with no result returned.

**Steampipe version (`steampipe -v`)**
Example: v0.4.1

**Plugin version (`steampipe plugin list`)**
```
+--------------------------------------------------+---------+-------------+
| NAME                                             | VERSION | CONNECTIONS |
+--------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/aws@latest       | 0.15.0  | aws         |
| hub.steampipe.io/plugins/turbot/steampipe@latest | 0.1.2   | steampipe   |
+--------------------------------------------------+---------+-------------+
```

**To reproduce**
Run the query:
```sql
select cidr_ip, count(*) from aws_vpc_security_group_rule group by 1
```

**Expected behavior**
Normal SQL group by result

**Additional context**
can test in account `899206412154` on demo

**Comment by bigdatasourav** [comment]
as discussed with Lalit , Kai need to check this.
