### ISSUE TITLE
Add integration test for table aws_ecs_container_instance

### ISSUE THREAD

**Issue by sayan133** [turbot/steampipe-plugin-aws#387]
**Is your feature request related to a problem? Please describe.**
Add an integration test for the existing table.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bigdatasourav** [comment]
terraform resource is not available , with CLI also facing issue. 
https://turbothq.slack.com/archives/G01PK0XKPRQ/p1620862906011000
