### ISSUE TITLE
Add tables for aws_audit_manager_*

### ISSUE THREAD

**Issue by tsangha** [turbot/steampipe-plugin-aws#390]
**References**
https://docs.aws.amazon.com/audit-manager/latest/APIReference/API_Operations.html

Considering that monitoring compliance is one of several enumerated steampipe value props, it might make sense to read data directly from AWS' recently introduced Audit Manager service. Audit Manager allows AWS customers to quickly gather evidence, assess compliance, and monitor ongoing risk in their cloud environment. Moreover, it ties those tasks (collectively, "assessments") to specific compliance frameworks like HIPAA, GDPR, or SOC2. Being able to track those frameworks and assessments via steampipe would be beneficial for organizations using steampipe to read data from multiple other organizations, such as audit firms, security firms, developer tools, etc. 

I think an interesting set of tables might be derived from the API actions below, though we might need to prioritize among them. Assessments, Frameworks, Evidence, and Controls being potentially the most interesting:

GetAccountStatus
GetAssessment
GetAssessmentFramework
GetAssessmentReportUrl
GetChangeLogs
GetControl
GetDelegations
GetEvidence
GetEvidenceByEvidenceFolder
GetEvidenceFolder
GetEvidenceFoldersByAssessment
GetEvidenceFoldersByAssessmentControl
GetOrganizationAdminAccount
GetServicesInScope
GetSettings
ListAssessmentFrameworks
ListAssessmentReports
ListAssessments
ListControls
ListKeywordsForDataSource
ListNotifications
ListTagsForResource

**Comment by cbruno10** [comment]
Hey @tsangha , thanks for raising this request!

Out of the tables above, it seems like assessments, frameworks, evidence, and controls are the ones you'd be interested in us adding first. I agree that these seem to have the most potential out of the resources above, so we'll have a look at those to start with and analyze the other resource types as well.

If you have any other requests or questions, please let us know, thanks!

**Comment by cbruno10** [comment]
@tsangha We've added several AWS Audit Manager tables, with the most recent one being `aws_auditmanager_evidence`, which will be released soon.

Were there any additional Audit Manager tables you were interested in?
