### ISSUE TITLE
Add table aws_audit_manager_assessment

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-aws#399]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

**Comment by cbruno10** [comment]
Related to https://github.com/turbot/steampipe-plugin-aws/issues/390

**Comment by visiit** [comment]
It's working on aws-cli but getting issue with steampipe i.e `Error: AccessDeniedException: Unable to determine service/operation name to be authorized`

**Comment by Priyanka585464** [comment]
I am currently working on this resource.List call is working fine and also i was getting response of get through List call.But there was some issue with Get call, the data was not getting fetch for some reason.So had a discussion ,came up with the solution.
So i will work on the test and docs and Make the PR ASAP.
