### ISSUE TITLE
Table aws_config_configuration_recorder should list for all the aws_regions and not only for regions mentioned in aws.spc file

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-aws#428]
**Describe the bug**
Table aws_config_configuration_recorder should list for all the aws_regions and not only for regions mentioned aws.spc file as this creating issue for AWS CIS.

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by cbruno10** [comment]
We should hold on this for now and keep the table regional.
