### ISSUE TITLE
Add tables for cost management

### ISSUE THREAD

**Issue by johnsmyth** [turbot/steampipe-plugin-aws#47]
potentially, cost explorer, pricing api, etc

**Comment by victorv1000** [comment]
Would love to see the ability to list reserved instances for EC2, RDS, Redshift, Elasticache, and Elasticsearch as part of the cost optimization pillar.

**Comment by cbruno10** [comment]
@victorv1000 The features associated with this issue did not include the reserved instance features you had requested, so I created https://github.com/turbot/steampipe-plugin-aws/issues/442 for tracking and discussion.
