### ISSUE TITLE
Getting error 'List' call requires an '=' qual for column: service_namespace from table aws_appautoscaling_target

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-aws#480]
**Describe the bug**
```
select * from aws_appautoscaling_target;
Error: 'List' call requires an '=' qual for column: service_namespace

```

**Steampipe version (`steampipe -v`)**
: v0.5.0

**Plugin version (`steampipe plugin list`)**
AWS: v0.18.0

**To reproduce**
Run above query

**Expected behavior**
no errors

**Additional context**
N/A

**Comment by Subhajit97** [comment]
@debabrat-git For this table, you need to pass `service_namespace` when you are running a query against this table.
`Expected query`
```
select * from aws_appautoscaling_target where service_namespace = '...';
```
