### ISSUE TITLE
aws_cloudtrail_trail table queries fail to get organization trails

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-aws#577]
**Describe the bug**
From a user in Slack:

> we have an organizational cloudtrail that gets "seen" from each aws account because its visible to that account. this makes steampipe confused

```
> select * from aws_cloudtrail_trail;
Error: 1 connection failed:
connection 'aws_schf': rpc error: code = Unknown desc = TrailNotFoundException: Unknown trail: arn:aws:cloudtrail:us-west-2:393097958779:trail/main for the user: 393097958779
> select * from aws_cloudtrail_trail;
Error: 1 connection failed:
connection 'aws_schf': rpc error: code = Unknown desc = CloudTrailARNInvalidException: AccountID in ARN is wrong, you can only access resources with AccountID 393097958779.
```

> This trail isn't created from within this account, it's created at the org level, but I think it's viewed via the APIs so I think steampipe is just confused by it.

**Steampipe version (`steampipe -v`)**
v0.7.0

**Plugin version (`steampipe plugin list`)**
v0.26.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**
The trail should be returned properly

**Additional context**

**Comment by rajlearner17** [comment]
We could replicate the issue of CloudTrailARNInvalidException, TrailNotFoundException, which is primarily happening for three API calls 
```
getCloudtrailTrailTags
getCloudtrailTrailEventSelector
getCloudtrailTrailStatus
```
As the org-trail is holding the ARN of the org-account, while the child account initiate the call it tries to find the child account-id in the ARN, this elevates to `Error: CloudTrailARNInvalidException: AccountID in ARN is wrong, you can only access resources with AccountID  123445566622`

similarly

'aws_cloudtrail_trail' failed to get column data: table 'aws_cloudtrail_trail' column 'is_logging' requires hydrate data from getCloudtrailTrailStatus, which failed with error `TrailNotFoundException`: Unknown trail: arn:aws:cloudtrail:us-east-1:123445566622:trail/cody-test-organizational-trail for the user: 123445566622. 

We are working on this fix.
