### ISSUE TITLE
Region do not match up in region and arn columns for aws_ec2_instance

### ISSUE THREAD

**Issue by jackdelab** [turbot/steampipe-plugin-aws#588]
**Describe the bug**
In the table `aws_ec2_instance`, the columns `region` and `arn` do not give the same region for instances not in us-east-1

> └─$ steampipe query "select region, arn from aws_ec2_instance where region != 'us-east-1'"
+-----------+-----------------------------------------------------------------+
| region         | arn                                                                                                          |
+-----------+-----------------------------------------------------------------+
| us-east-2 | arn:aws:ec2:us-east-1:5***********1:instance/i-0****************3 |
+-----------+-----------------------------------------------------------------+

**Steampipe version (`steampipe -v`)**
steampipe version 0.7.1

**Plugin version (`steampipe plugin list`)**
hub.steampipe.io/plugins/turbot/aws@latest       | 0.28.0

**To reproduce**

1. Create EC2 instance in us-east-2 region
2. `select region, arn from aws_ec2_instance`
3. columns do not give the same region name

**Expected behavior**
Region names should match in both columns

**Comment by e-gineer** [comment]
oh ... thanks for reporting @jackdelab ... this is a nasty bug that we seem to have introduced through more aggressive caching of the common column data :-(

In `getEc2InstanceARN` we use a cache around the common columns data - https://github.com/turbot/steampipe-plugin-aws/blob/62d70939046274c31f30c828ff2634b690509aa3/aws/table_aws_ec2_instance.go#L378

And in `getCommonColumns` we cache again, this time including the region - https://github.com/turbot/steampipe-plugin-aws/blob/62d70939046274c31f30c828ff2634b690509aa3/aws/common_columns.go#L121

We'll look into this issue ASAP and push out a patch for the plugin.

**Comment by cbruno10** [comment]
Hey @jackdelab , we just released v0.29.0, which includes a fix for this bug and https://github.com/turbot/steampipe-plugin-aws/issues/587, can you please install the new version and let us know if the issues are now resolved? Thanks!

**Comment by jackdelab** [comment]
Looks like the issue is gone on v0.29.0, very impressive getting that fixed so quickly!

**Comment by e-gineer** [comment]
Thanks @jackdelab for your ongoing feedback and raising the issues - it really helps!
