### ISSUE TITLE
Add managed_actions column to aws_elasticbeanstalk_environment table

### ISSUE THREAD

**Issue by misraved** [turbot/steampipe-plugin-aws#611]
**Is your feature request related to a problem? Please describe.**
AWS Elastic Beanstalk environment check is required in FSBP control.

**Describe the solution you'd like**
The addition of `managed_actions` column can help me query the data directly.

**Additional context**
https://docs.aws.amazon.com/config/latest/developerguide/elastic-beanstalk-managed-updates-enabled.html

**Comment by rajlearner17** [comment]
@karanpopat can you revisit this, we need this for [FedRAMP](https://docs.aws.amazon.com/config/latest/developerguide/elastic-beanstalk-managed-updates-enabled.html)
