### ISSUE TITLE
Add table for aws_ec2_instance - Ondemand Cost

### ISSUE THREAD

**Issue by sankeyraut** [turbot/steampipe-plugin-aws#632]
**Is your feature request related to a problem? Please describe.**
Add a column for ondemand hourly cost of the EC2 instance or a separate table will also help. 

**Describe the solution you'd like**
When we query the ec2 api, we would like to have a mechanism to get the hourly cost of the EC2 instance.  (irrespective of lifecycle). AWS Pricing API can be used here. 

https://docs.aws.amazon.com/sdk-for-go/api/service/pricing/

**Describe alternatives you've considered**
Alternate option is to use cost explorer API.

**Additional context**

**Comment by cbruno10** [comment]
Hi @sankeyraut , I'm sorry that we took so long to respond to this issue (almost 9 months)!

We do have a few cost tables available, like the [aws_cost_by_service_daily](https://hub.steampipe.io/plugins/turbot/aws/tables/aws_cost_by_service_daily) or [aws_cost_by_service_usage_type_daily](https://hub.steampipe.io/plugins/turbot/aws/tables/aws_cost_by_service_usage_type_daily), which can help you get cost across accounts or across an organization when querying the organization management account.

If you're using reserved instances, we also have some cost data in various columns in the [aws_ec2_reserved_instance](https://hub.steampipe.io/plugins/turbot/aws/tables/aws_ec2_reserved_instance).

After briefly looking at the Pricing API, the APIs feels rich enough that we'd most likely create separate tables to retrieve this data. For instance, as the Pricing APIs support filter capabilities, having separate tables with helpful key columns would allow for more efficient queries.

In regards to pricing data, is specific EC2 instance cost data the primary thing you're looking for? Are you typically looking to query this data for specific EC2 instances that exist, or do you have EC2 instance types in mind that you want to retrieve pricing data for?

Also, once you have pricing data for each instance, how do you plan to use this data? Would you take this pricing data and use it in another query, dashboard, or somewhere else? Or is this something you'd like to be able to see ad-hoc as you run other queries?

**Comment by yshollander-selerity** [comment]
I'll throw in my vote for adding a table based on the pricing API.  But it shouldn't be just EC2. I'm working on an cost analysis in advance of some RDS updates, and it would be nice if I had hourly cost (on demand as well as reserved or savings plan, as appropriate).  The existing cost tables are a good way to get the aggregated data, but it would be nice to see the hourly cost per resource.
