### ISSUE TITLE
Listing EC2 instances fails with status code: 400

### ISSUE THREAD

**Issue by RyanJarv** [turbot/steampipe-plugin-aws#634]
**Describe the bug**
When running `select * from aws_ec2_instances` steampipe exits with the following error after running for a bit.

```
Error: :
        status code: 400, request id:
```

This doesn't appear to happen outside a specific account, but so far haven't been able to narrow it down outside of that.

[Log during query part 1](https://gist.github.com/RyanJarv/d8882c6390debb0cfc5a85ad80ebe56e)
[Log during query part 2](https://gist.github.com/RyanJarv/d87df7f66f53a0578b96387d7009bfa2)

**Steampipe version (`steampipe -v`)**
steampipe version 0.7.3

**Plugin version (`steampipe plugin list`)**
 0.31.0

**To reproduce**
Currently haven't been able to reproduce this outside of a specific an environment. Will update if I can narrow this down though.

**Expected behavior**
Steampipe doesn't fail.

**Additional context**
The environment is fairly large so this fails sometime into the scan (unsure how long exactly, can double check soon and update). At least one attempt succeeded, so this doesn't appear to happen every time, but occured about 3 out of the 4 times attempted.

**Comment by rajlearner17** [comment]
@RyanJarv as mentioned already in slack, we are keeping a watch on it to understand the pattern, we already did a large-scale environment test and unfortunately could not replicate the same. However, keep us updated in case you have any further observations. Thanks again for helping here to improve.

**Comment by RyanJarv** [comment]
Was looking at the code and thinking this might be throttling, the aws_ec2_instance table makes a status request for each instance which may not be enough to trigger this but if something else is being used in the account at the same time this might make sense.

 It seems the retry behavior (https://github.com/turbot/steampipe-plugin-aws/blob/98bb1796fa18f4c120b983c7078d62fb269d6a4c/aws/service.go#L1532) doesn't currently back off, have seen this cause issues in the past where retrying without backing off isn't much better.
 
 This is just a guess of course, I'll retest with the updated error handling code to try to get more info.  Either way thinking it may be a good idea to log the retries as well, while code should be handling retries gracefully many times they aren't and knowing when you're hitting these limits is important for not (unnecessarily) causing issues in production.

**Comment by RyanJarv** [comment]
Looks like the status code for throttling is 429 however (https://aws.amazon.com/premiumsupport/knowledge-center/lambda-troubleshoot-throttling/). Not sure if the status code in the output is from the API or RPC though, should be able to check for this on Monday though.

**Comment by RyanJarv** [comment]
Was able to confirm this is what is happening. Seems I just got unlucky before and it failed on function that wasn't outputting the error, checked in CloudTrail and the DescribeInstanceStatus call is returning a RequestLimitExceeded error and below is the output from another run.


```
2021-08-30T10:31:12.716-0700 [ERROR] plugin.steampipe-plugin-aws.plugin: [ERROR] table 'aws_ec2_instance' failed to get column data: table 'aws_ec2_instance' column 'instance_initiated_shutdown_behavior' requires hydrate data from getInstanceInitiatedShutdownBehavior, which failed with error RequestLimitExceeded: Request limit exceeded.
2021-08-30 10:31:12.845 PDT [1194] ERROR:  2 connections failed:
        connection 'coinbase_bison': rpc error: code = Unknown desc = :
                status code: 400, request id:
        connection 'coinbase_bison_staging': rpc error: code = Unknown desc = :
                status code: 400, request id:
2021-08-30 10:31:12.845 PDT [1194] STATEMENT:  select * from aws_ec2_instance
2021-08-30 10:31:12.845 PDT [1194] LOG:  statement: ROLLBACK
2021-08-30 10:34:39.161 PDT [1338] LOG:  statement: ;
2021-08-30 10:34:39.162 PDT [1338] LOG:  statement: select count(*) from pg_stat_activity where client_port IS NOT NULL and application_name='steampipe' and backend_type='client backend';
2021-08-30 10:34:39.164 PDT [967] LOG:  received smart shutdown request
2021-08-30 10:34:39.164 PDT [967] LOG:  background worker "logical replication launcher" (PID 974) exited with exit code 1
2021-08-30 10:34:39.170 PDT [970] LOG:  shutting down
2021-08-30 10:34:39.173 PDT [967] LOG:  database system is shut down
```

So I think there's a few things that can be done here, backing off on the retries seems I think will help. AWS uses a token bucket to limit requests, so sleeping for a bit will allow the bucket to fill up a bit before trying again (https://docs.aws.amazon.com/AWSEC2/latest/APIReference/throttling.html).

Another thing I would need to be able to run Steampipe in certain environments is request limiting. So being able to limit the number of requests ran per second or something along those lines.

The last one is batching requests to API calls like DescribeInstanceStatus, it allows you to specify up to a 100 instances in one request. I think I looked into this for another table and there didn't seem to be an obvious way to do this currently, so not sure how feasible this would be but wanted to mention it since it would likely increase performance quite a bit and make it difficult to run into rate limiting issues like this (now that I think about it I suspect most of my issues with steampipe and large accounts in the past have been likely because of this issue).

Just wanted to throw these options out there, happy to submit PR's for some of these when I get some time as well.

**Comment by RyanJarv** [comment]
Was able to confirm this is what is happening. Seems I just got unlucky before and it failed on function that wasn't outputting the error, checked in CloudTrail and the DescribeInstanceStatus call is returning a RequestLimitExceeded error and below is the output from another run.


```
2021-08-30T10:31:12.716-0700 [ERROR] plugin.steampipe-plugin-aws.plugin: [ERROR] table 'aws_ec2_instance' failed to get column data: table 'aws_ec2_instance' column 'instance_initiated_shutdown_behavior' requires hydrate data from getInstanceInitiatedShutdownBehavior, which failed with error RequestLimitExceeded: Request limit exceeded.
2021-08-30 10:31:12.845 PDT [1194] ERROR:  2 connections failed:
        connection '<redacted profile 1>': rpc error: code = Unknown desc = :
                status code: 400, request id:
        connection '<redacted profile 2>': rpc error: code = Unknown desc = :
                status code: 400, request id:
2021-08-30 10:31:12.845 PDT [1194] STATEMENT:  select * from aws_ec2_instance
2021-08-30 10:31:12.845 PDT [1194] LOG:  statement: ROLLBACK
2021-08-30 10:34:39.161 PDT [1338] LOG:  statement: ;
2021-08-30 10:34:39.162 PDT [1338] LOG:  statement: select count(*) from pg_stat_activity where client_port IS NOT NULL and application_name='steampipe' and backend_type='client backend';
2021-08-30 10:34:39.164 PDT [967] LOG:  received smart shutdown request
2021-08-30 10:34:39.164 PDT [967] LOG:  background worker "logical replication launcher" (PID 974) exited with exit code 1
2021-08-30 10:34:39.170 PDT [970] LOG:  shutting down
2021-08-30 10:34:39.173 PDT [967] LOG:  database system is shut down
```

So I think there's a few things that can be done here, backing off on the retries seems I think will help. AWS uses a token bucket to limit requests, so sleeping for a bit will allow the bucket to fill up a bit before trying again (https://docs.aws.amazon.com/AWSEC2/latest/APIReference/throttling.html).

Another thing that would help with this issue is client side request limiting. So being able to limit the number of requests ran per second or something along those lines.

The last one is batching requests to API calls like DescribeInstanceStatus, it allows you to specify up to a 100 instances in one request. I think I looked into this for another table and there didn't seem to be an obvious way to do this currently, so not sure how feasible this would be but wanted to mention it since it would likely increase performance quite a bit and make it difficult to run into rate limiting issues like this (now that I think about it I suspect most of my issues with steampipe and large accounts in the past have been likely because of this issue).

Just wanted to throw these options out there, happy to submit PR's for some of these when I get some time as well.

**Comment by e-gineer** [comment]
Yes @RyanJarv you are exactly right ... Over the years, we've found `DescribeInstanceStatus` to be one of the most annoying APIs to work with at Turbot. It is used to get so many different pieces of data, but all subject to the same limit. It seems to be triggered here via `getInstanceInitiatedShutdownBehavior`:

https://github.com/turbot/steampipe-plugin-aws/blob/1e14b27a9e16e2f0dfd260ef47da62fe85593c4e/aws/table_aws_ec2_instance.go#L420

We have configured automated retry and backoff for AWS, which I'd believe should have been triggered here. Perhaps we've just got too many for it overall?

https://github.com/turbot/steampipe-plugin-aws/blob/1e14b27a9e16e2f0dfd260ef47da62fe85593c4e/aws/service.go#L1527

Your suggestion of batching the requests is an interesting one. I think it would have to be per-attribute but potentially for many instances. It's common we'd request pages of them together, so it should be feasible to do even a small delay to collect multiple requests into a single call. Definitely a good idea - thank you.

**Comment by RyanJarv** [comment]
> We have configured automated retry and backoff for AWS, which I'd believe should have been triggered here. Perhaps we've just got too many for it overall?

I should have linked this above but DefaultRetryer doesn't do the backing off part by default (https://github.com/aws/aws-sdk-go/blob/e2d6cb448883e4f4fcc5246650f89bde349041ec/aws/client/default_retryer.go#L23). So I believe it's sending requests as fast as they can fail (which likely is fairly fast).

> Your suggestion of batching the requests is an interesting one. I think it would have to be per-attribute but potentially for many instances. It's common we'd request pages of them together, so it should be feasible to do even a small delay to collect multiple requests into a single call. Definitely a good idea - thank you.

Curious how this would work. I assume this isn't possible with the current hydrate function behavior? If so are you referring to adding support for a separate type of hydrate function here or something along those lines?

**Comment by e-gineer** [comment]
@RyanJarv yes, you are right about the DefaultRetryer ... I thought we'd adjusted the retry rate, but should have confirmed. We'll change that to something more aggressive in backoff. Good catch, thanks.

Correct ... a wrapper that would delay and queue for a short period (e.g. 100ms) or max items (100). It will then send the requests as a single batch and return them. It could actually make a surprising difference to performance at scale, particularly since the same API is used for multiple different pieces of data. It will reduce the API calls a lot and reduce the associated backoff performance penalty. This will need a little more thought.
