### ISSUE TITLE
Add table aws_workspaces_workspace

### ISSUE THREAD

**Issue by mosburn** [turbot/steampipe-plugin-aws#679]
I have a ton of workspaces that need to be managed and categorized, this would be a great help. 

**References**
Terraform: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/workspaces_workspace
Golang: https://docs.aws.amazon.com/sdk-for-go/api/service/workspaces/

**Comment by bigdatasourav** [comment]
@mosburn Thank you for raising this request, the table will be available in this week's release.
