### ISSUE TITLE
Add table aws_elasticache_redis_metric_cpu_utilization_daily

### ISSUE THREAD

**Issue by sankeyraut** [turbot/steampipe-plugin-aws#691]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.
Engine level cloudwatch metric of EngineCPUUtilization can be considered

https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheMetrics.Redis.html

**Comment by rajlearner17** [comment]
@sankeyraut thanks for using steampipe and having this issue raised. We will evaluate this and take action. Meanwhile, let us know if we are expecting any further contribution from you 👍

**Comment by sankeyraut** [comment]
Yes.. will start the work this week and send you a PR

**Comment by sankeyraut** [comment]
PR : https://github.com/turbot/steampipe-plugin-aws/pull/753
