### ISSUE TITLE
Add `policy` and `policy_std` columns to the aws_glue_catalog_database table

### ISSUE THREAD

**Issue by misraved** [turbot/steampipe-plugin-aws#719]
Add the column `policy` and `policy_std` to the table which will include the information pertaining to the Glue Data Catalog resource policy for access control.

**Comment by c0d3r-arnab** [comment]
We need to raise an issue to get policy related to the resource using resource arn as the data is not coming.

**Comment by rajlearner17** [comment]
AWS has replicated the issue, now it's pending with them, lets work on an alternative else we mark this blocked [CASE 9203313011] Glue - get-resource-policy resource CLI outcome

**Comment by karanpopat** [comment]
The API and CLI for `get-resource-policy` are not returning any results for the glue database resource.
