### ISSUE TITLE
The cpu and memory fields should be numbers instead of text

### ISSUE THREAD

**Issue by mildebrandt** [turbot/steampipe-plugin-aws#727]
In the `aws_ecs_task` table, I'd like to see `cpu` and `memory` as number columns. The results from the aws cli come back as strings, but they are numbers. For example:

```
$ aws ecs describe-tasks --cluster <redacted cluster name> --tasks <redacted task arn>

<snip>
            "cpu": "512",
            "createdAt": 1635287601.393,
            "desiredStatus": "RUNNING",
            "enableExecuteCommand": false,
            "healthStatus": "UNKNOWN",
            "lastStatus": "RUNNING",
            "launchType": "FARGATE",
            "memory": "1024",
<snip>
```

**Comment by rajlearner17** [comment]
@mildebrandt thanks for so quick check and sharing us with immediate input appreciate it. We are looking into this feasibility, will make appropriate actions.
