### ISSUE TITLE
Incorrect data type for aws_ssm_managed_instance.platform_version

### ISSUE THREAD

**Issue by bryanburke** [turbot/steampipe-plugin-aws#731]
**Describe the bug**
The `aws_ssm_managed_instance.platform_version` field has the incorrect data type in the schema. The plugin currently defines that field as `bigint`; however, the [SSM DescribeInstanceInformation API response](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_DescribeInstanceInformation.html#API_DescribeInstanceInformation_ResponseSyntax) contains `PlatformVersion` as `string` data type.

This is causing `ParseInt` to fail on version strings that are not integers. For example, when trying to query the table in an account with SSM-managed Ubuntu 16.04 EC2 instances:

```text
Warning: executeQueries: query 1 of 1 failed: pq: 1 connection failed: connection 'aws': rpc error: code = Unknown desc = interfaceToColumnValue failed for column 'platform_version': strconv.ParseInt: parsing "16.04": invalid syntax
```

**Steampipe version (`steampipe -v`)**
0.9.0

**Plugin version (`steampipe plugin list`)**
0.38.0

**To reproduce**
1. Launch an Ubuntu EC2 instance with at least the **AmazonSSMManagedInstanceCore** managed IAM policy in its instance profile role (see [here](https://docs.aws.amazon.com/systems-manager/latest/userguide/setup-instance-profile.html)).
2. Wait for the instance to boot and show up in the SSM Fleet Manager console.
3. Set up your CLI profile with read-only access into the AWS account, and configure the Steampipe plugin appropriately.
4. Query the `aws_ssm_managed_instance` table: `steampipe query "select count(*) as n from aws_ssm_managed_instance"`

**Expected behavior**
The `aws_ssm_managed_instance` table does not try to parse the `platform_version` field as an integer but instead simply passes it through as a string.

**Comment by e-gineer** [comment]
Thanks @bryanburke for letting us know! Good catch :-)

I believe the bug is in this line of code:

https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_ssm_managed_instance.go#L110
