### ISSUE TITLE
Nil interface panic errors on s3TagsToTurbotTags transform for aws_s3_bucket table

### ISSUE THREAD

**Issue by MichaelBurgess** [turbot/steampipe-plugin-aws#739]
**Describe the bug**
After upgrading from plugin version 0.38.0 to 0.38.1 I am getting the following error:

```
Error: 2 connections failed:
connection 'aws_foo': rpc error: code = Unknown desc = failed to populate column 'tags': rpc error: code = Internal desc = transform s3TagsToTurbotTags failed with panic interface conversion: interface {} is nil, not []*s3.Tag
connection 'aws_bar': rpc error: code = Unknown desc = failed to populate column 'tags': rpc error: code = Internal desc = transform s3TagsToTurbotTags failed with panic interface conversion: interface {} is nil, not []*s3.Tag
```

**Steampipe version (`steampipe -v`)**
v0.9.0 (installed via homebrew)

**Plugin version (`steampipe plugin list`)**
v0.38.1

**To reproduce**
Upgrade Steampipe + AWS plugin to the above versions. Set up 1 or more AWS connection(s) and run `select * from <schema>.aws_s3_bucket`.

**Expected behavior**
Query returns results with no errors

**Additional context**
Running on Apple M1 Pro mac - should not be the cause though as was working fine on plugin version 0.38.1

**Comment by rajlearner17** [comment]
@MichaelBurgess thanks for checking this out. We are looking into this.

**Comment by misraved** [comment]
@MichaelBurgess The issue was rooted in the steampipe plugin SDK (v1.7.1). This has now been fixed (https://github.com/turbot/steampipe-plugin-sdk/blob/main/CHANGELOG.md#v173--2021-11-08). The latest version of this plugin(0.38.2) should fix the issue.

**Comment by MichaelBurgess** [comment]
Thanks for the quick turnaround @kaidaguerre / @LalitTurbot / @rajlearner17 / @misraved!
