### ISSUE TITLE
Add example queries to doc for `aws_cloudwatch_log_event` using filter for more efficient querying

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-aws#744]
**Is your feature request related to a problem? Please describe.**
When using the `aws_cloudwatch_log_event` table for the first time, queries take a while to run with large log groups.

**Describe the solution you'd like**
I'd like to see some examples on how to query the `aws_cloudwatch_log_event` table using the built-in AWS filter language for faster and more efficient queries.

**Describe alternatives you've considered**
Trying to figure out AWS log filters myself, which can be difficult.

**Additional context**

**Comment by e-gineer** [comment]
This is specifically for the `aws_cloudwatch_log_event` table and use of the `filter` column.
