### ISSUE TITLE
Verify `aws_sfn_state_machine_execution` table is using optimized API calls and sequencing is correct

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-aws#784]
The `aws_sfn_state_machine_execution` table uses a parent hydrate from the `aws_sfn_state_machine` table, which can cause throttling today when listing out executions for all machines, e.g., `select name, status, start_date, stop_date from aws_sfn_state_machine_execution`. This can take even longer when getting the `input` column as well.

We should test queries from this table, and from other tables in the service, to confirm that the design of the tables is optimized to reduce throttling. If there are any optional quals we can leverage, we should add them as well.

**Comment by rajlearner17** [comment]
@cbruno10 Makes sense - we will check this out.

**Comment by bigdatasourav** [comment]
sfn_* tables optimization has been done in qual phase-4 [PR](https://github.com/turbot/steampipe-plugin-aws/pull/873), closing this issue.
