### ISSUE TITLE
aws_vpc_security_group_rule contains no prefixlistids column, and no rows for rules that only contain prefixlistids

### ISSUE THREAD

**Issue by johnsmyth** [turbot/steampipe-plugin-aws#800]
**Describe the bug**
aws_vpc_security_group_rule contains no prefixlistids column, and no rows for rules that only contain prefixlistids.

security group rules table doesn't pull in prefixlist IDs so the output appears to contain less rules when there are actually rules within the target security group

**Steampipe version (`steampipe -v`)**
any

**Plugin version (`steampipe plugin list`)**
0.41.0

**Additional context**

**Comment by rajlearner17** [comment]
@johnsmyth we analyzed the requirement, seems to have the column in `aws_vpc_security_group_rule` and additionally new table `aws_ec2_managed_prefix_list` would be helpful to fetch more details about prefix-list.
