### ISSUE TITLE
aws_ec2_instance issue with user_data when not UTF-8

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-plugin-aws#809]
## Description
This issue occurs when the `user_data` field on the `aws_ec2_instance` table would return non-UTF-8 data, essentially you receive the below error in this event.

`ERROR: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8`

However, this was discovered when we attempted to pull back the information for some EC2 instances that're running CICD Build Runners for GitLab where the `user_data` seemingly returns data which is not a valid UTF-8 string.

### Reproduction
The relevant query was as simple as (on an account with an EC2 instance that has non-UTF8 user data):
```sql
select instance_id, user_data from profile.aws_ec2_instance
```

Confirmation of error was obtained by verifying the returned data from the AWS CLI (with a little help from `jq` - I've censored our instance-id and profile names)
`aws ec2 describe-instance-attribute --attribute userData --instance-id i-0000000000000f000 --profile profile | jq '.UserData.Value | @base64d'`

Where this would normally return something readable like `"MIME-Version: 1.0\r\nContent-Type: multipart/mixed;` (snipped for brevity).  What was actually returned was a longer version of `\u0005�r�/%\u0006�\u0003���\u0016XEs�`

### Additional Context
The column is populated by obtaining the data from a specific hydrate function [getInstanceUserData](https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_ec2_instance.go#L576) and performing a [base64DecodedData transform](https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_ec2_instance.go#L258) this should [return `nil, nil` in the event of an error](https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/utils.go#L155) - however that doesn't seem to be the case, else I would be expecting a null value in the data.

### Expected Result
Based on the information outlined in the `Additional Context` I would expect a null/empty field for `user_data` when there's an error decoding the base64 value to a `string` type.

### Actual Result
`ERROR: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8`

### Version Information
`steampipe version 0.10.0`
`hub.steampipe.io/plugins/turbot/aws@latest  0.41.0`

**Comment by bigdatasourav** [comment]
@graza-io thank you for highlighting this with us, will reproduce and check.

**Comment by bigdatasourav** [comment]
@graza-io can you please help us try this out associated [PR](https://github.com/turbot/steampipe-plugin-aws/pull/812) and confirm all works as expected?
