### ISSUE TITLE
Poorly worded error message: `Connection config have invalid regions`

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe-plugin-aws#810]
in `multi_region.go`

**Comment by misraved** [comment]
Fixed in https://github.com/turbot/steampipe-plugin-aws/commit/aa20790ee7fde3163a4ce34da4a220589e275e66#diff-2f903e225b71b6777e3c3b12779a31cfb1f6a74daa40a2abc870dcc3f5a15893
