### ISSUE TITLE
Better distinguish aws_organizations_account.account_id and aws_organizations_account.id in documentation

### ISSUE THREAD

**Issue by bryanburke** [turbot/steampipe-plugin-aws#823]
**Is your feature request related to a problem? Please describe.**
Not related to a problem with functionality.

**Describe the solution you'd like**
The [aws_organizations_account table documentation](https://hub.steampipe.io/plugins/turbot/aws/tables/aws_organizations_account#inspect) has descriptions for the `account_id` and `id` columns that are a bit vague, IMO.

From my experience querying this table, I observe the following:

- `account_id` is the ID of the account **making the API request**.
  - Current description: `The AWS Account ID in which the resource is located.`
  - The "resource" in this case is the organization root/master account itself (see below).
- `id` is the ID of the account the API **is describing**.
  - Current description: `The unique identifier (ID) of the account.`

I believe this difference is due to an eccentricity of the AWS Organizations API's design--namely, that only the organization root/master account can perform the ListAccounts call (as opposed to the DescribeOrganization call, which any account in the organization can perform).

I also believe this difference, though subtle, is very important. Effectively, `account_id` on this table is always the organization's root/master account ID.

I would like to request that the descriptions of the `account_id` and `id` columns on this table be updated to reflect more clearly what their values represent, as above.

**Describe alternatives you've considered**
Another possible approach may be to add a new column named `organization_master_account_id` or similar that simply mirrors the value of `account_id` but more clearly defines the meaning of the value. That said, I do not recommend changing `account_id`'s value, as doing so may break applications that rely on its being the organization root/master account ID (like the app I just implemented 😅).

**Additional context**
No additional context to provide. Steampipe is an incredibly powerful tool and an absolute joy to use!

**Comment by misraved** [comment]
Thanks @bryanburke for highlighting the confusion in the descriptions. 

Your suggestion makes a lot of sense, we will review them and try to get the descriptions updated so that all the confusion can be mitigated 👍 

Great to see you working across AWS Organization tables 😃 . Please do let us know in case you stumble upon something suspicious 👍

**Comment by cbruno10** [comment]
Hey @bryanburke , sorry for the radio silence on this issue.

Unfortunately, the `account_id` column is one we define once for all AWS tables (https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/common_columns.go#L28-L34), so it's not possible to change this column just for the `aws_organizations_account` table.

I've pushed in a [commit](https://github.com/turbot/steampipe-plugin-aws/commit/6baa5cf70c6e4096b5320bb3e1c782ff37219672
) to update the `id` column description and the [aws_organizations_account table doc](https://hub.steampipe.io/plugins/turbot/aws/tables/aws_organizations_account) that hopefully helps to clarify the difference between the two columns.

This should be released in v0.58.0 in the next few days. If you still find the messaging confusing or have another suggestion, please let us know!
