### ISSUE TITLE
Connection config have invalid regions: ap-southeast-3

### ISSUE THREAD

**Issue by johnsmyth** [turbot/steampipe-plugin-aws#825]
**Describe the bug**
When using a wildcard in the `regions` argument in the aws plugin, MANY tables return an error:  `Connection config have invalid regions: ap-southeast-3`.  In fact, when running the cis benchmark in the aws_compliance , half the controls return this error.

**Steampipe version (`steampipe -v`)**
steampipe version 0.11.0-dev.1

**Plugin version (`steampipe plugin list`)**
aws plugin  0.41.0  

**To reproduce**
Create a connection with a wildcard in the region list:
```hcl
connection "aws_bad" {
  plugin    = "aws"  
  profile   = "my_profile"
  regions   =  ["*"]
}
```
Run a query `select * from aws_vpc_security_group`
or Run the cis benchamrk in the aws compliance: `steampipe check benchmark.cis_v140 `

**Expected behavior**
Should not error

**Additional context**

**Comment by cbruno10** [comment]
@johnsmyth I've added in `ap-southeast-3` as a valid region in the various hardcoded lists of regions we maintain in the code.

We still have not done full integration testing for all services/resources against this region, but this will stop all queries from failing when using a wildcard in the `region` config argument. We're planning on updating how we do valid region checks in a future change in https://github.com/turbot/steampipe-plugin-aws/issues/826.
