### ISSUE TITLE
Queries against aws_ebs_snapshot are not returning results for aws ap-southeast-2 region

### ISSUE THREAD

**Issue by dboeke** [turbot/steampipe-plugin-aws#831]
**Describe the bug**
Queries against aws_ebs_snapshot are not returning results in the ap-southeast-2 region

**Steampipe version (`steampipe -v`)**
v0.10.0

**Plugin version (`steampipe plugin list`)**
v0.41.0

**To reproduce**
1) Create a snapshot in ap-southeast-2
2) query `select title, region from aws_ebs_snapshot`

**Expected behavior**
Returns results from existing snapshots.

**Comment by misraved** [comment]
Thanks @dboeke for raising this issue. I have successfully managed to replicate it. 

We will look to fix this up and get it released soon.

**Comment by dboeke** [comment]
@misraved @rajlearner17  the current version of the plugin `0.42.2` is returning zero results for `select title, region from aws_ebs_snapshot` for `us-east-1` & `ap-southeast-2`, while 0.41.0 and 0.42.0 are working fine.  Please revisit this issue.

**Comment by misraved** [comment]
@dboeke We have figured out the issue, it will be fixed in the latest release 👍
