### ISSUE TITLE
Incorrect value returned for `aws_ec2_ami` table

### ISSUE THREAD

**Issue by dboeke** [turbot/steampipe-plugin-aws#840]
**Describe the bug**
Trying to find all AMI's that exist in a particular AWS account, using the "self" attribute. Per the docs:  https://hub.steampipe.io/plugins/turbot/aws/tables/aws_ec2_ami 

```
image_owner_alias | text | The AWS account alias (for example, amazon, self) or the AWS account ID of the AMI owner.
```

However the actual results are returning `<null>` instead of `self`

**Steampipe version (`steampipe -v`)**
 v0.10.0

**Plugin version (`steampipe plugin list`)**
 v0.42.2 

**To reproduce**
1. Create an ami owned by the local account
2. query:  ```sql
select title, image_owner_alias from aws_ec2_ami where public = 'false'```

**Expected behavior**
Should return a list of local amis with any owned by the local account having `self` in `image_owner_alias`

**Additional context**
https://steampipe.slack.com/archives/C01UECB59A7/p1639956521079700

**Comment by rajlearner17** [comment]
@dboeke tanks for testing this out. We are looking into this.
