### ISSUE TITLE
cant join `aws_ec2_ami_shared` table on `image_id` even though its the Get KeyColumn

### ISSUE THREAD

**Issue by johnsmyth** [turbot/steampipe-plugin-aws#845]
**Describe the bug**
The `image_id` is the KeyColumn for Get.  Running a simple `select * from aws_ec2_ami_shared where image_id='ami-0d5eff06f840b45e9'`  works as expected. Attempting to join on the `image_id` results in error: ` 'List' call is missing required quals: column:'owner_id' operator: =`

@kaidaguerre Im not sure if this is an FDW issue (feels like one?)

**Steampipe version (`steampipe -v`)**
steampipe version 0.11.0-rc.1

**Plugin version (`steampipe plugin list`)**
hub.steampipe.io/plugins/turbot/aws@latest   0.43.0 

**To reproduce**
```
> select instance_id, i.image_id, a.* from aws_ec2_instance as i left join aws_ec2_ami_shared as a on i.image_id=a.image_id and a.account_id = i.account_id
Error: 1 connection failed: 
connection 'aws': rpc error: code = Internal desc = 'List' call is missing required quals: column:'owner_id' operator: =
```

```
> select * from aws_ec2_ami_shared where image_id='ami-0d5eff06f840b45e9'
+-----------------------------------------+-----------------------+-----------+------------+------------------------------------------------+------------------
| name                                    | image_id              | state     | image_type | image_location                                 | creation_date    
+-----------------------------------------+-----------------------+-----------+------------+------------------------------------------------+------------------
| amzn2-ami-hvm-2.0.20210427.0-x86_64-gp2 | ami-0d5eff06f840b45e9 | available | machine    | amazon/amzn2-ami-hvm-2.0.20210427.0-x86_64-gp2 | 2021-04-29T05:14:
+-----------------------------------------+-----------------------+-----------+------------+------------------------------------------------+------------------
(END)

```
**Expected behavior**
`select instance_id, i.image_id, a.* from aws_ec2_instance as i left join aws_ec2_ami_shared as a on i.image_id=a.image_id and a.account_id = i.account_id` should run successfully

**Additional context**

**Comment by johnsmyth** [comment]
@kaidaguerre Ineterstingly, simple adding the  `image_id` to `ListConfig.KeyColumns` sees to. fix the issue.  See the issue-845 branch -- https://github.com/turbot/steampipe-plugin-aws/commit/92d67ee4d8c316e49b897500bd424eef320b6f8e

**Comment by cbruno10** [comment]
Re-opening to take another look

**Comment by hcsu** [comment]
Hello, any update on this? 
Seems we are not able to list all the instances with AMI description just in one SQL?

**Comment by bigdatasourav** [comment]
Hey @hcsu, we are working on this issue and will provide an update soon.

**Comment by bigdatasourav** [comment]
Hey @hcsu, we have provided a fix in this [PR](https://github.com/turbot/steampipe-plugin-aws/pull/1535); it will be released soon. Until then, if you want to try it out and share your feedback, please follow the below steps.

```
1. git clone https://github.com/turbot/steampipe-plugin-aws.git
2. cd steampipe-plugin-aws
3. git checkout issue-845
4. make
5. Run your query
(Note in case you have already this checked out aws-plugin repo, prefer to checkout main > git pull > git checkout issue-845 branch)
```
