### ISSUE TITLE
select * from aws_wellarchitected_workload fails

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-aws#858]
**Describe the bug**

`aws_wellarchitected_workload` does stops in `⠼ Loading results... ` followed by

```
> select * from aws_wellarchitected_workload
Error: RequestError: send request failed
caused by: Post "https://wellarchitected.ap-northeast-3.amazonaws.com/workloadsSummaries": dial tcp: lookup wellarchitected.ap-northeast-3.amazonaws.com: no such host (SQLSTATE HV000)
>
```

**Steampipe version (`steampipe -v`)**
Example: v0.11.2

**Plugin version (`steampipe plugin list`)**
Example: v0.44.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).
Execute `select * from aws_wellarchitected_workload`

**Expected behavior**

**Additional context**

**Comment by rajlearner17** [comment]
@defec8edc0de Thanks for raising this part of your testing. Adding this track separately.  [Reference](https://github.com/turbot/steampipe-plugin-aws/issues/855)

**Comment by bigdatasourav** [comment]
As of now, AWS endpoints package does not provide support for `well-architected` service. AWS GO SDK issue [reference](https://github.com/aws/aws-sdk-go/issues/4262).
