### ISSUE TITLE
Add S3 Storage Lens support

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-aws#879]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

[S3 Storage Lens ](https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage_lens.html)

https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.42.25/service/s3control#S3Control.GetStorageLensConfiguration
https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.42.25/service/s3control#S3Control.ListStorageLensConfigurations

![image](https://user-images.githubusercontent.com/26873346/152329704-59769803-b319-44a5-8072-b0d0950dda53.png)

![image](https://user-images.githubusercontent.com/26873346/152330300-04cd1011-2611-4545-8562-ca7e87c05a23.png)

**Comment by cbruno10** [comment]
Re-adding the `stale` label, as the intent of marking issues as stale is to help keep the issue list light + focused. If this feature request comes up again or is required for a new benchmark, control, etc., then we can remove the `stale` label.
