### ISSUE TITLE
Page layout seems to be incorrect for below list of tables

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-aws#88]
Incorrect layout:-
1-  Table: aws_iam_access_advisor
![image](https://user-images.githubusercontent.com/43408569/109645434-d4b93200-7b7c-11eb-9540-5478153222fd.png)
2- Table: aws_iam_policy_simulator
![image](https://user-images.githubusercontent.com/43408569/109645534-fdd9c280-7b7c-11eb-9b95-3fad178661ab.png)
3- Table: aws_ec2_load_balancer_listener
![image](https://user-images.githubusercontent.com/43408569/109645651-26fa5300-7b7d-11eb-94ba-6bb5f2aeb9f2.png)
Correct layout :-
![image](https://user-images.githubusercontent.com/43408569/109645781-4f824d00-7b7d-11eb-95c4-3aeb1fd9a706.png)

**Comment by debabrat-git** [comment]
One more found
![image](https://user-images.githubusercontent.com/43408569/109778974-79924880-7c2b-11eb-846f-075a2f444135.png)

**Comment by cbruno10** [comment]
@debabrat-git I believe this is an issue for steampipe.io, can you please re-open this issue there? Thanks!
