### ISSUE TITLE
Optimize the child tables list API calls

### ISSUE THREAD

**Issue by bigdatasourav** [turbot/steampipe-plugin-aws#885]
**Is your feature request related to a problem? Please describe.**
The child tables list API calls can be further optimized if the column which is coming from the ParentaHydrate call, will be added as an optional filter column in child tables.

If the user provides information for that column, API calls can be restricted based on that information.

reference - https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_ssoadmin_permission_set.go#L121

**Comment by ParthaI** [comment]
Standardise the Empty check format for quals column if required.

**Comment by cbruno10** [comment]
Removing stale label and re-assigning to @LalitTurbot for now, as he's focusing on improving the AWS plugin at the moment.
