### ISSUE TITLE
AWS SSM Parameter - Gracefully Handle When Parameters are Encrypted and Steampipe Doesn't Have KMS Access

### ISSUE THREAD

**Issue by twratl** [turbot/steampipe-plugin-aws#904]
**Describe the bug**
When steampipe comes across a SSM parameter that is encrypted and there is not KMS access, and error is thrown instead of gracefully handling that edge case and moving on to the next parameter.

**Steampipe version (`steampipe -v`)**
Example: v0.12.2

**Plugin version (`steampipe plugin list`)**
Example: v0.48.0

**To reproduce**
select * from aws_ssm_parameter

**Expected behavior**
place NULLs in the field or just show the encrypted value perhaps, without trying to decrypt?

**Additional context**
Warning: executeQueries: query 1 of 1 failed: ERROR: rpc error: code = Unknown desc = AccessDeniedException: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access. (Service: AWSKMS; Status Code: 400; Error Code: AccessDeniedException; Request ID: 6cbe00d5-xxxx-xxxx-xxxx-eaxxxxxxxxx; Proxy: null)

**Comment by cbruno10** [comment]
Hey @twratl , we've been having some discussions on how to handle access denied errors better in https://github.com/turbot/steampipe-plugin-aws/issues/878; the situation isn't exactly the same as your's, but I believe the discussion around expectations and what values a user would expect is relevant.

I think in this case, returning `null` could be confusing when returned as the value, but returning the encrypted value could still give a clear indication of what happened, i.e., the table tries to get the most exact value possible (which in this case is the decrypted value), but will return a less clear version if access is not granted.

We'll do some testing from our end to see what these results look like and if there are any edge cases, thanks for opening the issue and the suggestions!

**Comment by twratl** [comment]
Agree on `null` being confusing. But I guess also returning the encrypted field could violate some guardrails/principals/regulations depending on the use case. In this specific case it feels like injecting a value of `<encrypted:not showing value>` or something along those lines would make sense. That helps ensure that encrypted data is not being stored outside of pre-defined controls. Perhaps do this regardless of whether steampipe has access to the KMS key or not...if the parameter is encrypted just inject some default value and move on.

**Comment by cbruno10** [comment]
Hey @twratl , we've recently added the `ignore_error_codes` config arg as part of v0.60.0. I believe if you add this config arg with the `AccessDeniedException` error code in, any SSM params we can't decode will now be skipped instead of throwing an error. I believe this approach is better than substituting values, as it's unclear/unusual for Steampipe to do this for column data.

If you still see an issue with this config arg enabled, feel free to re-open. Thanks!
