### ISSUE TITLE
Add table aws_vpc_eni

### ISSUE THREAD

**Issue by cjsrkd3321** [turbot/steampipe-plugin-aws#909]
**References**
https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-network-interfaces.html

Hello. I'd like to get ENIs for managing security groups with ENIs based.

Thanks.
Best regards.

**Comment by misraved** [comment]
Hello @cjsrkd3321, Thanks for raising this request.

We appreciate all your contributions and feedback 👍 . We will look to get this table out soon.

**Comment by cbruno10** [comment]
Hi @cjsrkd3321 , ENIs are already available in the `aws_ec2_network_interface` table. There is an example of working with ENI + security group data in https://hub.steampipe.io/plugins/turbot/aws/tables/aws_ec2_network_interface. If you have any other questions, please let us know here or in Slack!

**Comment by cjsrkd3321** [comment]
OMG! I couldn't find that. thanks for your commend!! 😀
