### ISSUE TITLE
Add column status_reason_code to table aws_securityhub_standards_subscription

### ISSUE THREAD

**Issue by iainelder** [turbot/steampipe-plugin-aws#929]
The [GetEnabledStandards](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_GetEnabledStandards.html) API now outputs a [StatusReasonCode](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_StandardsStatusReason.html) with valid values `NO_AVAILABLE_CONFIGURATION_RECORDER | INTERNAL_ERROR`.

It would help to diagnose subscriptions that are not in a ready state.

**Comment by rajlearner17** [comment]
@iainelder Thanks for using Steampipe!! 
We are actively working on it, will keep you posted. Thank you

**Comment by cbruno10** [comment]
@iainelder We've added the `standards_status_reason_code` column to the `aws_securityhub_standards_subscription` table in v0.51.0. If you run into any issues, please let us know, thanks!

**Comment by iainelder** [comment]
Works for me!

Can we include the new column in the example query "[list standards whose status is not ready](https://hub.steampipe.io/plugins/turbot/aws/tables/aws_securityhub_standards_subscription#list-standards-whose-status-is-not-ready)?

```
select
  name,
  standards_arn,
  standards_subscription_arn,
  standards_status,
  standards_status_reason_code
from
  aws_securityhub_standards_subscription
where
  standards_status <> 'READY';
  ```

**Comment by cbruno10** [comment]
@iainelder Thanks for the suggestion, I just updated the doc, so in our next release the Hub doc will be updated.
