### ISSUE TITLE
Add column storage_type in  aws_rds_db_cluster_snapshot

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-aws#939]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

Add the Storage Type info for the RDS DB Cluster snapshot  same as `aws_rds_db_snapshot` table
![image](https://user-images.githubusercontent.com/26873346/161054695-43f46bff-4d39-40db-9256-3ad9d8eead51.png)

**Comment by karanpopat** [comment]
There is no storage type associated with db cluster snapshots. Only db instance snapshots have storage type associated with it. 
![image](https://user-images.githubusercontent.com/16674560/171016722-665d865b-ea87-4a0d-9ddb-7737a99d943c.png)
