### ISSUE TITLE
Add table aws_lambda_log_event

### ISSUE THREAD

**Issue by vkumbha** [turbot/steampipe-plugin-aws#941]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

Trying to get the json format of the message in [aws_cloudwatch_log_event](https://hub.steampipe.io/plugins/turbot/aws/tables/aws_cloudwatch_log_event) I see there is a column message_json but doesn’t help. This is because the Lambda logs are of type text. Would like to have a JSON format for the log files. 

![image](https://user-images.githubusercontent.com/40973863/161230323-01ca9829-78f5-4413-bdd2-9983b1517e08.png)

Can you please add a new table `aws_lambda_log_event` which automatically parses the cloudwatch events behind the scenes and returns the data in specifically designed columns. (See aws_cloudtrail_trail_event as an example.)

**Comment by rajlearner17** [comment]
@vkumbha Thanks for checking this out. We will work on it.

**Comment by ParthaI** [comment]
[The API](https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.42.25/service/cloudwatchlogs#CloudWatchLogs.FilterLogEventsPages) is being use in the table [aws_cloudwatch_log_event](https://hub.steampipe.io/plugins/turbot/aws/tables/aws_cloudwatch_log_event).

The response contains a field `message` which is a string type, we are doing Unmarshal for getting other column values, but if the value of the message property is not a valid JSON then it throws error/ return null data. Which looks like a issue from api end.
