### ISSUE TITLE
SharedConfigAssumeRoleError when chaining roles

### ISSUE THREAD

**Issue by as-bt** [turbot/steampipe-plugin-aws#954]
**Describe the bug**
I am receiving the following error while using role based credentials in a primary account to access a series of secondary accounts via STS:AssumeRole.

`ERROR: rpc error: code = Unknown desc = SharedConfigAssumeRoleError: failed to load assume role for {ROLE}, source profile {PROFILE} has no shared credentials (SQLSTATE HV000)`

Based on my initial research of the error, it looks like it is originating from the go aws sdk.
Threads referencing the same error:
https://github.com/99designs/aws-vault/issues/410
https://github.com/aws/aws-sdk-go/issues/2063

I was successfully able to authenticate and pull data from various secondary accounts using the aws cli utility.

**Steampipe version **
0.13.6

**Plugin version**
0.54.0

**Comment by cbruno10** [comment]
Hey @as-bt , thanks for the report!

Would you be able to share your `aws.spc` config file here (with any sensitive information removed)? This would help us reproduce and test the issue from our side, and see if we can figure out any workarounds. Thanks!

**Comment by as-bt** [comment]
Hey, here are some details regarding the credential set up. Hopefully it is of use.

Sample from `aws.spc`
```
connection "prefix_conn1" {
    plugin = "aws"
    profile = "conn1"
}
connection "prefix_conn2" {
    plugin = "aws"
    profile = "conn2"
}
connection "prefix_conn3" {
    plugin = "aws"
    profile = "conn3"
}
connection "prefix_all" {
  plugin      = "aws"
  type        = "aggregator"
  connections = ["prefix_*"]
}
```

Sample from `.aws/config`
```
[profile conn1]
source_profile = primary_profile
role_arn = arn:aws:iam::{ACCID1}:role/Audit
[profile conn2]
source_profile = primary_profile
role_arn = arn:aws:iam::{ACCID2}:role/Audit
[profile conn3]
source_profile = primary_profile
role_arn = arn:aws:iam::{ACCID3}:role/Audit
```

Output from running `aws sts get-caller-identity --profile primary_profile`
```
{
    "UserId": "{USERID}",
    "Account": "{ACCID}",
    "Arn": "arn:aws:sts::{ACCID}:assumed-role/Audit/{USERIDENTIFIER}"
}
```

**Comment by rajlearner17** [comment]
@as-bt, sorry for the delayed response; we could not replicate the exact error you mentioned; the assumed role is working as expected; maybe something we are missing that you follow.

I would like to see if you can help us get more information on your settings; I am just sharing a simple approach we took to test

Below scenario I tested 
**.aws/credential file** 

`**Example accounts**
`
- 111111111111 - ACCT1
- 222222222222 - ACCT2

**CASE-1**

```
#arn:aws:iam::222222222222:user/test-steampipe

[acct2_test_steampipe_user_only]
aws_access_key_id = {ACCESSKEY}
aws_secret_access_key = {ACCESSKEYID}

#arn:aws:iam::111111111111:role/cross-account-testing (cross-account role from ACCT1 mapped to test-steampipe-user-ACCT2)

[assume-role-cross-acct-acct1]
role_arn = arn:aws:iam::111111111111:role/cross-account-testing
source_profile = acct2_test_steampipe_user_only
```
When I add below in **aws.spc**

```
connection "acct2_test_steampipe_user_only" {
  plugin  = "aws"
  profile = "acct2_test_steampipe_user_only"
  regions = ["*"]
}

# [assume-role-cross-acct-acct1] is set in credential file > (cross-account role from ACCT1 mapped to test-steampipe-user-ACCT2)
connection "assumed_role_from_acct1" {
  plugin  = "aws"
  profile = "assume-role-cross-acct-acct1"
  regions = ["*"]
}
```
The above scenario works perfectly when we query from steampipe on the `acct2_test_steampipe_user_only` as direct access key-based and `assumed_role_from_acct1` as assumed role-based.

**CASE-2**
Assume that I move the profiles from the credential file to `.aws\config` file

```
#arn:aws:iam::111111111111:role/cross-account-testing (cross-account role from ACCT1 mapped to test-steampipe-user-nagraj)
[profile config_assume-role-cross-acct-acct1]
role_arn = arn:aws:iam::111111111111:role/cross-account-testing
source_profile = acct2_test_steampipe_user_only
```
Executed 
```
aws sts get-caller-identity --profile config_assume-role-cross-acct-acct1
{
    "UserId": "AROAXYSEVGQ77T36DQ3KT:botocore-session-1651076534",
    "Account": "111111111111",
    "Arn": "arn:aws:sts::111111111111:assumed-role/cross-account-testing/botocore-session-1651076534"
}
```
Added connection in the **aws.spc** file as below

```
connection "acct2_test_steampipe_user_only" {
  plugin  = "aws"
  profile = "acct2_test_steampipe_user_only"
  regions = ["*"]
}

# [assume-role-cross-acct-acct1] is set in credential file > (cross-account role from ACCT1 mapped to test-steampipe-user-ACCT2)
connection "assumed_role_from_acct1" {
  plugin  = "aws"
  profile = "assume-role-cross-acct-acct1"
  regions = ["*"]
}

# This is same as above, however the profile is read from the config file
connection "config_assume_role_cross_acct_acc1" {
  plugin  = "aws"
  profile = "config_assume-role-cross-acct-acct1"
  regions = ["*"]
}
```
The above setting worked as well. I am not sure if I could demonstrate the scenarios, but I am happy to clarify. I was just trying to think of what I missed here to replicate?

**Comment by as-bt** [comment]
Hey @cbruno10, 

Unfortunately I do not have direct control over the configuration of the credentials causing the issues on my end. I likely will not be able to provide any additional information on how they are configured on the back end. 

I did some testing within my own AWS accounts to see if I could replicate the issue.

Using AWS SSO I configured a role that my identity would be dropped into

`{
    "UserId": "AROAWDT3WXAFOBNS2PSSV:{MYUSER}",
    "Account": "{ACCID1}",
    "Arn": "arn:aws:sts::{ACCID1}:assumed-role/AWSReservedSSO_AdministratorAccess_108463855569a28c/{MYUSER}"
}`

I then configured a role in my second account that can be assumed by the above role
{
    "UserId": "{USERID}",
    "Account": "{ACCID2}",
    "Arn": "arn:aws:sts::{ACCID2}:assumed-role/AdministratorAccess/botocore-session-1651592240"
}

I configured the AWS credential/config files as I describe above
`[profile acc2_profile]
source_profile = acc1_profile
role_arn = arn:aws:iam::{ACCID2}:role/AdministratorAccess`

`connection "acc2_test" {
 plugin = "aws"
 profile = "acc2_profile"
}`

I then ran `steampipe query` to see if I was able to pull resources using role --> role credentials. Unfortunately (or fortunately) Steampipe did not error out with this setup and successfully pulled resources from account 2.

I think this test is close to how the original credentials were configured, but I may be missing information that I cannot access to complete the picture.

Given that neither of us were able to replicate the issue with our own configurations feel free to close out this issue unless you have other ideas.

Thanks!

**Comment by cbruno10** [comment]
@as-bt Thanks for doing more testing on your end, good to hear it works within your own AWS accounts at least.

I may have missed it in previous comments, but with the original credentials you're having issues with, are you able to run queries against any of those connections (instead of with the aggregator)? Or do you still get the same error from your original comment?

**Comment by as-bt** [comment]
Individual connections break as well as the aggregator.

I know that the original credentials are at least accepted by AWS because I can use them with the AWS CLI to pull service information down from individual accounts. The error being kicked back seems to originate from the AWS Go SDK, but at this point I'm not quite sure what part of the credential configuration is causing issues.

**Comment by cbruno10** [comment]
@as-bt Ok thanks for testing again.

Sorry that we couldn't reproduce or find a workaround, but if you are able to get additional details on how those creds are setup, we'd be happy to dive back in and see if we can reproduce/fix the underlying issue. I'm also not sure how the credentials are controlled, but if it's possible to get a different set or type of credentials, that may be helpful in testing access and debugging as well.

If you have anymore questions or details, feel free to re-open this issue, thanks!
