### ISSUE TITLE
Add table aws_glue_catalog_table

### ISSUE THREAD

**Issue by erikcw** [turbot/steampipe-plugin-aws#955]
Steampipe currently offers `aws_glue_catalog_database` to list the databases in the Glue catalog, however it is missing the related functionality of retrieving the tables inside of those databases.

I propose adding a new table containing the table definitions inside of each of those databases (columns include database, name, location, input format, etc).

**References**
[boto3 documentation for get_tables()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.get_tables)

[slack thread](https://steampipe.slack.com/archives/C01UECB59A7/p1649955204689459)

**Comment by bigdatasourav** [comment]
@erikcw Thank you for highlighting this issue, we will look into it.
