### ISSUE TITLE
Add table aws_neptune_db_cluster

### ISSUE THREAD

**Issue by tinder-tremaineeto** [turbot/steampipe-plugin-aws#960]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

- https://docs.aws.amazon.com/neptune/latest/userguide/feature-overview-db-clusters.html
- https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/neptune#Client.DescribeDBClusters
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/neptune.html#Neptune.Client.describe_db_clusters
- https://docs.aws.amazon.com/cli/latest/reference/neptune/describe-db-clusters.html

![image](https://user-images.githubusercontent.com/86266570/165646291-f618821c-6c78-486d-ad26-3bf004afd88d.png)

Can you please add the table for `aws_neptune_db_cluster`? Thanks!

**Comment by ParthaI** [comment]
@tinder-tremaineeto Thank you for raising the issue, we will take a look.
