### ISSUE TITLE
Add table aws_sagemaker_domain

### ISSUE THREAD

**Issue by tbugfinder** [turbot/steampipe-plugin-aws#970]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-domain.html

**Comment by rajlearner17** [comment]
@tbugfinder Appreciate using Steampipe!!

While we acknowledge looking into this, would you be able to share your use case of using Steampipe? This will help us with prioritising. Are other `sagemaker` tables helping you?

Thanks in advance.

**Comment by tbugfinder** [comment]
Every SageMaker Domain creation includes an EFS filesystem.
Running through multiple create/destroy operations end up in left over EFS filesystems.
We would like to find and map SageMaker Domains in use and left overs so that these can get cleaned up.

**Comment by tbugfinder** [comment]
impressive
