### ISSUE TITLE
Add support for S3 object level logging. 

### ISSUE THREAD

**Issue by rajmohanty17** [turbot/steampipe-plugin-aws#98]

**Comment by cbruno10** [comment]
Hi @rajmohanty17 , can you please describe the feature request and use case a bit more? Please include any reference links if available, thanks!

**Comment by rajmohanty17** [comment]
@cbruno10 this is the requirement, not sure if we have some way to get this from any other table 

AWS CIS 1.3.0 > Section 3.11 & 3.12

**Comment by Subhajit97** [comment]
As per discussion, we can achieve the above recommendations using `event_selectors` in `aws_cloudtrail_trail` table.
Therefore closing this issue.
