### ISSUE TITLE
Add table aws_route53_trafficpolicy

### ISSUE THREAD

**Issue by tinder-tder** [turbot/steampipe-plugin-aws#980]
**References**
Currently there isnt a way to query or list traffic policies.  Also in the `aws_route53_record` table if there is a policy applied to a record the`records` field shows 
```
"This resource record set includes an attribute that is unsupported on this Route 53 API version. Please consider using a newer API version or a tool that does so."
```
https://docs.aws.amazon.com/Route53/latest/APIReference/API_GetTrafficPolicy.html
https://docs.aws.amazon.com/Route53/latest/APIReference/API_ListTrafficPolicies.html
https://docs.aws.amazon.com/cli/latest/reference/route53/get-traffic-policy.html

**Comment by ParthaI** [comment]
Thanks, @tinder-tder for raising the issue, we will try to get it in as soon as possible and we will update you.
